### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#1]
A few errors came up when parsing the Core files:

Classes / Document / Properties / externalMap / type; ExternalMap should be colon
Classes / Extension - has no Properties section
Classes / IntegrityMethod - has no Metadata or Properties sections
Classes / Package / Metadata - subclass is not a list item
Classes / Package - has no Properties section
Classes / PublicKey - has no Properties
Vocabularies / HashAlgorithmVocab - description section should be capitalized

Some of these are easily-fixed typos.  Others require the model itself to be developed before the template can include the information.  And Classes/Agent and related elements don't exist in the current model, indicating the template should be updated.

**Comment by davaya** [comment]
README says "These files are automatically processed into regular Markdown and placed in the `generated` branch."  There is currently no generated branch, indicating that automatic processing software has not been run.  It would be a good idea to run processing software any time templates are updated to reflect changes in the logical model.

Some typos were fixed, but the `template2model` script in https://github.com/davaya/spdxv3-template-tool finds an old and a new one in Core:
* Core / core.md: id and name are not list items
* Core / Classes / Package / Metadata: SubclassOf is not a list item

and Software has not been fixed:
* Software / software.md: id and name are not list items
* Software / Classes / File / Metadata: SubclassOf is not a list item
* Software / Classes / Snippet / Metadata: SubclassOf is not a list item
* Software / Classes / SoftwarePackages / Metadata: SubclassOf is not a list item
* ...

Core/Classes has a section called `Properties`, while Software/Classes calls the same section `Data Properties`
Core/Vocabularies has a section called `Entries` while Software/Vocabularies calls the same section `Instances`

**Comment by zvr** [comment]
Closing this, as it refers to obsolete versions of files.
