### ISSUE TITLE
Punch List: Snippet

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#11]
This is a punch list of open questions from the 2021-12-07 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Define byte range, continue to follow W3C standard? 
- [x] Define snippet location - possibly as abstract class:  byte range, line range, W3C, etc.
- [ ] Will snippet location class be able to model W3C
- [x] Review 2.2 Snippet to make sure not dropped.

**Comment by iamwillbar** [comment]
* Check with Sean what UCO uses for ranges within a file.
* No strong desire to keep the W3C approach.

**Comment by goneall** [comment]
@iamwillbar In the model, there is a new property `contentIdentifier` with a type URI and the `snippetFromFile` is missing.  Did we just rename the property?  I couldn't find any record of this in the minutes.

**Comment by armintaenzertng** [comment]
I just went over the 2.3 specification and made sure that the only properties not present in the 3.0 model are part of the Licensing profile and snippetFromFile, which is discussed in #130. As `byteRange` and `lineRange` are now defined as `PositiveIntegerRange`, I think this issue can be closed.

**Comment by kestewart** [comment]
@iamwillbar - am closing this issue.  Please reopen if you disagree.
