### ISSUE TITLE
Proposal: Change Package supplier from a relationship to a property

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#113]
Discussed on the tech call on March 7, 2023.

The current model uses a `suppliedBy` relationship from the `Package` to an `Agent` to describe the supplier of a package.

In SPDX 2.3, the supplier is a property of the `Package` of type `String`.

The proposal is to change the SPDX 3.0 model to use a property of the `Package` of type `Agent`.

The following use case "supplier validation" would be solved with this change is the following:
- A consumer of an SPDX SBOM needs to make decisions based on who is supplying the package.  Examples of such decisions are capturing the license choice in a multi-licensed package (e.g. MySQL), knowing who to contact for support, understanding liability related items as it relates to who is supplying the package.
- The producer of an SPDX document wishes to support the consumer need for making supplier based decisions
- Supplier would include one and only one supplier in the SBOM for the Package(s)

In the current model using relationships, relationships can be added later and the cardinality is multiple.  If there are more than one suppliedBy relationship, it is impossible for the consumer to make the supplier based decisions.

Note that this proposal does cause an increased duplication of data in the following scenario "downstream redistribution":
- Supplier A supplies a package and documents it in an SPDX SBOM
- Downstream supplier B passes along the exact same package content and creates an SBOM referring to the same package content

In this scenario, using relationships supplier B could just add a new supplier relationship to the package defined by Supplier A.  If it were a property, a different package would need to be created with may properties duplicated.

**Comment by goneall** [comment]
In the proposal where supplier is a property of the package, the "downstream redistribution" could be solved as follows "Option A":
- A new Package is created with just the SPDX ID and any required fields based on the profile used.  Any properties which have been changed by the downstream supplier is changed as appropriate (e.g. `downloadLocation`).  For the core profile where no properties have changed, this would only be the ID since all other fields are optional.
- A relationship from the new package to the original package would be created with a relationship type of `ancestor`.
- The consumer would look for the `ancestor` relationship and use that to fill in any package properties of interest.

An alternative solution "Option B":
- A new Package is created and all properties, relationships, and annotations are copied.
- A relationship from the new package to the original package would be created with a relationship type of `ancestor`.
- The consumer would use the package information directly.

My preference would be Option A as it minimized the duplication of property values, however, it does put more burden on the consumer.

Option A as compared to the current implication would introduce one additional SPDX ID (the minimum property for those using the core profile - which I would argue is pretty minimal.  If there are any properties which have been changed by the downstream supplier, you would need to create a new Package under the current model anyway - so there would be no difference in the amount of duplication.

Also note that it is very likely one or more properties would be changed by the downstream supplier such as the `downloadLocaetion` which would require a new Package to be created.

**Comment by goneall** [comment]
After our call, I thought of one more use case that this (property) proposal doesn't support.

If you want to ask the question, "what are all the suppliers for this package where I may be able to get a copy?", the suppliedBy property will not be sufficient.

This is for 2 reasons:
- The definition of "suppliedBy" is answering the question of who supplied the package that either I'm using or I'm describing.  It is answer the specific "I used this" or "I supplied this" which is different semantics from "I could possibly this this from".
- The cardinality proposed is `0..1` which does not allow for multiple suppliers

If this is an important use case, I would suggest we keep the relationship but rename it and add a description which distinguishes the possible suppliers from the actual supplier which is used for the base of the Package definition.

**Comment by goneall** [comment]
@nishakm @sbarnum - if you could add any proposed use case solutions to the "supplier validation" use case to this issue.

@kestewart Please review, comment on my above problem and solution descriptions.

**Comment by nishakm** [comment]
@goneall Finally got a chance to look through this. Is the primary use case here "describing multiple suppliers of the same package"? I'm at a loss to come up with a scenario where this may happen considering that most build systems are not bit-for-bit reproducible, and as such, will not generate a package checksum that is the exactly the same across the board.

I could imagine an organization's relational database where they would want to ask the question "give me all possible suppliers of package with name x version a.b.c" but that information can be digested from the SBOM whether it is encoded in a Relationship or in a Package as a property.

(forgive my faux SQL in the diagram)
![sbom_package_multiple_suppliers drawio](https://user-images.githubusercontent.com/1007786/224870255-7e85396a-183e-4fc3-91fc-0812c4bc15c9.png)

**Comment by nishakm** [comment]
I thought about one use case: package mirrors
![package_mirrors drawio](https://user-images.githubusercontent.com/1007786/225066209-29fa66d3-eabd-4233-83a5-8fabd84b65f5.png)

**Comment by nishakm** [comment]
Package in a larger Package
![subpackage_supplier drawio](https://user-images.githubusercontent.com/1007786/225073232-c7a4d0e2-ea46-4304-8020-15d4630b0a46.png)

**Comment by goneall** [comment]
The tech call on 14 Mar 2023, resulted in the following proposal:

- add back the `suppliedBy` property with a range of `Agent` cardinality 0..1 (note: a future provenance / pedigree profile may further restrict this to cardinality 1).  The semantics of the `suppliedBy` property would be the supplier of the package actually used in the SBOM, i.e.: where did a really get this package from?
- rename the `suppliedBy` relationship to `availableFrom` who's `to` property would point to one or more Agents.  These Agents would represent additional suppliers where the package is available.

**Comment by sbarnum** [comment]
I believe a relationship approach is more appropriate for this than a property but understand that for 3.0 we need to start simple and it is okay to make some limiting presumptions for now allowing for future evolution as necessary once better clarity is gained through use.

If we are pursuing a property-based approach I would just want to express my strong objection to the 'ancestor'-based option A above where a derived Element only has part of its content explicitly defined and relies on following relationships to other objects to try to get the rest of its content. On a basic level, this violates our "all Elements are independent" principle. I have seen this sort of approach be disastrous in past experience. 
I would assert that ALL Elements must fully and explicitly contain all of their inherent content. Relationships and related Elements are for expressing useful contextual detail around the initial Element but not for expressing inherent detail of the Element itself.

**Comment by kestewart** [comment]
The property has been updated in #292 .
Mark this closed when the relationship has been updated as well.

**Comment by kestewart** [comment]
Relationship update handled in https://github.com/spdx/spdx-3-model/pull/296,  so marking this closed.
