### ISSUE TITLE
"Duplicate" properties?

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-3-model#114]
Looking at the diagram:

The abstract `Element` class has a property `name` of type `String`.

Some classes that "derive" from this one, also have a `name` property:
- `SpdxDocument`
- `Software/ File`
- `Software/ Package`

Is this the same? Does the existence of the property in these classes signify something?

**Comment by goneall** [comment]
I noticed the same thing.  I was wondering if this is due to a difference in cardinality?

**Comment by maxhbr** [comment]
You are right @goneall.
For example for SpdxDocument, that is for changing cardinality. `name` is required for it

But in the drawio diagram and in the markdown files I do not find the name in `Software:File` or `Software:Package`

**Comment by maxhbr** [comment]
@zvr : this is resolved, right?

**Comment by zvr** [comment]
Yes, resolved via #170.
