### ISSUE TITLE
Punch List: File

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#12]
This is a punch list of open questions from the 2021-12-07 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Review 2.x File and make sure not dropping use cases?
- [x] Are there any media types missing? 
- [x] Review Software purpose list and have definitions?

**Comment by davaya** [comment]
Is MediaType defined anywhere?  If so, it should include "application/spdx3+<syntax>" where <syntax> is from the list of supported syntaxes.

**Comment by iamwillbar** [comment]
MediaType will allow all IANA media types.
Purpose list for 2.x implemented in https://github.com/spdx/spdx-spec/pull/622.

**Comment by armintaenzertng** [comment]
Apart from the properties concerning the Licensing profile and the file type, which is tracked in #82, all 2.3 properties are accounted for. As this addresses the last open task of this issue, I think it can be closed.

**Comment by kestewart** [comment]
@iamwillbar - am closing this issue.  Please reopen if you disagree.
