### ISSUE TITLE
Creators of Creators

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#123]
I'm currently trying to implement a conversion prototype from SPDX 2 to 3. Due to Agents being Elements with CreationInfo there are some aspects which I'd like to have clarification on:

When converting the document's [creators](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#68-creator-field), what will the SPDX3 field `created_by` of their CreationInfo look like? Will it contain all SPDX2 creators? Or only the non-tool ones? Or...?

When converting an annotation's [annotator](https://spdx.github.io/spdx-spec/v2.3/annotations/#121-annotator-field), what will the SPDX3 field `created_by` of their CreationInfo look like? Will it contain only itself? Or itself plus the document's creators (if it is distinct from them)?

Is the CreationInfo of an Creator/Annotator even relevant for anyone?

While we are at it (not related to conversion): What if I add a supplier to a package -- that I have not created -- via a relationship some time after the package has been created? I would probably have to add two Agents then: One for the supplier and one for myself who created the supplier (and myself). Is that correct?

**Comment by maxhbr** [comment]
I think, when going from 2.x to 3, there is just a single creator set, which is the `Creator` that yo linked to. And everything in that document is created by that.

in the example
```
Creator: Person: Jane Doe ()
Creator: Organization: ExampleCodeInspect ()
Creator: Tool: LicenseFind-1.0
```

the person would be created by all three entries, the Organization also, and so on.

**Comment by armintaenzertng** [comment]
Thanks for linking the discussion, Sebastian! :)

If I understand this correctly, a SPDX2 Creator of type "Tool" should be converted to a `createdUsing` property which points to a SPDX3 `Tool`.
@goneall: I believe this goes against the [current migration guideline](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.9fsqrwd7zpc2) which states that a SPDX2 CreationInfo actor should be converted to `SoftwareAgent` and not to `Tool`.

**Comment by goneall** [comment]
Thanks @seabass-labrax and @armintaenzertng for pointing out the issue in the migration guide.  I just updated the document in suggestion mode to be consistent with the meeting minutes.  Please have a look and let me know any suggestions: https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.9fsqrwd7zpc2

**Comment by seabass-labrax** [comment]
That looks good. One thing to add might be the case where a 2.3 document has only 'created by tool', and the other fields are anonymous (such as when using the REUSE tool to generate SPDX). I think at a minimum, `createdBy` would become the `Agent` representing the user of the conversion tooling, so if Armin converted a SPDX 2.3 document with

```
Creator: Person: Anonymous ()
Creator: Organization: Anonymous ()
Creator: Tool: reuse-0.14.0
```

...this would become something like

```
"createdBy": "https://example.com/ld/spdx/persons/armin/1",
"createdUsing: "https://example.com/ld/spdx/tools/reuse-0.14.0",
```

**Comment by armintaenzertng** [comment]
@seabass-labrax, your approach will lead to problems during automated conversion as we plan to have in the python-tools.
Even if we found some obscure way to ask the current user of the conversion tool for their creator details, I'm not sure that they would indeed be the right person to include in the CreationInfo. (The example above suggests that Armin used the reuse tool, but he never did.)

As a sidenote: I'm not aware that "Anonymous" is a special keyword in SPDX, so our tooling would treat this as the creator's name.

**Comment by goneall** [comment]
@armintaenzertng - Do you think this is an issue with the model or something we can fix in documentation?

**Comment by armintaenzertng** [comment]
@goneall, I made a few remarks in the migration guide which hopefully help solving the confusion around this topic.

I don't think there is a model issue here apart from the fact that creators of creators are simply confusing.

**Comment by goneall** [comment]
@armintaenzertng - I attempted to update the migration guide per suggestion.  Feel free to propose any different text in the migration document itself.  Once that is updated, we can close this issue.

**Comment by goneall** [comment]
It looks like this issue is resolved with the updated migration guide - closing
