### ISSUE TITLE
Change cardinality of Relationship "to" property from 1..* to 0..*

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#129]
If a Relationship has a completeness of `noAssertion`, there would not be an element for the `to` property.

This could be solved in one of three ways:
1. Have a special Element `NoAssertion` that would be referenced in the `to` property.  This is similar to today's solution.
2. Change the cardinality of `to` from `1..*` to `0..*` and leave the `completeness` property as is (including a `noAssertion` value).
3. Change the cardinality of `to` from `1..*` to `0..*` and remove the `noAssertion` value from the `completeness` property since having a `to` with no elements would imply `noAssertion`.

My preference would be 2 above is it is the cleanest to implement.  The only downside I can think of is having a `noAssertion` value and having one or more `to` elements doesn't seem to make sense.

Having a `NoAssertion` element in solution 1 above is quite challenging to implement in some computer languages and in RDF, as we learned in the SPDX 2.X implementations.

**Comment by seabass-labrax** [comment]
As I have mentioned during a recent SPDX Tech Team meeting, I think this is a bizarre and pooly-defined aspect of SPDX, and thus should not be included in the forthcoming SPDX 3.0 specification. I'm aware that some stakeholders (seemingly with affiliations related exclusively to computer security efforts in the USA) have expressed a desire for a 'known unknown' facility in Software Bill of Materials, but I have yet to see a concrete example of such a capability being used in reality.

My preference would therefore be No. 3, as it at least allows Relationship Elements with empty 'To' fields to be ignored in processing without undue difficulty.

**Comment by kestewart** [comment]
Resolved in https://github.com/spdx/spdx-3-model/pull/293
