### ISSUE TITLE
License Profile: add licenseListVersion to Creation Information

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#131]
In the SPDX 2.3 spec, the license list version used for an SPDX document is captured as specified in [spec 6.7](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#67-license-list-version-field).

The current licensing-profile branch does not include a property of licenseListVersion or an extension to the CreationInformation class to include this as an optional property.

This may have just been an oversight.

**Comment by seabass-labrax** [comment]
I've attended almost every Legal Team and Tech Team meeting during the last couple of years and don't recall this ever being a topic of discussion. As such I agree that it is probably an oversight; plus, I don't immediately see a reason why licenseListVersion would not still be relevant in SPDX 3.0.

**Comment by seabass-labrax** [comment]
My initial reaction is that this property should apply to the SPDX Element which uses the License Expressions. It can be optional in the case where an SPDX Element does not contain any licensing-related information.

**Comment by swinslow** [comment]
Moving to 3.0, as I'll want to understand better how to incorporate this into CreationInfo and don't think we'll add that for 3.0-rc.

**Comment by goneall** [comment]
I'll create a PR for this one

**Comment by goneall** [comment]
Proposing we add this as a property to `LicenseExpression` as suggested by @seabass-labrax 

It seems that it would only be applicable for the expressions.

I'll create a PR proposal once PR #444 is merged since it may cause a conflict.

**Comment by zvr** [comment]
Ah, @goneall, I am confused:
- you write "Proposing we add this as a property to `LicenseExpression`"
- there is a commit automatically mentioned above that references this
- but the PR automatically mentioned above adds it to `CreationInfo` instead...

**Comment by goneall** [comment]
@zvr There are now two PR's - one for each proposal.  We can choose one and throw the other away.

Do you have an opinion on the newly created PR for the licenseExpression?
