### ISSUE TITLE
Change homePage property back to doap:homepage

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#132]
SPDX 2.3 uses a pre-existing RDF vocabulary [DOAP](https://en.wikipedia.org/wiki/DOAP) for the package home page property.

Using DOAP has the advantage of correlating similar information from different sources without having to do explicit mappings.

Using DOAP will also maintain compatibility with SPDX 2.3.

**Comment by seabass-labrax** [comment]
This has my full agreement. We should make sure to add DOAP to the
Normative References section; it's currently missing from in SPDX 2.3.

**Comment by kestewart** [comment]
@maxhbr - can you generate this PR to make the change from xsd:string back to DOAP?    I believe the fix should be made in https://github.com/spdx/spdx-3-model/blob/main/model/Software/Properties/homePage.md, but am not sure how to encode up the DOAP change.

**Comment by kestewart** [comment]
@goneall - can you tackle this?

**Comment by kestewart** [comment]
DIscussed with Thomas & Gary, and this isn't essential for rc1 so moving to the next rc.

**Comment by goneall** [comment]
Decision was made to keep the namespace as an SPDX namespace
