### ISSUE TITLE
Rename packagePurpose to primaryPackagePurpose

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#133]
The current model show `packagePurpose` as the property name in the SPDX 3 model diagram.  Late in the 2.3 review cycle, we renamed this property to `primaryPackagePurpose`.  We likely just missed updating the SPDX 3 model diagram.

**Comment by zvr** [comment]
Does it make sense to have it named _Primary_ if we can have a list of values?

**Comment by seabass-labrax** [comment]
The consensus was to add two properties:

- We decided to add PrimaryPackagePurpose (with a cardinality of 0..1) in SPDX 2.3 as it was felt that it would be immediately useful for some security-related use-cases

- We decided to add PackagePurpose (with a cardinality of 0..*) in SPDX 3.0, where more flexibility would be desired

Please see https://github.com/spdx/spdx-spec/issues/720#issuecomment-1161850272 for more context.

**Comment by zvr** [comment]
@goneall do you suggest we should also change `filePurpose` and `snippetPurpose` accordingly?

**Comment by goneall** [comment]
< @goneall do you suggest we should also change filePurpose and snippetPurpose accordingly?

@zvr Although I don't know of any specific use cases for `filePurpose` and `snippetPurpose`, it probably would be good to have the same structure and terminology as the Package - so short answer is yes.

**Comment by kestewart** [comment]
Reviewed - https://github.com/spdx/spdx-3-model/tree/main/model/Software/Properties and packagePurpose, filePurpose & snippetPurpose have all been added.    Closing this.

**Comment by goneall** [comment]
Reopening this issue - the comment above is not correct as of 6 May 2023, there is only `purpose`

**Comment by goneall** [comment]
Purpose was originally proposed by me to accommodate lossless round-trip translation to CycloneDX type property in the Component class.  CycloneDX only allows 1 value.  If we have a cardinality of greater than 1, it is impossible to do a lossless translation.

If we want to allow multiple purposes, we could have 2 properties:
- purpose - cardinality 0..*
- primaryPurpose - cardinality 0..1

Personally, I think we only need primary purpose, but if there are use cases for multiple I'm OK adding.

**Comment by goneall** [comment]
@zvr @kestewart thoughts?

**Comment by goneall** [comment]
Note that in the description for the purpose property, it describes a "primary purpose" with an implied cardinality of 0..1.

**Comment by kestewart** [comment]
From the prior discussions in https://github.com/spdx/spdx-spec/issues/720#issuecomment-1161850272,  I read it as the decision was made to have a PrimaryPackagePurpose AND PackagePurpose fields in 3.0.    I'm ok with moving the field we have to be the PrimaryPackagePurpose, but we need to consider if we still want a PackagePurpose as discussed before.  @goneall

**Comment by goneall** [comment]
@kestewart I just went back and read all the comments.  It looks like @nishakm and @seabass-labrax were proponents of cardinality 0..*.  I'm not sure I understand the use cases, however.  Before adding in a second property, I would like to make sure there is a solid use case and there is a high probability it will actually be used.  Having 2 properties with essentially the same semantics but different cardinality could be confusing to the casual reader of the spec.

If we do add the second parameter, perhaps we should come up with a clearer name - like `additionalPurpose` to make it clear you should use the primary purpose first.

**Comment by zvr** [comment]
I _think_ I prefer a `purpose: 0..*` because:

- we can record multiple purposes
- it's simpler to have a single property
- if we ingest CDX, we can record the (single) value in the data

Downside is that, if our data contains multiple values, it cannot be represented in CDX. I'm not sure this should be a limiting factor for us.

**Comment by goneall** [comment]
I definitely want to continue to support lossless translations between CDX and SPDX and having a cardinality of `0..1` is required for this.

I understand the theoretical interest an having a multiple cardinality, but I wonder if it will really be used.  If anyone plans to use more than one purpose, I will support adding a second property `purposes` but feel strongly we should keep the `primaryPurpose`.
