### ISSUE TITLE
Rename class CreationInformation to CreationInfo

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#134]
SPDX 2.3 uses the name CreationInfo for name of the class containing creation information.  The current SPDX 3.0 model uses the name CreationInformation.

I don't recall discussing a rationale for the change, so it may just be an oversight.

Suggest changing the name to be compatible with the SPDX 2.3 spec.

**Comment by seabass-labrax** [comment]
There should not be a class for creation information in SPDX 3.0. Creation information is specific to each Element, and so the appropriate way of modelling this in RDF is to have separate properties attached to the Element resources. That is to say:

```xml
<spdx:Element>
  <spdx:createdBy rdf:resource="https://example.com/ld/spdx/identities/seabass"/>
  <spdx:createdUsing rdf:resource="https://example.com/ld/spdx/tools/emacs-27.1"/>
  <spdx:created rdf:datatype="spdx:dateTime">
    Mon, 20 Mar 2023 21:29:08 +0000
  </spdx:created>
  ...
</spdx:Element>
```

**Comment by goneall** [comment]
@seabass-labrax This was already discussed and we agreed to make this a "data type" class.

**Comment by seabass-labrax** [comment]
I think you might find that there's no indication of such a decision in the SPDX Tech Team minutes, but if you do know of a record of this, please let me know; I intend to bring up the topic at tomorrow's meeting.

**Comment by goneall** [comment]
@seabass-labrax I believe @iamwillbar updated the diagram to it's current state after the meeting.  The diagram shows a `CreationInformation` struct/class.  This issue is simply requesting the name be changed from `CreationInformation` to `CreationInfo`.

**Comment by goneall** [comment]
@seabass-labrax It looks like the structure of `CreationInformation` is being covered by issue #80 

I would suggest we focus this issue on just the name and continue the discussion on structure in issue #80

**Comment by goneall** [comment]
Update from SPDX tech call on 21 March 2023:

Without commenting on the structure issue raised by @seabass-labrax above, no one on the tech call disagreed with renaming `CreationInformation` to `CreationInfo` as it is currently represented in the model diagram.
