### ISSUE TITLE
Serialization: Hash structure and readability

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#137]
We discussed tag-value and readable file formats at the 3/23 serialization subteam meeting, including the checksum example from the [2.3 spec](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/examples/SPDXJSONExample-v2.3.spdx.json).

In 3.0 this looks like:
![image](https://user-images.githubusercontent.com/19152940/227522717-4ac452b6-dff5-4eed-9754-15e82d49891c.png)

and could be serialized as in 2.3 JSON with a list of "algorithm" and "checksumValue" properties.  But it is more compact and readable to serialize them as maps with algorithm as the key as they appear in the 2.3 Tag-Value format:

![image](https://user-images.githubusercontent.com/19152940/227523939-c13316af-c35b-4509-8aa1-e217b2570929.png)

It was mentioned that the "other" algorithm can have more than one value, which is allowed in all three alternatives:
1. list of "algorithm" and "checksumValue" properties
2. list of maps
3. single map with the "other" algorithm having a set of values

Serialization should be defined by a schema, not using ad-hoc examples, and in 3.0 the logical model can either include serialization constraints, or those constraints can be designed and documented in a separate serialization model:

```
     package: "http://acme.com/checksum-test/v1"
     exports: ["Checksums"]

Checksums = Record
   1 checksums1       Checksum1 [1..*]
   2 checksums2       Checksum2 [1..*]
   3 checksums3       Checksum3

Checksum1 = Record
   1 algorithm        Algorithm
   2 checksumValue    Generic

Algorithm = Enumerated
   0 other
   1 md5
   2 sha1
   3 sha256
   4 blake2b_384

Generic = Binary /x

Checksum2 = Choice
   0 other            Generic
   1 md5              Binary{16..16} /x
   2 sha1             Binary{20..20} /x
   3 sha256           Binary{32..32} /x
   4 blake2b_384      Binary{48..48} /x

Checksum3 = Map{1..*}
   0 other            Generic [0..*]
   1 md5              Binary{16..16} /x optional
   2 sha1             Binary{20..20} /x optional
   3 sha256           Binary{32..32} /x optional
   4 blake2b_384      Binary{48..48} /x optional
```

The "single source of truth" should contain enough detail to generate a serialization schema as above, ensuring that the data format is defined and that data in the selected format can both be validated and is consistent with the logical model.  In this example the second and third alternatives are not only more readable than the first, they allow the checksum size to be specified per algorithm and validated.

**Comment by goneall** [comment]
I agree it is more compact, but I prefer the list approach for it's match to the logical model, perhaps more flexible, and (you guessed it) compatibility with SPDX 2.3.

**Comment by davaya** [comment]
A direct correspondence between logical model and serialized values is best, but as Willliam says, logical types can be serialized in any manner, and a serialization model allows that difference to be defined if necessary.

In this case I'd propose making the logical model a direct representation of the serialized value - a data type class with properties like all other classes:
![image](https://user-images.githubusercontent.com/19152940/227601234-a9ea468b-97aa-4820-a860-632a08777706.png)

This has the important benefit of being able to set property types on a type-by-type basis, particularly for checksum algorithms that have parameters in addition to just bare values.

**Comment by maxhbr** [comment]
I have three comments that all go in the same direction of "hashes are maybe more then just algorithm and value":

#### Comment 1:
How would you add the `PackageVerificationCode` in that example, which as far as I understand will derive from `Hash` or `IntegrityMethod`. It has
- an algorithm: `PackageVerificationCode`
- a hashValue, e.g. `d6a770ba38583ed4bb4525bd96e50461655d2758`
- a list of excluded files, e.g. `./package.spdx`

The [example](https://spdx.github.io/spdx-spec/v2-draft/package-information/#79-package-verification-code-field) shows that in tag-value as:
```
PackageVerificationCode: d6a770ba38583ed4bb4525bd96e50461655d2758 (excludes: ./package.spdx)
```

#### Comment 2:
Also profiles might extend `Hash` or `IntegrityMethod` in a way that does not match the simple examples above.

#### Comment 3:
Every single hash can have a `comment` (derived from `IntegrityMethod` in the diagram above), how does that fit into your example?

**Comment by davaya** [comment]
The simple example just replaced the current enumeration.

Extending it demonstrates how requirements for specific algorithms can be accommodated.  The property "packageVerificationCode" would be a type that included a "value" property of type bytes, and a property "excludedFiles" of type string [0..*]:

![image](https://user-images.githubusercontent.com/19152940/227791297-917203d9-6a97-40d2-93e6-31ccb5840ddd.png)

**Comment by goneall** [comment]
This depends on the resolution of #345

**Comment by goneall** [comment]
Based on discussion in the security meeting on 12 Jan 2023, the support of package verification code will be postponed until after RC2 - retargeting this issue for post RC2.

**Comment by goneall** [comment]
@jeff-schutt @zvr @maxhbr - Just bringing this issue to your attention as it relates to the recent verification code discussions
