### ISSUE TITLE
Punch List: Collection

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#14]
This is a punch list of open questions from the 2021-12-07 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:
 
- [ ]  Is Collection a peer or a container of its members?

**Comment by davaya** [comment]
A logical model defines associations between types - all logical types (including Element) may be associated with other types, and the nature of the association is a semantic label, not a data structure.

An information model defines data structures, and there are only two kinds of association between data types: contain and reference.  For example the members of a list are serialized in a document as either values or references to values, and the information model must specify which.

The SPDX logical model defines the semantics of Collection as an Element that has 0..* "element" Elements and 0..* "rootElement" Elements.  Unlike "describes", "contains" or "depends_on", "element" is an anodyne association label that means nothing more than "member" of the collection. At the logical level no Element contains another Element; all Elements are peers.

A formal SPDX information model, or the prose of an SPDX specification and example data, could show Collection as a list of Element values or Element ids.  The disadvantage of requiring Collection to be a list of values is that no Element can be a member of more than one collection, or its data must be copied into every collection of which it is a member.

Position:
* The data representing a Collection must be a set of Element IDs (references), not a set of (contained) Element values.
* A Collection Element listing the elements in an SPDX document may optionally be included within that document, but serves no purpose.
* A Collection Element listing the elements in an SPDX document may optionally be included in a different document, serving as an index of the referenced document.

**Comment by armintaenzertng** [comment]
Is this issue still relevant for the 3.0 release? The only point I see that does not align with the current model is the topic of having a list of elements vs a list of references to those elements. But relationships and annotations also have properties of range Element (`to` and `subject`, respectively), so this would affect them, too?

**Comment by kestewart** [comment]
@iamwillbar - am closing this issue for now.  Please reopen if you disagree.
