### ISSUE TITLE
Punch List: BOM & SBOM

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#16]
This is a punch list of open questions from the 2021-12-14 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Why do we need these?    Marketing/expectation management.
   * Package artifact is always the top level.   Everything that follows from it is a SBOM.
     SBOM is about the package.  Package is about the package, it's also not the package.
- [x] Is SBOM and Package the same thing?
- [x] Does having an SBOM replace the need for document DESCRIBES relationship?
- [x] How does SBOM relate to document?
- [x] Is SBOM the same as artifact?   What does an artifact describe?
- [x] Artifact could be a service, device, feature.
- [x] Is defining feature of BOM that it is comprehensive?
  - [x] Is this BOM ready to ship, does it capture everything it is meant to provide?   SBOM would just be software?

**Comment by davaya** [comment]
The meaning of "Document" is still under discussion, so temporarily use "SpdxDocument" as an SPDX Element that:
1. inherits from Artifact
2. has an "elements" property containing a set of Element IRIs
3. describes a document containing the serialized values of the Elements listed in "elements"

Consider three example serialized SPDX documents, each containing three Elements::
A. three License Elements
B. a Package Element plus two License Elements
C. a Package Element plus two File Elements

SPDX documents are serialized bytes contained in a file or returned from an API.  The act of serializing a set of Elements creates a "file", and if the file is to be referenced/re-used then a "SpdxDocument" Element can be created to describe it.  If the file is not persistent or not referenced then there is no need to create a new Element; the file exists independently of any Elements that describe it.

* **Is BOM/SBOM an unnecessary marketing term?**  No, it is a necessary term but an unnecessary Element if the logical model defines (Spdx)Document to describe a collection of serialized Element values. It has been argued that A is not an SBOM but C is.  I believe (S)BOM is an appropriate name for all of A, B, and C, but if not then some name is needed for all "SPDX files".

* **Is SBOM and Package the same thing?** A package is a real-world (hardware or software) entity. A Package Element describes a package entity. A BOM/SBOM is a serialized collection of Elements that may include zero or more Package Elements.

* **Is SBOM the same as artifact? What does an artifact describe?**  A software package is an artifact containing software. An SBOM is an artifact containing serialized SPDX Elements.

* **How does SBOM relate to document?** SBOM may be (in my opinion, see above) a synonym for an SPDX document.

**Comment by davaya** [comment]
**Foundational Assumption:** SPDX v3 is Element-based, i.e., if no Elements have ever been serialized, an observer can look at 157 individual independent Element values in a model store and determine what SBOM(s) they represent.  "SBOM" has two distinct meanings: "a collection of Elements" and "a document".   Both of them are real meanings but the difference is a source of confusion.

A "package" is a collection of hardware/software components.  A "BOM" is a collection of Elements, some of which describe artifacts (HW/SW components) while others are not artifacts (identities, annotations, relationships, licenses, etc.).  An SPDX document is an artifact containing any set of serialized Element values.

Consider three example documents:
A. three License Elements
B. a Package Element plus two File Elements
C. an SBOM Element plus two File Elements

* **Is BOM/SBOM an unnecessary marketing term?**  No.  A BOM Element is a collection of Elements describing an artifact, while a document contains any Element values.
    * All of A, B and C are "SBOM documents".
    * Only C is an "SBOM collection"
    * B might look like an SBOM collection, but Package has been switched from extending Collection to extending Artifact, and thus has no members. B has metadata about a package and two files that may or may not be in the package,

* **Is SBOM and Package the same thing?** No.  Package has a "packagePurpose" property that includes BOM as an option.  BOM should be removed from the list, to remove any confusion with the BOM Element type.

* **Is SBOM the same as artifact? What does an artifact describe?**  A software package is an artifact containing software. An "SBOM collection" is a set of Elements describing an artifact.  An "SBOM document" is an artifact containing arbitrary serialized SPDX Elements.

* **How does SBOM relate to document?** "SBOM document" is a synonym for SPDX document.  The distinction between "SBOM document" and "SBOM collection" is still a great source of confusion, particularly if the foundational assumption is not agreed/understood.
