### ISSUE TITLE
Security: Multiple definitions of `severity`

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#166]
`severity` is defined in multiple sub-classes of `VulnerabilityCategorization`, with a different type in each. I suggest renaming the properties, for example: `cvssV2Severity`, `cvssV3Severity`, `epssSeverity` and `genericSeverity`.

**Comment by kestewart** [comment]
This has been resolved as part of merging the Security Profile into main.   If you disagree, please reopen.
