### ISSUE TITLE
Add (back) defining document to the ExternalMap

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#169]
In the Sean's proposal for the ExternalMap, there was a property `definingDocument` with a value of the URI ID for the document which contains the definition.  This makes is straightforward find the document information including the verification checksum for any element defined externally.

If we don't add this back in, we need to define an algorithm for how you map an externally defined element to the document that contains the element.

**Comment by goneall** [comment]
From the conversation in the migration document with Sean, we need to add this property back.

**Comment by sbarnum** [comment]
I strongly support this.
The definingDocument property was an integral part of our discussions/design for ExternalMap but got lost somewhere along the way.
This simple property enables ExternalMap to much more simply support SPDX 2.X style use cases and migration.

NOTE: the value of this property is a URI ID once expanded (which may be its native state) (e.g., "http://spdx.org/spdxdocs/zephyr-d41a5faf-c09e-4c40-bbad-d69a3bdbf100/app#SPDXRef-DOCUMENT" but in serialized form could also be a prefixed (compacted) form of the identifier (e.g. "DocumentRef-app:SPDXRef-DOCUMENT") with the prefix defined in the NamespaceMap (e.g., prefix="DocumentRef-app", value="http://spdx.org/spdxdocs/zephyr-d41a5faf-c09e-4c40-bbad-d69a3bdbf100/app#")
