### ISSUE TITLE
Question: Namespace for SPDX

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#172]
The current namespace for SPDX is `http://spdx.org/rdf/terms` with the 2.3 version namespace `http://spdx.org/rdf/terms/2.3`.

In SPDX 3, we have different namespaces for the different profiles.

Two questions:
- What is the exact namespace (e.g. `http://spdx.org/rdf/terms/[profile]/[version]`)?
- Do we want to relate the 2.3 terms to the equivalant 3.0 terms (e.g. using `owl:sameAs`)?

**Comment by zvr** [comment]
Documented in https://github.com/spdx/spdx-3-model/blob/main/serialization/rdf.md

**Comment by kestewart** [comment]
Closing this for now, as it's documented.   Reopen if something still needs to be done.
