### ISSUE TITLE
Punch List: Collection

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#18]
This is a punch list of open questions from the 2021-12-14 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Does collection really need a namespace map and an external map?

**Comment by davaya** [comment]
No.

Document is a specific type of Collection, a container of serialized Element values.  NamespaceMap and ExternalMap exist only to support serialization, and would not be shown in the logical model at all if SPDX had a formal information model that defined serialization features common across all serialization formats.

If included in the logical model, NamespaceMap and ExternalMap should be properties of Document only.
