### ISSUE TITLE
`createdBy` might not receive a value during 2->3 conversion

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#180]
For specifying the "who" in CreationInfo, we have both `createdBy` (for Agents) and `createdUsing` (for Tools), with only the former being mandatory.
During conversion from SPDX 2.3 we convert the `creator` property to `createdBy` in the case of Persons and Organizations and to `createdUsing` in the case of Tools. ([See the migration guideline](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit))

Now, in 2.3 it is not mandatory to have a Person or Organization as creator. This would lead to an invalid SPDX 3 document as we have no value for `createdBy`.

**Comment by goneall** [comment]
A couple of thoughts on this issue.  

It is a likely scenario based on my experience with SPDX 2.X.  There are a lot of tools that will just fill in tool as the CreationInfo and not require a user to fill in the needed information for the additional createdBy property.

I personally like the proposed required createdBy, but we'll need some type of upgrade path.

One initial thought is to create an Agent just for this type of migration issue. Something like a `createdBy` value of type `SoftwareAgent` which points to the tool used and a hint that it was migrated from SPDX 2.X.

**Comment by kestewart** [comment]
Based on discussion with William,  +1 to Gary's advice to use value of type SoftwareAgent.

**Comment by kestewart** [comment]
Closing,  please reopen if still an issue.
