### ISSUE TITLE
Punch List: ExternalMap

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#20]
This is a punch list of open questions from the 2021-12-14 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Should we change the cardinality of verified using to be optional? (See where it resides, but don't want to verify integrity) Possibly using an integrity profile? 
- [x] Can a single element be serialized into a document with just the bytes of that document?   Do you need the bytes of two elements in serialized data, or just the bytes of one element?   
- [x] Is Document only for serialization?
- [x] In git, what it hashes, it goes through a filter to do normalization.
- [x] Do we need to clarify between external map (SPDX understand) and external reference (SPDX is opaque to, and doesn't follow further)?   Should ExternalMap be renamed ExternalSPDXMap or something like imply that understanding?
- [x] Some confusion about external id vs. Element URL 
- [x] Should document hang off element and namespacemap and externalmap hang off document?

**Comment by davaya** [comment]
**external id vs. Element URL**:

* The "artifactUrl" property uniquely identifies a real-world entity that can be described by an SPDX Element, such as a software package or a serialized SPDX document.
* The "id" property uniquely identifies an Element of any type,
* The ExternalMap type is not an Element, it maps an "id" property to a definingDocument with an artifactUrl that uniquely identifies a serialized document containing the Element with that id.

There could be many documents containing the serialized value of an Element.  ExternalMap maps an element id to one of those documents.

**Is Document only for serialization:**

* There is no prohibition on creating a logical Document Element that describes a document artifact.
* There is no need to create a logical Document Element to support serialization.  It is sufficient for the serialized bytes in one document to reference elements in another document using ExternalMap.  The referenced document is assumed to be available.
* If a document references an Element but does not contain an ExternalMap entry for its id, the Element value is assumed to be available from a model store.

**Comment by kestewart** [comment]
Discussed with William, and updated punch list.  Closing this for 3.0-rc1
