### ISSUE TITLE
Software Profile Release Candidate Punch List

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#200]
WIP - This is a running list of issues that need to be resolved before the SPDX 3.0 release candidate

- [x] Add Software Dependency Relationship PR #69 
- [x]  Add in reconciled set of valid software types, as refined in tech team discussions & with profile needs merged.
- [x] TODO add in as work through issues list (Kate & Gary)

**Comment by kestewart** [comment]
Closing off this punchlist for 3.0-rc;   we should start new 3.0 final one.
