### ISSUE TITLE
Core Profile Release Candidate Punch List

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#201]
WIP - This is a running list of issues that need to be resolved before the SPDX 3.0 release candidate

- [ ] ~~Add Actor Identifier PR #173 @davaya to update diagram, @iamwillbar to review~~

**Comment by davaya** [comment]
Replaced by #202

**Comment by kestewart** [comment]
This can be closed when https://github.com/spdx/spdx-3-model/pull/202 is resolved.

**Comment by goneall** [comment]
Moved Actor resolutions to RC2
