### ISSUE TITLE
Licensing: Where should contextual meanings of NONE / NOASSERTION be stated?

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#204]
Currently, in the [licensing-profile branch](https://github.com/spdx/spdx-3-model/tree/licensing-profile/model), the Classes [NoneLicense](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/NoneLicense.md) and [NoAssertionLicense](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/NoAssertionLicense.md) contain brief descriptions of their meanings.

However, because these values have slightly different meanings in the Declared License vs. Concluded License context, the specific meanings of "NONE" and "NOASSERTION" for these uses are spelled out in the [declaredLicense](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Properties/declaredLicense.md) and [concludedLicense](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Properties/concludedLicense.md) Properties files.

I'm fine with either structure, but wanted to confirm with the broader SPDX 3.0 team about which location you feel is preferable.

**Comment by swinslow** [comment]
Just to note, a similar question applies to the NoneText and NoAssertionText classes.

Also, I'm guessing the resolution of this issue to some extent depends upon how we're handling #71 / #76.

**Comment by goneall** [comment]
In the tech call discussion on 17 April 2023, we discussed having an Individual Value for NONE and NOASSERTION rather than different classes / types.  We still need to finish a few details on how this would be implemented consistently across the profiles before making any updates.

**Comment by zvr** [comment]
Are we talking about different individuals per class/type (like _NoneLicense_ and _NoAssertionLicense_) or single individuals _None_ and _NoAssertion_ that will be used in different use cases?

**Comment by goneall** [comment]
> Are we talking about different individuals per class/type (like NoneLicense and NoAssertionLicense) or single individuals None and NoAssertion that will be used in different use cases?

That wasn't specified in the call.  My proposal would be to have it per class/type which is different from the SPDX 2.3 model.  Having it per type would simplify the range values for the properties and better match the programming model used by the various tools.

For the text type, I would propose we just use a single NONE and NOASSERTION individual of type xsd:string for RDF.  For non-RDF serializations, we can just describe the meaning of NONE and NOASSERTION text values in the property descriptions as we do today.

**Comment by swinslow** [comment]
I think there are aspects of it that remain open to be reconsidered for 3.0, so I'm going to set this to 3.0.

**Comment by goneall** [comment]
I'll create a PR for this one.

**Comment by goneall** [comment]
This is resolved with PR #456
