### ISSUE TITLE
Licensing: Type and formatting for LicenseID properties

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#205]
A couple of related questions here:
* In the parent abstract class [License](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/License.md), should `licenseId` be an `xsd:string` or some separately-defined type?
* For [CustomLicense](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/CustomLicense.md), how should it be expressed that the prefix must be `LicenseRef-` and how should the set of permitted characters in the identifier be specified?

**Comment by goneall** [comment]
@swinslow Excellent question.  Based on how we treat the Element ID's, the `licenseId` should be a URI.

A bit more info on how it works in SPDX 2.X (and how I would propose it would work in SPDX 3.0):
- The ID is a `fragment` - the string after the `#` in a URI - is the ID.  The namespace for the listed licenses is `http:\\spdx.org/licenses`.  For local licenses (e.g. `LicenseRef-`) the namespace would be the namespace of the "Document" or default namespace.

**Comment by swinslow** [comment]
Thanks @goneall, your comment was very helpful and pulled together some concepts that I think I hadn't considered before. I'm not going to change this for 3.0-rc, but I suspect we may need to revisit this for 3.0, so I'm going to tag it for that milestone.

**Comment by goneall** [comment]
We've decided to inherit the ID's from element and have a mapping table for expressions that use LicenseRef- style id's.

See PR #444 for more detail.
