### ISSUE TITLE
Licensing: Fix NONE / NOASSERTION for copyright text

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#207]
Relates to #204, #71 and #76

Currently, there is a FIXME note in the [CopyrightTextField](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/CopyrightTextField.md) to fix the statement of what NONE and NOASSERTION means in the context of the copyright text field.

Deciding where to put this relates to the open question in #204 about where the meanings of NONE / NOASSERTION should be specified, and also to the questions in #76 about how to model fields generally that can contain these values.

**Comment by swinslow** [comment]
Note @tsteenbe's comment at https://github.com/spdx/spdx-3-model/pull/277#discussion_r1186061592 -- suggestion to rename `NoneText` in Licensing to `NoneCopyrightText`.

If NONE / NOASSERTION for text fields will generally be handled as just a string with special meaning attributed to `"NONE"` and `"NOASSERTION"`, then we'll just get rid of the NoneText / NoAssertionText classes. But if those specialized classes will stay, then I agree with @tsteenbe that it would be better to rename them to be specific to Copyright text if that's the intent.

**Comment by swinslow** [comment]
The FIXME note has been removed, but I want to leave this open for 3.0 for consideration of @tsteenbe's comment noted above.

**Comment by goneall** [comment]
I opened issue #446 to add the copyright text back in - somehow we lost it.  I'm closing this issue as it contains a reference to this issue.

**Comment by goneall** [comment]
After further investigation, the `copyrightText` property is on the `SoftwareArtifact` class and has a description describing the NONE and NOASSERTION values.

I believe this is sufficient to resolve the issue.

@swinslow @zvr if you disagree, please open a pull request with a proposed solution.
