### ISSUE TITLE
Licensing: Update custom license additions

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#208]
**NOTE**: This issue is pending resolution of the change proposal at https://github.com/spdx/change-proposal/issues/4

Several of the classes currently shown in the Licensing profile are just listed as placeholders, and should not be filled in until the Change Proposal linked above is resolved.

Depending on the resolution of that Change Proposal, the names and meanings of several of the Classes may be adjusted accordingly.

**Comment by swinslow** [comment]
The relevant Classes include the following (all links from the licensing-profile branch):
* [WithExceptionOperator](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/WithExceptionOperator.md)
* [ListedLicenseException](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/ListedLicenseException.md)
* [CustomLicenseException](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/CustomLicenseException.md)
* [LicenseException](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Classes/LicenseException.md)

**Comment by swinslow** [comment]
With #268, I believe this has now been implemented for purposes of the 3.0-rc data model.

Further updates are needed to some of the ancillary SPDX spec materials, in particular updating the License Expression Syntax in the prior annex at https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/. And, relatedly, figuring out where and how the content from those annexes is getting carried over into 3.0.  :)  So I'm going to mark this as still pending for the 3.0 milestone.

**Comment by goneall** [comment]
Closing this issue since the majority of the work has been completed.

We can open a separate issue to document the license expression syntax somewhere.
