### ISSUE TITLE
Licensing: Fill in License class property definition descriptions

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#209]
Now that the format has been provided for the Properties files, and the [skeleton MarkDown files have been added](https://github.com/spdx/spdx-3-model/pull/179) for the properties in the License class, the properties' descriptions need to be defined. I'll take the first shot at this.

**Comment by goneall** [comment]
Thanks @swinslow

**Comment by swinslow** [comment]
Completed in #225
