### ISSUE TITLE
Licensing: Modeling minCount:0 boolean fields

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#211]
Some fields that we are thinking of as "booleans" actually have three states: true, false, and not specified (i.e., `minCount: 0`).

For example, for the `License` class, the `isFsfLibre` property is meant to specify whether a license is considered free by the FSF. According to the current description of the field at https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md (section F), this field has the following properties where used on [the License List](https://spdx.org/licenses):
* `Y` if the license is listed as free by the FSF
* `N` if the license is listed as _not free_ by the FSF
* blank otherwise

This aligns with the modeling of `isFsfLibre` being a boolean, but with `minCount: 0, maxCount: 1` in the `License` class.

My question is just, are there any concerns that users of fields like this will misunderstand it as being just a standard boolean "true / false only" field on the class? Or are we comfortable that users will properly implement the trinary "yes / no / not present" options since it can be `minCount: 0`?

**Comment by goneall** [comment]
This is similar to the None and NoAssertion issues.  Perhaps we could create one solution for both?

@maxhbr - I recall you had some ideas on this.

**Comment by maxhbr** [comment]
This is similar but distinct, since it would result in 4 values
* None
* NoAssertion
* True
* False

> My question is just, are there any concerns that users of fields like this will misunderstand it as being just a standard boolean "true / false only" field on the class? 

I would assume that it does not cause a misunderstanding. Maybe the description could clarify that.

**Comment by goneall** [comment]
We could also "wrap" a boolean value in a type that would support None and NoAssertion as well as the underlying value, similar to the [Java Optional type](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html).

**Comment by maxhbr** [comment]
yes, but `None` is not valid here. Otherwise you end up with 4 options.

**Comment by swinslow** [comment]
Leaving open for 3.0, as this relates to the broader questions around handling of `NONE` / `NOASSERTION`.

**Comment by swinslow** [comment]
Given that there have been no further comments on this, I think the existing situation as released in -rc2 presumably works.

Properties like `isFsfLibre` permit, _but do not require_, a boolean value to be specified. So users can either specify `true` or `false`, or can just omit it if they don't want to specify either.

In light of that, I am comfortable with closing this for 3.0. If there's a pressing need down the road to revisit this, we can reconsider then.
