### ISSUE TITLE
Adding DateTime class in core

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-3-model#215]
I propose we add a class named `DateTime` or `Timestamp` to Core and change all properties that currently have range  `xsd:dateTime` to have this new class as range.

The new class will be a subclass of `xsd:string` (like `SemVer`, for example), but will also have a shape constraint that the format is `yyyymmddThhmmssZ`.

This will allow us to keep the same format as used in SPDXv2.

If we don't do this:

- we either have to add the format shape restriction to every property (and there are a number of them in the different profiles)
- or we don't restrict the format, which forces all implementations to have a full parser for all variants of ISO-8601 that are allowed by `xsd:dateTime`.

If there is agreement, I can submit the PR to implement this.

**Comment by armintaenzertng** [comment]
I agree with the general sentiment.
But the format in SPDX2 was `YYYY-MM-DDThh:mm:ssZ`, see for example [here](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#69-created-field).

**Comment by zvr** [comment]
Yes, @armintaenzertng , of course.
In my defense, I typed it from memory on a train in Sweden... 😉

**Comment by goneall** [comment]
@zvr - definitely agree :)
