### ISSUE TITLE
ConfidentialityLevel `Clear` missing?

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#220]
[ConfidentialityLevelType.md](https://github.com/spdx/spdx-3-model/blob/main/model/Dataset/Vocabulary/ConfidentialityLevelType.md) currently only defines three levels, while the linked Wikipedia entry also lists a fourth, namely `Clear`. Should this be added or is this omitted on purpose (in that case we might want to add a sentence stating why it is not used)?

**Comment by kestewart** [comment]
@armintaenzertng - have added clear to the set in https://github.com/spdx/spdx-3-model/pull/246,  please review, and if that satisfies, close this.

**Comment by kestewart** [comment]
Resolved by https://github.com/spdx/spdx-3-model/pull/246
