### ISSUE TITLE
Licensing: Format of templating for licenseText

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#221]
The [`licenseText` property](https://github.com/spdx/spdx-3-model/blob/licensing-profile/model/Licensing/Properties/licenseText.md) (description forthcoming) exists on the `License` class. This means that it can be used for either a `ListedLicense` (i.e., a license on the [SPDX License List](https://spdx.org/licenses)) or a `CustomLicense` (i.e., a user-defined `LicenseRef-` license).

A few questions for consideration:

1. Should `licenseText` permit templating?
2. If so, should it be the [license-list-XML repo's](https://github.com/spdx/license-list-XML) [XML license templating format](https://github.com/spdx/license-list-XML/blob/main/DOCS/xml-fields.md), or the original [SPDX legacy text template format](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b153-legacy-text-template-format)?
3. And, should templating be available only for `ListedLicenses`, or also for `CustomLicenses`?

My personal opinion on these (but I'd like to hear others' thoughts):

1. Yes
2. The XML license templating format (especially since the text template format is designated as "legacy", and the canonical definitions for the ListedLicenses is presumably the XML format)
3. Should be available for both (especially since it is defined for the `License` abstract class)

**Comment by swinslow** [comment]
One additional note:

If the XML templating format is used, then the `licenseText` property would be only the portion of the license-list-XML's license source files that appears between the `<text>...</text>` tags. Other variables are used for the remainder of the license metadata.

**Comment by goneall** [comment]
> Should licenseText permit templating?

I believe (strongly) this should be a separate property.  In the listed license RDF and JSON formats, there is a separate property [`standardLicenseTemplate` property](https://spdx.org/rdf/terms/#d4e1850) which follows the documented template format.  Several use cases just want to display the text and the templating would make those use cases difficult to implement.

> If so, should it be the [license-list-XML repo's](https://github.com/spdx/license-list-XML) [XML license templating format](https://github.com/spdx/license-list-XML/blob/main/DOCS/xml-fields.md), or the original [SPDX legacy text template format](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b153-legacy-text-template-format)?

@swinslow  - have we accepted and documented the XML format as a standard?  If so, I would agree we should use the XML format.  If not, then we should use legacy.  Once that is agreed to, I would recommend a separate property with a different name and deprecated the original format.

> And, should templating be available only for ListedLicenses, or also for CustomLicenses?

Yes - but only as a separate property name.

**Comment by swinslow** [comment]
Thank you @goneall! You've convinced me that a separate property is appropriate for this, and that `licenseText` should just be text.

In honesty, I don't believe we can say that we have documented the XML format used by the license-list-XML repo as a standard. So for the time being, yes, let's use legacy and then when the XML format is fully documented, we can add a separate property as you suggested.

**Comment by goneall** [comment]
In the [SPDX 2.X model](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/model/SPDX-UML-Class-Diagram.jpg) `standardLicenseTemplate` is the property name used for this purpose.

**Comment by swinslow** [comment]
Thanks @goneall! standardLicenseTemplate was added for 3.0-rc, to mean the legacy text template format.

I'm leaving this open for 3.0, so we can consider whether to document and add the XML templating format as well. I suspect that will be too heavy of a lift for 3.0, but will keep open for the time being.

**Comment by goneall** [comment]
Issue #359 tracks adding a filed for XML to the listed license.  Closing this issue - we can track the update in the new issue.
