### ISSUE TITLE
Rename LicenseExpression to AnyLicenseInfo

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#222]
AnyLicenseInfo is used in the [SPDX 2.3 UML class diagram](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/model/SPDX-UML-Class-Diagram.jpg).  It is also currently used in some of the tooling.

This is an abstract class, so it doesn't impact the serializations.

**Comment by goneall** [comment]
I would suggest we reserve the class name `LicenseExpression` to represent a class which structures the expression string syntax itself and use `AnyLicenseInfo` to represent any type of license.

**Comment by swinslow** [comment]
Hi @goneall, I'm making this change to minimize compatibility problems for tooling migrating from 2.x. Will submit a PR shortly.

**Comment by swinslow** [comment]
Fixed in #222
