### ISSUE TITLE
CustomLicense has a different name and structure relative to SPDX 2.3

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#223]
Compared to the [SPDX 2.3 UML class diagram](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/model/SPDX-UML-Class-Diagram.jpg), the SPDX 2.3 `ExtractedLicenseText` is named `CustomLicense`.  There is also an additional abstract class in SPDX 2.3 `SimpleLicensingInfo` which is a superclass of both `License` and `ExtractedLicenseText`.

Since the class is concrete, the name change will impact serializations.  We should either change the name back or write up some reasoning for the change.

The abstract classes have less of an impact.  I personally like the proposed 3.0 structure, but it will create some incompatibilities in some of the current libraries.

**Comment by swinslow** [comment]
Thanks @goneall. For this one, I'm inclined to keep it as CustomLicense. I think that the context change from the historical ExtractedLicenseText name is sufficiently different that CustomLicense is an appropriate name here.

Hopefully this also won't cause compatibility problems for tooling such as with the LicenseExpression vs. AnyLicenseInfo item in #222.
