### ISSUE TITLE
Property names: Singular vs Plural

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#226]
I'm not sure if this was discussed but I can't remember a decision:
Do we want to keep property names consistently to singular?

Some currently plural property names: [externalIdentifiers.md](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/externalIdentifiers.md), [externalReferences.md](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/externalReferences.md), [imports.md](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/imports.md), various [properties in the Dataset profile](https://github.com/spdx/spdx-3-model/tree/main/model/Dataset/Properties).

Possible problem: [namespace.md](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/namespace.md) vs [namespaces.md](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/namespaces.md). Maybe find a better word for the latter?

**Comment by goneall** [comment]
It was discussed and decided on singular in the April 4th tech meeting - see the serialization updates in the [notes](https://github.com/spdx/meetings/blob/main/tech/2023-04-04.md#notes).

**Comment by kestewart** [comment]
All tagged references are merged.   Closing.

**Comment by bact** [comment]
> It was discussed and decided on singular in the April 4th tech meeting - see the serialization updates in the [notes](https://github.com/spdx/meetings/blob/main/tech/2023-04-04.md#notes).

Update the tech meeting link: https://github.com/spdx/meetings/blob/main/tech/2023/2023-04-04.md
