### ISSUE TITLE
Dataset profile: Cardinalities

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#227]
The current [dataset profile](https://github.com/spdx/spdx-3-model/blob/main/model/Dataset/Classes/Dataset.md) seems inconsistent in its use of cardinalities.

`anonymizationMethodUsed` is the only property with no `maxCount`. @maxhbr thinks this is a good idea to allow for multiple methods listed here. Most of the properties are free form text, so in principal you don't need multiple entries. In examples like this, though, it might be better to split different methods into different entries of this property.

On the other hand, for example `knownBiases` and `dataPreprocessingSteps` both have `maxCount = 1`, even if their property names are plural (see also #226 for the question whether they should be converted to singular), but I'm not sure that they constitute different cases to the above concerning their cardinality.

I already opened PR #219 to fix cardinalities for properties where having more than one value does not make sense.

**Comment by armintaenzertng** [comment]
This basically also applies to the AI profile. I'm not sure if all cardinalities there are set as intended.

**Comment by kestewart** [comment]
@rgopikrishnan91 - can you please review/comment.

**Comment by maxhbr** [comment]
I think https://github.com/spdx/spdx-3-model/pull/230 is closed, and that should fix this ticket, right?

**Comment by rgopikrishnan91** [comment]
@maxhbr I think we can convert these properties to have singular names, however, I think @goneall suggestion of removing the maxcount should be used here. Also, in AI profile, modelExplainability and modelDataPreprocessing both having maxcount removed might also be a good idea (should I reopen[ #230](https://github.com/spdx/spdx-3-model/pull/230))?

**Comment by rgopikrishnan91** [comment]
@maxhbr I think we can convert these properties to have singular names, however, I think @goneall suggestion of removing the maxcount should be used here. Also, in AI profile, modelExplainability and modelDataPreprocessing both having maxcount removed might also be a good idea (should I reopen[ #230](https://github.com/spdx/spdx-3-model/pull/230))?

**Comment by maxhbr** [comment]
No, do not reopen this PR. Instead you can propose new changes in a new PR.

**Comment by kestewart** [comment]
Updated cardinalities merged for Dataset and AI.  Closing this.
