### ISSUE TITLE
How to express relationship completeness on the left side, which was possible in 2.3 by using the inverse relationship type

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-3-model#228]
The example files for [SPDX2.3](https://github.com/spdx/spdx-spec/blob/844144b3785dbc6a35065eda3b9d36adda874540/examples/SPDXJSONExample-v2.3.spdx.json#L273-L275) contain the following relationship:
`SPDXRef-CommonsLangSrc GENERATED_FROM NOASSERTION`
The question is: How to migrate this to SPDX 3.0? 

From the current discussion and migration guide this relationship would be swapped to a `GENERATES` relationship and the `NOASSERTION` would imply the completeness to be set to `noAssertion`. The problem then is that there is no `from` Element for this swapped relationship only a `to`.

**Comment by goneall** [comment]
Related to issue #129 

We could change the cardinality of `from` to `0..*`.

**Comment by kestewart** [comment]
In discussion with William,  from can't be 0..*,   due to many:many implications.   So we need to determine an alternate way of signaling this with completeness indiscators.

**Comment by goneall** [comment]
@kestewart agreed to take this on as part of the relationship cleanup

**Comment by goneall** [comment]
@kestewart - checking in on if this is handled with the relationship decisions
