### ISSUE TITLE
Adding more types to ExternalReference

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-3-model#251]
Whilst working to improve the SPDX SBOM generation in [ORT](https://github.com/oss-review-toolkit/ort) we had a discussion why we generate multiple packages in SPDX versus a single one in our CycloneDX. The reason was that in SPDX 2.3 to encode in SPDX that a Java package has a binary artifact, sources artifact and source code repository requires 3 SPDX package and several relationship such as GENERATES and DISTRIBUTION_ARTIFACT. This needlessly bloats the SPDX file if you just want to exchange information about include JAR but also want to convey additional information the SBOM tool collected.

Currently the ExternalReferenceType in 3.0 model is defined as

- altDownloadLocation: A reference to an alternative download location.
- altWebPage: A reference to an alternative web page.
- other: Used when the type doesn't match any of the other options.
- securityAdvisory: A reference to the published security advisory (where advisory as defined per ISO 29147:2018). It may contain an impact statement whether a package (e.g. a product) is or is not affected by vulnerabilities.
- securityFix: A reference to the source code with a fix for the vulnerability (e.g., a GitHub commit).
- securityOther: Used when the reference is security related but doesn't match any of the other types.

Proposal is to extend ExternalReferenceType with the below types.
Doing so will enable:
1.  SPDX creators or tools to easily include more data they know about an element (without having to any clean-up).  This data can then be amended by other tools.
2.  better back and forward conversion with CycloneDX

-  **api-advisories**: A reference to API service where up-to-date security advisory statements related to artifacts can be retrieved
-  **api-vex**: A reference to API service where up-to-date VEX statements related to artifacts can be retrieved
-  **bom**: A reference to the bill of materials information related to an artifact / / Use case Eclipse foundation publishing SPDX SBOMs for all their projects in a central location
-  **binary-artifact**:  A reference to binary artifacts related to a package
-  **build-meta**: A reference build metadata related to a published package
-  **build-system**: A reference build system used to create or publish the package
-  **source-artifact**:  A reference to an artifact containing the source for a package
-  **chat**: A reference to the instant messaging system used by the maintainer for a package
-  **documentation**: A reference to the documentation for a package
-  **funding**: A reference to funding informaton related to a package
-  **issue-tracker**: A reference to the issue tracker for a package
-  **mailing-list**:  A reference to the mailing list used by the maintainer for a package
-  **metrics**:  A reference to metrics related to package such as OpenSSF scorecards.
-  **license**: A reference to additional license information related to an artifact
-  **release-notes**: A reference to the release notes for a package
-  **release-history**: A reference to published list of releases for a package
-  **social-media**: A reference to social media chanel for a package or vulnerability
-  **source-artifact**:  A reference to an artifact containing the source for a package
-  **support**:  A reference to support channel for a package or vulnerability
-  **vcs** :  A reference to version control system related to an artifact

**Comment by maxhbr** [comment]
I think they are good, although they might create some confusion.

I am also afraid, that entries like `license == https://opensource.org/license/mit/` might be very weak references, and are more like additional URLs. But maybe I imply to much into the semantics of ExternalReferences

**Comment by kestewart** [comment]
Some concerns that we have represented this with other external reference fields today in SPDX.

**Comment by puerco** [comment]
I mentioned this in the meeting but I'll do it again here, `api-vex` is simply not a thing. VEX data can be made available via a number of ways, not just an API: from a well-known URL, a bucket or an OCI registry.

**Comment by tsteenbe** [comment]
@puerco I picked `api` in this issue as I trying to indicate that this is machine-readable endpoint. Any suggestions for a better name - originally I used bom, bom-advisories, bom-vex, etc.

**Comment by tsteenbe** [comment]
> I am also afraid, that entries like license == https://opensource.org/license/mit/ might be very weak references, and are more like additional URLs.

My intent with most of these above references was to provide a mechanism to SPDX creator to store the unprocessed package metadata so other people or tools can improve this data or use this raw data to compute on top of SBOMs.  Have been looking at too many SBOMs from various tools and what I see is that data they have is omitted and when asked the cost of converting to required format is not feasible to implementer due to lack funding, resources, etc. This got me asking what is better A) no data or B) suboptimal data for which I say B).

**Comment by kestewart** [comment]
Closing this as the security profile is now merged into Main.   Please open a new issue, if there is additional items to work on.
