### ISSUE TITLE
Glossary should be in alphabetic order and have standalone definitions

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-3-model#253]
In its current form, definitions depend on previous ones.

**Comment by kestewart** [comment]
Definitions should be reworked to be standalone.    Have tagged this to be completed as part of 3.0 release

**Comment by puneeth072003** [comment]
@kestewart @goneall I'd be more than happy to work on this issue

**Comment by goneall** [comment]
Resolved with PR #680
