### ISSUE TITLE
Licensing fields as Relationships rather than Properties

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#254]
On the tech team call 2023-05-02, it was agreed that _at least for release candidate 1_, the declaredLicense and concludedLicense fields should be Relationships rather than Properties of the applicable software artifacts.

The reason for this change is because software artifacts (defined in Core / Software) may be modeled separately once, but multiple tools or individuals may subsequently specify their own determination of the declared / concluded license for those software artifacts. If the license fields are properties, then they can only be specified _at the same time_ that the software artifacts are declared. If they are instead relationships, then they can be specified separately by various tools / individuals and linked via relationship to the commonly-declared software artifacts.

I believe there are two key open issues for making this work:
1. How would constraints work?
  * If "satisfying" the licensing profile requires that every software artifact within a particular scope have a `concludedLicense`, this is easy to check if this is a property: either the property is there, or it is not.
  * It is not immediately clear how this would be validated via relationships, or what that would necessarily even mean. If anyone can create a relationship linking to a pre-existing declaration of a software artifact, then which relationships would we look at to determine whether the constraint is satisfied?
2. Separately, if declaredLicense and concludedLicense would be Relationships, then it seems as though copyrightText and attributionText should be as well. I assume those would be treated equivalently, and therefore would need to be standalone "Elements" with SPDX IDs corresponding to those strings.

I believe @zvr is putting together a proposed PR to implement the "Relationship" structure, but I am not sure about the outcome of the two points noted above. As a result, after RC1 this may revert back to needing to be Properties if Relationships are not workable.

cc @jlovejoy @kestewart @maxhbr for visibility -- please feel free to jump in if I've mis-stated anything!

**Comment by kestewart** [comment]
Initial attempts had issues.  Moving this to be sorted for 3.0.

**Comment by zvr** [comment]
@tsteenbe by "Licensing fields as Relationships rather than Properties", the idea was that the model would be more like:

```
 Relationship
    RelatiopnshipType: CONCLUDED_LICENSE
    from: urn:myns:myWonderfulPakcage
    to: http://spdx.org/licenses/MIT
```

**Comment by tsteenbe** [comment]
@zvr  Was aware of that approach but  think my proposal is simpler and attempts consistency across profiles.

**Comment by tsteenbe** [comment]
Commercial licensing use cases see also https://github.com/spdx/spdx-3-model/issues/397 also in my opinion to have a more elaborate  relationship type. Using a `to: http://spdx.org/licenses/MIT` works great for a single standard open source license but what if an SPDX creator wants to communicate that multiple packages within the same SBOM are under one commercial license say LicenseRef-proprietary-ACME-Corp but with different renewal/expiration dates?
