### ISSUE TITLE
Collition between terms defined in SPDX 2.x and SPDX 3 on https://spdx.org/rdf/terms/?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#283]
Hey, we are currently hosting the RDF Terms for 2.3 on https://spdx.org/rdf/terms/, without a version in the URL. This also is reflected in the IRIs of the classes, e.g. http://spdx.org/rdf/terms#Annotation for annotation.

Does that cause any issues, if we replace this page with completely different SPDX 3 stuff? Do we break SPDX 2.x if we replace it? How is versioning handled?

**Comment by zvr** [comment]
Please see https://github.com/spdx/spdx-3-model/blob/main/serialization/rdf.md for SPDXv3 IRIs.

**Comment by zvr** [comment]
License IRIs remain the same (not part of RDF).

**Comment by maxhbr** [comment]
Thanks
