### ISSUE TITLE
governance docs should not be duplicated

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-3-model#287]
It looks like we have duplicated some of the governance docs in this repo. We should not have duplicates of such things, but link to the documents in their original form in the governance repo

**Comment by kestewart** [comment]
@zvr - can you put in a PR to remove them?  I'm guessing this is part of what you set up at the start.

**Comment by zvr** [comment]
@jlovejoy I originally put it here because the License references "the accompanying Governance.md file".
