### ISSUE TITLE
If license information is optional, we do not need NoAssertion in the model

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#289]
If DeclaredLicense is optional, we might not need the concept of `NoAssertion` in the model. If we want to give the possibility to explicitly state that there is `NoAssertion` somewhere, we might be able to just allow that in serialization.

> do we need `noAssertion` if that field is optional?
> 
> This can be:
> - `null`
> - `None`
> - `NoAssertion`
> - `MIT` or ...

_Originally posted by @maxhbr in https://github.com/spdx/spdx-3-model/pull/286#discussion_r1186309221_

**Comment by swinslow** [comment]
-1 -- we should retain NOASSERTION as an explicit option, which is separate from the absence of the field. See my comment just now in https://github.com/spdx/spdx-3-model/pull/286#discussion_r1186324846

**Comment by maxhbr** [comment]
if `null` means the same as `NOASSERTION`, we either should make that field mandatory to get rid of `null` or we get rid of `NOASSERTION`.

**Comment by maxhbr** [comment]
This was just again brought up be me in the Tech team call today.

Here is some background from the v2.3 spec https://spdx.github.io/spdx-spec/v2.3/package-information/#713-concluded-license-field :

> If the Concluded License field is not present in a package, it implies an equivalent meaning to NOASSERTION.

So, my question can be summarized to: **if "not present" has an equivalent meaning to NOASSERTION, why do we need to be able to encode this equivalent information in two distinct different ways in the model?**

@kestewart : you stated that NOASSERTION does not have the same meaning as "not present information", can you elaborate on that?

**Comment by zvr** [comment]
@maxhbr I'm not sure exactly what you are proposing.... that license information should not be optional but mandatory? or that we don't use NoAssertion?

**Comment by maxhbr** [comment]
my proposal would be to drop noassertion from the model, since a no-present value is equal to noassertion. If one then explicitly states `NOASSERTION` would just be a serialization and not a model question and would still be possible.

as @swinslow stated in his comment (https://github.com/spdx/spdx-3-model/pull/286#discussion_r1186324846):
> So I would still suggest allowing either serialization outcome. Either it is present as NOASSERTION, or it is absent and a consumer would interpret that silence as being semantically equivalent to NOASSERTION (if they care about it at all).

Since they are semantically equivalent, they should not have distinct encodings in the model.

##

But, since the discussion started to also support `MIT AND NOASSERTION` in expressions, that might no longer be an option. Not sure if we want to go that way.

**Comment by maxhbr** [comment]
ok, so it is not "semantically equivalent".  And after clarifying that in the spec we could close this issue.

**Comment by goneall** [comment]
> ok, so it is not "semantically equivalent". And after clarifying that in the spec we could close this issue.

@maxhbr - can you create a PR with the clarification?

**Comment by swinslow** [comment]
This was resolved in #456 - closing, thank you all!
