### ISSUE TITLE
Punch List from Aug 30 2022 tech call

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#29]
Below are the items raised in the August 30, 2022 tech call along with pointers to any previous discussions or decisions directly related to the item.

The table has the following columns:
- `Class` The model class the item relates to, or `Overview` if it is a general item pertaining to all classes
- `Item` The punch list item - text taken verbatim from the minutes as of 31 August 2022
- `Cat.` A Category indicating if this item has been previously discussed.  The category is one of:
  - `NPD` - Not previously discussed - no evidence was found in prior meetings of this item being discussed
  - `DD` - Discussed and decided - there are minutes or notes in a GitHub issue that this item was discussed and a decision made
  - `DND` - Discussed and not decided - There are minutes or issue notes where this was discussed, but no clear decision was recorded in the minutes
 - References - Links to GitHub issues or minutes relevant to the item

| Class | Item | Cat. | References | Status |
| ----- | ----- | ---- | ------------ | --- |
| Snippet | Snippet is line range and byte range. Yes. Punch: Document beginning & end of snippet in model. | DND | Issue #11 | Resolved, added line and byte ranges to model. Byte range takes precedence if in conflict. |
| Snippet | Discuss and determine if we should add a "data class" and relationship between data class, file and snippet. Ping Alexios. We may already have a relationtype suitable. Content of a file is one object, Metadata of a file is another object. | NPD | Although this was described as a previous suggestion on the call, I could not find mention in prior meeting minutes | Not a blocker for 3.0, Sebastian and Jeff are working on related proposals. |
| Snippet | clarify location cardinality in model | DND | Issue #11 | Resolved. Keeping single location for 3.0, content proposal may amend. |
| File | Clarify definition of Package and File and how they relate to each other (including if download location makes sense for a file) | NPD | Lots of discussions on package download location, but no evidence of file download location being discussed | Resolved. These are properties on Package but available via ExternalReferences for other artifacts. |
| Package | Revisit cardinality of Download location. 0..* | DD | Decision documented in [2021-10-05.md](https://github.com/spdx/meetings/blob/main/tech/2021-10-05.md) | Resolved. Primary attached to Package, additional can be added with ExternalReferences. |
| Package | Revisit cardinality of Home Page (depends on purpose - ie. marketing, developer) | DND | Cardinality not specifically addressed, but discussed on issue #13, [2022-03-01.md](https://github.com/spdx/meetings/blob/main/tech/2022-03-01.md), [2021-12-07.md](https://github.com/spdx/meetings/blob/main/tech/2021-12-07.md), [2020-10-13.md](https://github.com/spdx/meetings/blob/main/tech/2020-10-13.md) | Resolved. Primary attached to Package, additional can be added with ExternalReferences. |
| Package | Clause 7 fields reviewed for coverage. Some should 2.3 become elements? or more fields in the Package class? | DND | Several discussions on individual fields found, but not as an entire group | Open issue. |
| Package | Should Package URL be a property on package? | DND | Discussed on [2021-11-09.md](https://github.com/spdx/meetings/blob/main/tech/2021-11-09.md) - line 74 looks like a decision | Resolved. Added as a property on Package. |
| Artifact | Should Artifact URI be moved back into Artifact class. (one form of an external identifier) | DD? | [2020-10-13.md](https://github.com/spdx/meetings/blob/main/tech/2020-10-13.md),[2020-09-14.md](https://github.com/spdx/meetings/blob/main/tech/2020-09-14.md),[2020-10-13.md](https://github.com/spdx/meetings/blob/main/tech/2020-10-13.md)  - decision to make property? [2020-11-09.md](https://github.com/spdx/meetings/blob/main/tech/2020-11-09.md) | Resolved. Decided not to add this since no universal URI for all artifact types. Added content identifiers to File and Snippet to resolve one of the needs for this. |
| Artifact | Should location be added to Artifact or at the Package/File/Snippet level? | DND | [2022-08-16.md](https://github.com/spdx/meetings/blob/main/tech/2022-08-16.md) | Resolved. Did not add property but available via ExternalReferences. |
| Element | Should external locator and external identifier be called out in Element? | DND | [2022-08-16.md](https://github.com/spdx/meetings/blob/main/tech/2022-08-16.md) | Resolved. ExternalIdentifiers on element meets this need. |
| Element | External Identifiers need to be better defined | DND | Note that we've have several discussions on external identifiers - to many to list here | Pending. Need to document in spec text but concept is defined (identifier from an external system that uniquely identifies the subject of the element). |
| Element | Gain consensus and clarity on type of extension element. (clarify - Map<IRI, any> Structure or dictionary map? | DND | Discussed in [2022-03-22.md](https://github.com/spdx/meetings/blob/main/tech/2022-03-22.md) and marked as closed but specific type was not documented.  Also discussed in [2021-12-07.md](https://github.com/spdx/meetings/blob/main/tech/2021-12-07.md), [2021-04-20.md](https://github.com/spdx/meetings/blob/main/tech/2021-04-20.md), [2021-03-02.md](https://github.com/spdx/meetings/blob/main/tech/2021-03-02.md), and [2021-02-23.md](https://github.com/spdx/meetings/blob/main/tech/2021-02-23.md) | Pending. There are still some active concerns about the existence of this concept. |
| Element | Assess if data model proposal (Alexios) works with VerifiedUsing (example SPDX document element) | See above | Data model proposal under snippet |
| Element | Clarify if VerifiedUsing refers to integrity of the 'thing' described by an Element, or the integrity of the Element data itself (its canonical representation)? Capture and enable both with separate "targetVerifiedUsing" and "elementVerifiedUsing properties? targetVerifiedUsing would go in Artifact, not Element. | DND | Partial decision in [2021-11-09.md](https://github.com/spdx/meetings/blob/main/tech/2021-11-09.md), does not look like it was discussed in [2021-11-16.md](https://github.com/spdx/meetings/blob/main/tech/2021-11-16.md) | Resolved. verifiedUsing is how to verify the subject of the element. Non-blocking for 3.0: Canonicalization WG to propose what is needed for canonicalization. |
| Element | On ExternalReference and ExternalIdentifier indended to be abstract and if so, how does it work | NPD | | Resolved. Not abstract. |
| Element | Provide a complete list of annotation types. | DD | Decision documented in [2022-03-29.md](https://github.com/spdx/meetings/blob/main/tech/2022-03-29.md) | Resolved. List updated. |
| Enumerations | Need to be made complete with values pulling forward from 2.3 | ? | more of an action than a decision | Resolved? Please verify. |
| Enumerations | Should they be closed, or allow folks to add things. (Folks can always add other things to their software, but can those things claim to be SPDX-conforming?) | NPD | Could only find one discussion on enumerations for profiles | Resolved. They are closed but software wanting to maintain forward compatibility should expect new values. |
| Actor | should Actor have it's own identifier property? See ArtifactURI. | DD? | Line 70 in [2022-04-05.md](https://github.com/spdx/meetings/blob/main/tech/2022-04-05.md) appears to be a decision | Pending. Ongoing discussion about identities. |
| Relationship | what are the use-cases for relationship cardinalities (from+to) and directions | DD? | Discussed in issue #5 | Documentation? |
| Relationship | Revisit cardinality of relationshipCompleteness. (In context of serialization. ) Default, optional are conflicting. | NPD | I couldn't find this specific discussion | Resolved. Logically it must be present, but there is a common default value for serializations and they are recommended to make it optional. |
| Relationship | Articulate all the Enumerated relationship types for 3.0 | ?? | More of an action than a decision | Resolved? Please verify. |
| Checksum | Enumeration: Consider adding "OTHER" | NPD | | Resolved. Added. |
| Overview | Create an spreadsheet Review 2.3 and 3.0 | ?? | More of an action than a decision | Pending. |
| Overview | Do we want to restrict Enumerations or allow extensions? Historical we've kept it restricted for Consumer benefit. | NPD | Same as enumerations issue listed above | Resolved. Duplicate. |
| Overview | Should Profiles or closed, or enable extending definitions. | DD | Discussed and decided in [2021-03-30.md](https://github.com/spdx/meetings/blob/main/tech/2021-03-30.md), [2021-04-06.md](https://github.com/spdx/meetings/blob/main/tech/2021-04-06.md), [2021-04-20.md](https://github.com/spdx/meetings/blob/main/tech/2021-04-20.md), [2021-04-27.md](https://github.com/spdx/meetings/blob/main/tech/), [](https://github.com/spdx/meetings/blob/main/tech/2021-04-27.md) | Resolved. |
| Overview | Anything in 2.3 we need to justify why we deprecate. Already depricated, we don't need to revisit. | ?? | More of an action | Pending. |
| Overview | How do we handle optional fields with default values in model? Should optionality be part of data model, not in information model? Can you answer the question is this complete at logical model level? Do we want to have consistent approach across all fields. When not present stating default value, etc. | NPD | similar to other punch list items above | Resolved. Duplicate. |

**Comment by iamwillbar** [comment]
Move comment from Element to CreationInformation?

**Comment by kestewart** [comment]
@iamwillbar - am closing this issue as all open elements are covered by other issues at this point.   Please reopen if you disagree.
