### ISSUE TITLE
Proposal: Add generated documentationn as gh-pages

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-3-model#320]
I used [Ontospy](https://github.com/lambdamusic/Ontospy) and the [spec-parser](https://github.com/spdx/spec-parser) to generate a html documentation of the current release-candidate. Currently it is deployed on my own fork and available as a 
- multi-page document: https://meretp.github.io/spdx-3-model/
- or a one-page document: https://meretp.github.io/spdx-3-model/one_pager/

Should this be added to the main repo? If someone could create a `gh-pages` branch for this, I can open a PR against the branch and provide these two generated documentations (- suggestions for better directory names than "one_pager" very welcome).
For now I can only provide these already generated docs but I am also working on a GitHub Action workflow to automatically generate the documentation and update the gh-pages branches when a PR is merged.

**Comment by zvr** [comment]
Thanks for this work, @meretp .

Tagging @iamwillbar who was also working on the "generating" front to see whether these pages are OK for our use.

**Comment by goneall** [comment]
If it will be more than a week or two to get the web page generator from @iamwillbar - I think it would be very beneficial to have these pages in the interim.

With the activity here at OSSSumit, we're going to get a lot more eyes on our repo :)

**Comment by goneall** [comment]
@meretp I added a `gh-pages` branch - please go ahead and create a PR.

Thanks!

**Comment by goneall** [comment]
I believe this can now be closed.  We are starting up a separate email thread to make the official GH markdown files published.

tech call 11 July 2023
