### ISSUE TITLE
Are there plans for a machine readable schema?

### ISSUE THREAD

**Issue by mlieberman85** [spdx/spdx-3-model#321]
I see there's a json schema for v2.2 and v2.3, but I don't see one for the RC for v3.0. Are there plans to have a machine readable schema?

**Comment by goneall** [comment]
> Are there plans to have a machine readable schema?

Yes - we plan on generating the schema from the markdown files.

Now that we have RC1 out for review, we will be focusing more on the serialization specifications.

**Comment by mlieberman85** [comment]
Thanks. Related, how is this supposed to be currently read even from a human standpoint? I see a ton of small .mds but no indication of how someone should read it to understand the model?

**Comment by goneall** [comment]
We added some text in the contributing.md file for the review, but it probably isn't sufficient.

There a proposal from @meretp - https://github.com/spdx/spdx-3-model/issues/320 - to add some generated docs.

We'll probably have those generated in the next day or two which should be much more readable.

**Comment by mlieberman85** [comment]
Thanks!

**Comment by goneall** [comment]
Thanks to @meretp, we just added a more navigable view of the spec at https://spdx.github.io/spdx-3-model/ontospy/
Note that this isn't the final format we plan to generate, but it is easier than navigating the individual .md files.
We still need to update some of the README and CONTRIBUTING files to point to these files, so I'll leave this to track the remaining actions.

**Comment by willarmiros** [comment]
Hi @goneall - thanks for publishing the navigable view, it's super intuitive to navigate! Is it possible to get the raw ontology RDF either committed to the repo or available for download somewhere, similar to https://github.com/spdx/spdx-spec/blob/development/v2.3/ontology/spdx-ontology.owl.xml?

Context: I would like to programmatically generate SPDX v3-compliant JSON BoMs, so having something like an RDF schema (or JSON would be even better, I just figure you may have an RDF more easily on hand) would be very helpful to play around with generating some v3 examples!

**Comment by goneall** [comment]
Ping @zvr  on the above question.

I see we are generating the ontology in .ttl format in the Action script, but I can't find where it is uploaded.

**Comment by zvr** [comment]
The generated ontology is being generated in every run.
In its current state it's incomplete, so it does not get uploaded in the generated branch; but it is being stored as an artifact, by using the `upload-artifact` action.

To see them, go to the `Actions` tab, filter by `run spec-parser` action on the left, and click on a run (probably the most recent one). You'll see the generated artifacts in the results page.

Once the results are more acceptable, they will be uploaded as usual.

**Comment by goneall** [comment]
Thanks @zvr  

@mlieberman85 Once we have the spec-parser running, you'll be able to access the ontology.

Attached is the model output from the latest run - note that this is still a work in progress and should not be relied on for accuracy, but it could give you a better idea what the final format will look like.

Please let us know any feedback.
[model.ttl.zip](https://github.com/spdx/spdx-3-model/files/11592756/model.ttl.zip)

**Comment by mlieberman85** [comment]
Thanks! Yeah, it's less about what the actual finalized model will look like, but I want to understand what the output format might be, e.g. json schema, turtle, something else as it helps with some of the tooling we're writing to make implementation of SBOM generation, validation, verification, and ingestion easier.

**Comment by goneall** [comment]
@mlieberman85 There's also a JSON schema in the works.  Personally, I prefer the OWL/SHACL/RDF schemas since they offer a superset of descriptions and constraints relative to other schemas.

**Comment by willarmiros** [comment]
Thanks for posting the schema draft, I will try to use it and provide feedback this week, most likely at the AI/Dataset profile meeting since that is the feature of interest in v3 for my use case.

+1 to @mlieberman85's ask for the JSON schema, great to hear it's in the works! Will make things much easier for tooling on our end as well since it's primarily JSON-oriented.

**Comment by goneall** [comment]
Yes - we do now have plans to generate a schema - the serialization workgroup is taking this on

From tech call 11 July 2023
