### ISSUE TITLE
Licensing: License expression including `OrLaterOperator` and `WithAdditionOperator`

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-3-model#324]
In the Tooling Mini Summit one use case for the licensing profile was the following license expression "GPL-3.0-or-later WITH AdditionRef-autoconf-gpl3". 
This implies that we need to be able to use the `OrLaterOperator` as license in the `WithAdditionOperator`. The current model in the licensing profile doesn't allow this. 
One option would be to make the `OrLaterOperator` a subclass of `License` but as this would then allow some kind of "nested" `OrLaterOperator` which is not valid on the other hand, we probably need to rethink the structure here. 

This is also an issue in the open proposal for the rework as commented[ here](https://github.com/spdx/spdx-3-model/pull/297/files#r1190815132).

Edit:  According to the answer in the linked comment above the GPL-3.0-or-later license is a `ListedLicense` so the example above would be handled without the `OrLaterOperator`. I can't think of a better example but I think the issue should be clear.

**Comment by goneall** [comment]
This appears to have been resolved with the refactoring @armintaenzertng did.

@meretp @armintaenzertng - if you disagree, please reopen.
