### ISSUE TITLE
Singular property name problem with `namespace` and `namespaces`

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#328]
If we want to keep property names singular, we have to come up with a different name for either [namespace](https://github.com/spdx/spdx-3-model/blob/a79efb07977a152406badb9b530519fc4ab80834/model/Core/Classes/NamespaceMap.md?plain=1#L25) or [namespaces](https://github.com/spdx/spdx-3-model/blob/a79efb07977a152406badb9b530519fc4ab80834/model/Core/Classes/ElementCollection.md?plain=1#L27).

**Comment by goneall** [comment]
Suggest `namespaces` -> `namespaceMap` (note lower case `n` to distinguish it from the class by the same name)

**Comment by goneall** [comment]
Closing this issue as the namespaces are no longer in the model once #411 is merged

From tech call on 11 July 2023
