### ISSUE TITLE
`RelationshipType` obsolete for Security profile Relationships?

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#330]
The [model-security-profile.png](https://github.com/spdx/spdx-3-model/blob/main/model-security-profile.png) seems to indicate that the various subclasses of `Relationship` in the Security profile require a single specific `RelationshipType` each.
Is that a hard requirement? If so, this is basically obsoleting the need for this property as it adds no new information. In this case, could we add a `maxCount=0` or is this not possible because of the previously defined `minCount=1`?

The markdown files (for example [here](https://github.com/spdx/spdx-3-model/blob/main/model/Security/Classes/CvssV2VulnAssessmentRelationship.md)) currently do not state any constraints on the `RelationshipType`.

**Comment by puerco** [comment]
Ah interesting, we didn't know how to implement the constraints automation in the markdown so we resorted to listing it in English text, such as here:

https://github.com/spdx/spdx-3-model/blob/0b26b63a2238fb0c33f2dcc8a8940663e6ac1ed5/model/Security/Classes/VexUnderInvestigationVulnAssessmentRelationship.md?plain=1#L21-L24

**Comment by rnjudge** [comment]
@armintaenzertng Re:Adolfo's comment -- are there any changes we need to make in the security profile or can this be closed?

**Comment by armintaenzertng** [comment]
This has been handled in #338.
