### ISSUE TITLE
Security: Type of `score`

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#332]
There is currently a type mismatch in the markdown files:
The property [`score`](https://github.com/spdx/spdx-3-model/blob/main/model/Security/Properties/score.md) has "Range: xsd:string", while the classes [`CvssV2VulnAssessmentRelationship`](https://github.com/spdx/spdx-3-model/blob/main/model/Security/Classes/CvssV2VulnAssessmentRelationship.md) and [`CvssV3VulnAssessmentRelationship`](https://github.com/spdx/spdx-3-model/blob/main/model/Security/Classes/CvssV3VulnAssessmentRelationship.md) state "type: xsd:decimal".

In any case, it seems that only a single decimal place is allowed in the score value. This restriction does not seem to be stated anywhere so far and would be easier to enforce via regex as has been done [here](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/DateTime.md). As regex can only be applied to string values, `score` might be better off as a string?

**Comment by jeff-schutt** [comment]
SPDX Security Profile team discussed this in today's meeting and agrees with conforming to whichever pattern has been decided elsewhere in the model. We will await resolution of Issue #368 to make the appropriate changes here.

**Comment by davaya** [comment]
Leaving it as xsd:decimal with [fractionDigits](https://www.w3.org/TR/xmlschema11-2/#rf-fractionDigits) = 1 would preserve the semantics that score is a number while still restricting its precision.

**Comment by goneall** [comment]
@jeff-schutt - we resolved how we want to approach #368 - if you could create a pull request - thanks.
