### ISSUE TITLE
Licensing: Mandatory fields of `License` and `LicenseAddition`

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#335]
The [`License`](https://github.com/spdx/spdx-3-model/blob/main/model/Licensing/Classes/License.md) class currently defines `licenseName` and `licenseText` as mandatory. I get that this is necessary for custom licenses, but in the case of listed licenses this is not unnecessary as the information can be simply looked up in the official license list. Also, in SPDX2 this information was not included.

I propose making these properties optional in general and restrict them to `minCount=1` for custom licenses.

Same concerns apply to [`LicenseAddition`](https://github.com/spdx/spdx-3-model/blob/main/model/Licensing/Classes/LicenseAddition.md), i.e. the fields `additionName` and `additionText`.

**Comment by goneall** [comment]
I believe licenseName should not be mandatory - it wasn't required in SPDX 2.X even for custom licenses.  Only ID and text was required.

**Comment by goneall** [comment]
I think it is OK for the model to have licenseText required for listed licenses.

There will always be license text for both custom and listed licenses.  In the case of a listed license, the license text will be gathered from the publicly available information (either in the [license-list-data](https://github.com/spdx/license-list-data) repo or from the [web page](https://spdx.org/licenses/)).

Applications should expect the data to be available for the license text for the listed licenses - hence having it required should be fine.

**Comment by goneall** [comment]
> I thought the plan was to have each license/exception from the License List as a predefined "individual" of the Listed* class?

That would still work - since the type of the Individual would be a listed license, it would be OK for the text field to be required.

**Comment by goneall** [comment]
Discussed with Kate and we decided to leave this as the same as 2.3 - closing this issue.

@armintaenzertng if you feel strongly, feel free to re-open.
