### ISSUE TITLE
Cardinality of `attributionText`

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#336]
In SPDX2, `attributionText` [had cardinality 0..*](https://spdx.github.io/spdx-spec/v2.3/package-information/#723-package-attribution-text-field), while in SPDX3 [it has currently 0..1](https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/SoftwareArtifact.md).

Do we want to keep the current SPDX3 cardinality (In that case, how are multiple SPDX2 attribution texts converted into a single one?)
or do we change it to 0..*?

**Comment by goneall** [comment]
I would like to keep the cardinality the same as 2.X for compatibility reasons.

@swinslow - you OK with changing the cardinality back?

**Comment by goneall** [comment]
I'll create the PR

**Comment by swinslow** [comment]
I don't have a particular preference either way. I think using `0..1` to align with `copyrightText` might be cleaner, but I'm fine with reverting it for compatibility purposes if that's easier for the tool users.

@goneall apologies for the delayed response -- I'm fine with the change in #453 that you proceeded with.

**Comment by swinslow** [comment]
It looks like the failing test in #453 is something unrelated, so I think we can close this now as completed.
