### ISSUE TITLE
Update description of licenseId and additionId

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-3-model#339]
In ```model/Licensing/Properties/additionId.md``` and ```model/Licensing/Properties/licenseId.md``` we have:

```
It may only include letters, numbers, period (".") and hyphen ("-")
```

First proposed modification: replace ```numbers``` by ```digits```

Rationale: a number can contain a comma, which is not expected.

Second proposed modification: replace ```period``` by ```periods``` and ```hyphen``` by ```hyphens```

Rationale: we can have more than one period and more than one hyphen.

Third proposed modification: define what a letter is.

Rationale: it is not clear what a letter is, is it only letter from A to Z without diacritics, or are PèreNoël and λογισμικού valid identifiers?

**Comment by goneall** [comment]
All good updates - agree with the proposed changes.  For the letters, we should keep it to [A..Za..z] - ie: Ascii A-Z upper and lower case.

**Comment by zvr** [comment]
This should be closed.

It refers to properties no longer existing (and the description was limiting, anyway -- id's should be URIs).

**Comment by goneall** [comment]
Based on the tech call on 11 July 2023, we agreed to close this issue
