### ISSUE TITLE
drop `Payload --element--> Element`, since it is redundant?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#34]
Why is there a `element` relation between `Payload` and `Element`? Why is the `element` relation between `Collection` and `Element` not sufficient?

Further is this `element` relation a `n-to-m` relation and since everything derives from Payload there are arbitrary `element` relations between arbitrary Elements possible, which is even more flexible then the `Collection`, that feels wrong.

![20221030_09h55m16s_grim](https://user-images.githubusercontent.com/1187050/198870407-bdae13eb-6967-4008-b44b-7539af23d6bc.png)

**Comment by maxhbr** [comment]
this is related to #38

**Comment by iamwillbar** [comment]
Per the comment in #38 this is to support serializing either a single element or a collection of elements, the default implementation of "element" for Payload would be an empty list. Collection would override this.

**Comment by maxhbr** [comment]
discussion continued in #38
