### ISSUE TITLE
Package Verification Code

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#345]
In the current SPDX 3 model, we use the `verifiedUsing` property to verify Elements.  We have had past discussions that we would subclass `IntegrityMethod` to implement the [Package Verification Code](https://spdx.github.io/spdx-spec/v2.3/package-information/#79-package-verification-code-field) or replace it with some similar algorithm.  This has yet to be implemented.

In the tools implementer call on 17 May 2023 we discussed this and there was general consensus that the Package Verification Code as it is currently defined and used does not work.  This consensus was based on previous "DocFest's" where we compared calculated Package Verification Codes produced from different tools with the same target package - they all were different making the code less than useful.

We have a few options:
1. Don't provide a verification mechanism for Packages
2. Implement the Package Verification Code as discussed
3. Implement an alternative to the Package Verification Code which can be used in 3.0

With the deadline for SPDX 3 quickly approaching, option one may be the best as long as we don't have adoption issues due to this missing functionality.  Something we should check with the user community before implementing.  We can always adopt 2 or 3 in SPDX release 3.1 since the addition will not be a breaking change unless we make it required.

**Comment by goneall** [comment]
Here's a proposal for 3 above:

- Introduce 2 subclasses of IntegrityMethod for use by Package - one intended for the case where a Package is distributed in a single artifact `PackageArtifactVerification` (e.g. tarball or installation file) and one intended for the case when the Package is distributed as a set of source file `PackageSourceVerification` (e.g. similar to the `filesAnalyzed=true` in SPDX 2.X)
- In the case where the creator of an SBOM is defining the metadata for a package comprised of source file, they would use the `PackageSourceVerification`
- In the case where the creator of an SBOM is defining the metadata for a package distributed as a single file artifact it would use the `PackageArtifactVerification`
- If describing package metadata which does not have a distribution artifact and does not have source files, they would not include any `verifiedUsing` properties
- The `PackageSourceVerification` would include a single property `sourceFile` which would be a list of SPDX files.  To verify the package, the consumer would iterate over all the files and compare them to their copy of the source distribution.  This would allow verification without the algorithmic complexities of the Package Verification Code which has plagued the tools providers.
- The `PackageArtifactVerification` would include a single property `distributionFile` which would point to a single mandatory SPDX file.  This would provide a means for verifying binary distributions of packages.

If there is interest in this approach, I can create a draft pull request for review.

**Comment by goneall** [comment]
Once we close on this propose, we should update / close issue #85

**Comment by goneall** [comment]
Proposal to support the legacy PackageVerificationCode - but add in the other alternative verification methods proposed by @jeff-schutt - @goneall to create a pull request with a proposal.

**Comment by goneall** [comment]
@jeff-schutt - From the tech call on 19 Sept 2023, we decided to implement the alternative methods you described above but include the old verification code algorithm just for compatibility with SPDX 2.3.  In the documentation we would encourage people to use a different method.

This creates a bit of a problem with using the enumerations since one of the enumeration values would need the additional algorithm for the legacy package verification code.

Perhaps we create separate subclasses for each of the enumeration values and essentially use the subclass type as the enumeration to distinguish between the different approaches.  

I plan on creating a pull request as a proposal later today.

**Comment by goneall** [comment]
> @jeff-schutt - From the tech call on 19 Sept 2023, we decided to implement the alternative methods you described above but include the old verification code algorithm just for compatibility with SPDX 2.3. In the documentation we would encourage people to use a different method.
> 
> This creates a bit of a problem with using the enumerations since one of the enumeration values would need the additional algorithm for the legacy package verification code.
> 
> Perhaps we create separate subclasses for each of the enumeration values and essentially use the subclass type as the enumeration to distinguish between the different approaches.
> 
> I plan on creating a pull request as a proposal later today.

@jeff-schutt - I can not think of a way to solve the above stated problem without doing the additional type restrictions specified in PR #498 -  If you can come up with a solution, please reply with the approach or create a separate PR with the solution.

**Comment by goneall** [comment]
> > @jeff-schutt - From the tech call on 19 Sept 2023, we decided to implement the alternative methods you described above but include the old verification code algorithm just for compatibility with SPDX 2.3. In the documentation we would encourage people to use a different method.
> > This creates a bit of a problem with using the enumerations since one of the enumeration values would need the additional algorithm for the legacy package verification code.
> > Perhaps we create separate subclasses for each of the enumeration values and essentially use the subclass type as the enumeration to distinguish between the different approaches.
> > I plan on creating a pull request as a proposal later today.
> 
> @jeff-schutt - I can not think of a way to solve the above stated problem without doing the additional type restrictions specified in PR #498 - If you can come up with a solution, please reply with the approach or create a separate PR with the solution.

I just created a new PR #598 which attempts to implement the suggestion - not exactly in the manner suggested, but it does remove duplication of data for integrity methods.

**Comment by goneall** [comment]
Based on the package verification meeting (part of the Security profile team) discussion on 12 January 2023, we decided that the model does support package verification codes as is.  A PR will be opened to better document this in the spec.

**Comment by goneall** [comment]
With the addition of the legacy package verification code, this particular issue can be closed - note there are still some remaining open related issues

**Comment by xnox** [comment]
I cannot verify or generate SHA1 on a strict FIPS system.
From latest guidance it seems that spdx 2.3 and 3 both require to generate this? Is it allowed to produce all zeros as verification code? Or is this stanza optional in spdx 3?

What are the related outstanding issues?
