### ISSUE TITLE
Format of `standard` property

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#347]
The current description of [`standard`](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/standard.md) does not provide the format that the standard should be stated in. If this field will be relevant for machine-readability in the future, this will make parsing super-hard; from the top of my hat there might be the following variations to specify the standard name:
abbreviated lowercase, abbreviated uppercase, full name, URI to the specification

**Comment by kestewart** [comment]
I don't think we know enough at this point to move to a range of values.    In addition to IEEE, ISO/IEC, etc, there are also internal company standards that folks want to use this field for.   At this point, I suggest we treat this like a comment, rather than trying to parse it.

**Comment by goneall** [comment]
To make this forwards compatible, we should pick a property name that supports it's use as a comment and leaves open a property name we can use for an enumerated value.  We could leave the name as `standard` and introduce something like `standardEnumeration` in the future or we could change this property name to `standardComment`.

I just want to consider the compatibility before we're locked in for the 3.0 release.

**Comment by armintaenzertng** [comment]
related to #387

**Comment by goneall** [comment]
Based on tech call on 11 July 2023, we agreed to close this

**Comment by goneall** [comment]
Based on tech call on 11 July 2023, we agreed to close this
