### ISSUE TITLE
Cyclic dependency of definitions in the Model

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#35]
in https://github.com/spdx/spdx-3-model/commit/92c25fcb420934c5b32f7809cd46fc12d3d6182d one has the following cyclic dependency which is annoying when implementing:

* the `Element` definition depends on the definition of `CreationInformation`
* the `CreationInformation` contains a `createdBy` field of type `Actor` and thus depends on its definition
* `Actor` itself derives from `Element` so it is dependent on its definition

This causes a cyclic dependency between implementing modules which is really bad in some programming languages and at least annoying in others.

**Comment by iamwillbar** [comment]
Yeah, I need to go back through the minutes. I don't think Actor is meant to inherit from Element.

**Comment by maxhbr** [comment]
![2023-01-24_19-13-45](https://user-images.githubusercontent.com/1187050/214374916-839f7d31-01b0-4d5d-be1f-3653ad59e9f0.png)

**Comment by zvr** [comment]
The arrow from `CreationInformation` goes to `Identity`, but it should go to `Entity`. 

But this is minor, since we decided that it's a pointer and not an embedded Element.

**Comment by maxhbr** [comment]
The issue is, that the definition reads like

1. a **Creation Info** points to a createdBy of Type **Entity**
2. an **Element** contains a **Creation Info**
3. a **Entity** is something that extends an **Element**

So, **Entity** is used before it is defined. This is the essence of the cycle and make implementing and working very hard.

**task:** if you think there is no cycle, write the definitions without using something before it is defined

**Comment by iamwillbar** [comment]
In the `createdBy` of an entity it can refer to itself, for example, this pseudocode is valid:

```
{
  "SPDXID": "urn:william",
  "creationInformation": {
    "createdBy": ["urn:william"],
    ...
  },
  ...
}
```

**Comment by seabass-labrax** [comment]
I believe there are two options that can be taken:

1. The Element Creator field contains an **'anonymous' class** (that is, contains a 'struct')
2. The Element Creator field contains a **pointer to an Element** (that is, contains the IRI of an Element)

Both of these options have been discussed in SPDX Tech Team calls, and have been reflected at different times in diagrams committed to this repository.

Option 2, **pointer to an Element**, means that there will, logically speaking, always be at least one cycle in the supergraph of all SPDX Elements. In practice, it is likely that every SPDX data producer will at first create an SPDX Identity Element describing themselves, causing a self-referential cycle for each SPDX data producer. This is a different kind of cyclic dependency than the one that @maxhbr describes at the beginning of this issue thread: it's about the SPDX Elements in a graph, not the SPDX model definitions.

**Comment by davaya** [comment]
Entity is not "used before it is defined".  Software that creates an element (e.g., a Python dict) has two fields with the same value.

In contrast to William's example, the model is not modeling recursive values:
```
{
  "SPDXID": "urn:william",
  "creationInformation": {
    "createdBy": [
      {
        "SPDXID": "urn:william",
        "creationInformation": {
          "creatdBy": [
            {
              "SPDXID": "urn:william",
              "creationInformation": {
                "creatdBy": [
                   ...
                   
ERROR 506: Out of Memory
```

**Comment by maxhbr** [comment]
> In the `createdBy` of an entity it can refer to itself, for example, this pseudocode is valid:

This pseudocode is talking about a different problem.

**Comment by maxhbr** [comment]
> Entity is not "used before it is defined". Software that creates an element (e.g., a Python dict) has two fields with the same value.

but the term `Entity` is used before it is defined.

**Comment by davaya** [comment]
A schema is [declarative](https://www.techtarget.com/searchitoperations/definition/declarative-programming), not procedural.  All the words go onto the paper at the same time, or typed in in any order.  A person can type or a program can create:

Entity = {...}
Element = {...}
CreationInfo = {...}

in any order.  Undefined references are detected at runtime when the completed model is used, not while editing.

**Comment by maxhbr** [comment]
Yes, you are right, one has the power to write and define such structures. That is true, since also the diagram is able to define it.

But whether it is a good or not is a different question. And this issue here talks about the negative implications of this complexity introduced by it.

**Comment by davaya** [comment]
My vote would be that:
1. "goodness" is a property of implementations
2. defining the model in a way that supports references (as in William's example) is good, prohibiting them is bad
3. prohibiting dependencies between model definitions is an effect of code design, not programming language `*`
4. therefore bending the model to accommodate implementation limitations is bad

`*` Proof: JSON schema supports cyclic references and is [supported](https://json-schema.org/implementations.html) in many programming languages, compiled and interpreted, weakly and strongly typed.

**Comment by maxhbr** [comment]
> 1. "goodness" is a property of implementations 

If the data model is good to understand and good to implement and does not make it hard to describe is a property of the model.

>  * Proof: JSON schema supports cyclic references and is supported in many programming languages, compiled and interpreted, weakly and strongly typed.

This argues that it is theoretically possible to handle it and you thus agree with that there is the described cycle. So it is not a proof that there is **no** cycle, which I asked for.

> Back in the days of punch cards I do remember languages where forward references were an error, but I don't think any of them are in use today :-).

I think forward references within a file are supported in many places. **But** the initial argument was, that if you would implement it in multiple modules (or in any modular way), these modules would then have a cyclic dependency on each other. And that is discouraged and unsupported in many places.

So, after we agreed that this property described here is true, lets focus on whether it is desirable in its current form.

**Comment by maxhbr** [comment]
#### This is just a random thought, not a proposal:

I know, that we probably would not be able to agree on it but just to throw a way of resolving this issue into the round:
![2023-01-25_07-41-56](https://user-images.githubusercontent.com/1187050/214504183-773e9c49-ba1f-4c9f-8428-624fc14cb76e.png)

**Comment by davaya** [comment]
> So it is not a proof that there is no cycle, which I asked for.

I'm afraid I'm lost - are you talking about a class inheritance cycle or a data instance cycle?  There are no class cycles in the SPDX model, just as there are no class cycles in the genealogy model.  There can certainly be data cycles, including nonsense graphs like Bob is his own grandfather, but the model itself is not cyclic.

> But the initial argument was, that if you would implement it in multiple modules (or in any modular way), these modules would then have a cyclic dependency on each other.

Is it your opinion that there is no modular way to do genealogy using this model?  If you believe that there is not, then I say the implementation of "modularity" is incorrect, not the model.


![spdx-person](https://user-images.githubusercontent.com/19152940/214551261-0bfb4db7-dd30-41c8-a6d8-67cd87317f44.jpg)

**Comment by maxhbr** [comment]
> If you believe that there is not, then I say the implementation of "modularity" is incorrect, not the model.

Your example does not contain such a cycle. You would create that problem if you would reverse the arrow between `Element` and `Marriage`

**Comment by maxhbr** [comment]
This was brought up again by the Lite profile team on the SPDX Mini Summit:

![2023-09-18_15-09-25](https://github.com/spdx/spdx-3-model/assets/1187050/ce7c102a-7bae-4510-92de-1c1f36ff2aad)

I think we have not resolved all concerns here.

**Comment by davaya** [comment]
Pretend that CreationInfo did not exist, and that CreatedBy were a direct property of Element.  In that case Agent would have a self-reference cycle.  What is the problem with that?  Why is it shown in red?  An Agent instance can be created by a different Agent, and an Agent instance can be created by the same Agent.

In data instances it is just data - the Actor IRI and createdBy IRI can have the same value.

In the real world producers can use their own private keys to sign their public keys - "self-signed certificates" are a real thing.  A real-world person can produce an Actor element and designate himself as its creator.

**Comment by davaya** [comment]
OK, but I don't see it.  Element is the root class, Agent is a subclass of Element, and CreationInfo is a property of Element.  The rightmost red edge is either "CreationInfo is a property of Element" (a correct data relationship) or "Element is a subclass of CreationInfo", which is a nonsense subclassing relationship.

The diagram needs to make the subclassOf relationships clear.  There cannot be subclassOf cycles, but AFAIK the model files don't indicate that there are any.

**Comment by goneall** [comment]
I suggest this be resolved in documentation.  I agree with @davaya that this isn't really an issue, but since it does come up from time to time, we need to document what an `Agent` can have `creationInfo` with properties pointing to itself.

This could be done in the `Agent` class description, the `CreationInfo` class description and the `createdBy` property description.

**Comment by rnjudge** [comment]
4/9/2024 - Max agreed we can close this issue. We can re-open if implementers run into this issue.

**Comment by maxhbr** [comment]
@rnjudge : I fixed the status and closed it as "not planned" instead of "completed", this does better match the outcome
