### ISSUE TITLE
Would be nice to have some examples in the markdown files

### ISSUE THREAD

**Issue by rnjudge** [spdx/spdx-3-model#351]
The security profile added examples of how to use the profile under a "syntax" section. For example, see: https://github.com/spdx/spdx-3-model/blob/main/model/Security/Classes/CvssV2VulnAssessmentRelationship.md

It would be great if the other profiles could do something like this as well so users can get a sense for how to functionally implement the profiles.

**Comment by maxhbr** [comment]
the "markdown files" are not really markdown. They are something that is parsed by the spec-parser that mostly follows some markdown conventions for easy readability and for easy editing and reviewing. **They are not really markdown and the examples in the security profile are not really supported, parsed or rendered correctly.** If you are interested in such features, one would first need to extend the https://github.com/spdx/spec-parser/ accordingly. (cc @zvr )

**Comment by rnjudge** [comment]
4/9/2024 - Inline markdown for the webpages is now supported in the spec: https://spdx.github.io/spdx-spec/v3.0/model/Security/Classes/CvssV3VulnAssessmentRelationship/.

Closing this issue as the examples right now are unique to the security profile.
