### ISSUE TITLE
Update README and CONTRIBUTING with markdown format

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#354]
We're getting [requests on the Gitter channel for more information on the markdown format](https://matrix.to/#/!KroEiQRgxgEcaPSUjc:gitter.im/$zdXtkV3Wvt5WdwADQSBnDuhimoX7hMWC3MdTVIpTvQ4?via=gitter.im&via=matrix.org&via=fosdem.org).

The spec parser [documents the format grammar](https://github.com/spdx/spec-parser/blob/main/docs/md_docs/grammar.md), but I couldn't find any context other than the [property template](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Properties/_property.md) and [vocabulary template](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/_vocab.md) in core.

**Comment by goneall** [comment]
@zvr - If we don't have any docs available, I can make an attempt to write it up if you are available to review.  Just let me know.

**Comment by MordodeMaru** [comment]
Happy to help with this, @goneall

**Comment by zvr** [comment]
We have nothing written down, sorry.

And the spec-parser evolves constantly, so the documentation you pointed to may or may not be correct. The only source of truth is the actual [code](https://github.com/spdx/spec-parser/blob/main/spec_parser/parser.py), I'm afraid.

Once we finalize the format, we should make an effort to document it, obviously, but right now we're pressed to adapt it to our ever-changing needs (cf. individuals ;-)).

**Comment by goneall** [comment]
Moving to 3.0

**Comment by goneall** [comment]
> What is the motivation for using this markdown format over specifying things with Turtle that can be edited both with any text editor but also graphically via Protege?

In general terms, we have a lot of contributors to the spec who are not RDF / OWL / SHACL savvy, so we devised a format that was acceptable to that community yet allowed those of use more comfortable with RDF / OWL / SHACL to generate and review the more precise schemas.  The format was the result of very long discussions with may contributors with different perspectives.

BTW - In my workflow, I typically review the generated [model.ttl](https://github.com/spdx/spdx-3-model/blob/gh-pages/model.ttl) file using protege then update the markdown files when needed.

**Comment by aamedina** [comment]
Yeah, I can imagine how complicated marketing RDF to others is. I can figure it out, but I can see how this will be a perpetual problem the more expressive people want to get with properties. 

BTW if you want to look at some of my TTL while I explore/learn the SPDX 3 model: https://github.com/aamedina/ssvc/tree/main/resources/spdx 

I am trying to figure out the best way to go about transferring changes I make in the model here (I am importing the model into Datomic and querying with datalog, mapping SPDX 2.3 RDF I have to the new model), so I need a "source" that is relatively stable for my workflow so I will probably be pulling changes you make into that until things finalize.

**Comment by goneall** [comment]
We probably won't get this documented in time for 3.0, but still would be nice to have for future contributors.

Moving to 3.1.

**Comment by bact** [comment]
@aamedina @goneall @zvr with #867 already merged, does this issue considered fixed and can be closed?

**Comment by goneall** [comment]
> @aamedina @goneall @zvr with #867 already merged, does this issue considered fixed and can be closed?

@bact  - Agree - I'll go ahead and close it.  If anyone see any additional need for documentation please open a new issue or PR.
