### ISSUE TITLE
Add a licenseXML field to the License class

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#359]
Based on https://github.com/spdx/spdx-spec/issues/853, we should add the license XML to the listed license metadata.

We could also remove the license template field, but I would prefer to leave that in as a deprecated field for at last one release to allow migration to the new format.

**Comment by goneall** [comment]
@swinslow - let me know any thoughts.

**Comment by swinslow** [comment]
+1 to this! Given our discussion in #221 I think this is well worth it. I would agree with preserving the license template field for now as well.

My only comment is that we might consider putting it not in ListedLicense, but rather in the parent License class as an optional field (same for license text template format). That way, CustomLicenses can also implement this if the creator so chooses.

**Comment by goneall** [comment]
> My only comment is that we might consider putting it not in ListedLicense, but rather in the parent License class as an optional field

I'm good with this - I can think some uses for this for in non-listed licenses.
