### ISSUE TITLE
Is there a datatype for SPDXIDs?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#36]
I see that on element `SPDXID: IRI`, but not every `IRI` is a `SPDXID` and thus I wonder if there should be a special datatype with a defined structure. Especially if someone substitutes relations like `rootElement` with an `IRI` instead of the whole `Element`, a definition would be helpful.

**Comment by iamwillbar** [comment]
No, any IRI is a valid SPDX identifier.
