### ISSUE TITLE
VEX should be able to handle multiple vulnerability identifier types

### ISSUE THREAD

**Issue by j---** [spdx/spdx-3-model#360]
Specifically, to support some of the AI modeling work, AIID incidents should be associable within a VEX. https://incidentdatabase.ai/summaries/incidents/

**Comment by puerco** [comment]
Hey @j--- thanks for raising the issue!
From what I can understand we have it covered. The main identifier in the [vulnerability class](https://github.com/spdx/spdx-3-model/blob/main/model/Security/Classes/Vulnerability.md) is a string. And you can add any number of external references to it. Perhaps I'm not understanding this well but happy to hear more.

**Comment by goneall** [comment]
@j--- -do you agree with @puerco? if so, we can close this issue.

**Comment by goneall** [comment]
I'm going to go ahead and close this issue - @j--- if you disagree, please submit a new issue
