### ISSUE TITLE
Unable to add a File's downloadLocation

### ISSUE THREAD

**Issue by willarmiros** [spdx/spdx-3-model#362]
## Use Case

I want to build a SBOM that represents a machine learning pipeline which takes as input a dataset, trains a model, and outputs a trained model. The dataset is composed of several files, so I want to add a SBOM element that for my Dataset, and each of its child files to reflect this type of structure:

```
Dataset_1
├── s3://Dataset-bucket/path/to/file1
├── s3://Dataset-bucket/other/path/file2
└── s3://Dataset-bucket/file3
````

## Problem

In this case, my files are pulled from several different URLs, meaning I can't use the Dataset's single DownloadLocation property. 

## Proposed solution

Instead, each file should have their own URL, ideally as a `DownloadLocation` property. This property can be added to the File class or to one of its superclasses.

**Comment by willarmiros** [comment]
Upon further research, I found that I can either use an external reference of type [altDownloadLocation](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/ExternalReferenceType.md) and/or external identifier of type [pkgUrl](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/ExternalIdentifierType.md) to identify a file's URI (s3 files are supported by the PURL spec).

Would love to have confirmation from SPDX folks that these are acceptable approaches instead of directly including a `downloadLocation` property, if that's the case I can close this issue.

**Comment by zvr** [comment]
You obviously always have the option to treat each of the S3 files as a `Package` (and use its `downloadLocation`).

**Comment by willarmiros** [comment]
Ah that makes sense too. I think given we want to populate a `downloadLocation`, `version`, and `purl` for each file it makes sense to add it as a package. I'm not sure that semantically makes the most sense, as it is still a single file e.g. an image file that we are representing, which I would not consider a package, but I think that may be a bigger discussion.

**Comment by goneall** [comment]
> I'm not sure that semantically makes the most sense, as it is still a single file

The semantics for an SPDX package is an artifact that can be independently distributed - even if it is a single file - so this would be acceptable.  We even have a `SoftwarePurpose` defined for this: `file` "the Element is a single file which can be independently distributed (configuration file, statically linked binary, Kubernetes deployment, etc)"
