### ISSUE TITLE
Support license expression strings in some or all serialization formats

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#372]
In SPDX 2.X most serialization formats used license expression strings. The current 3.0 license model serialized in it’s current form can be very complex for humans to read or write.  We would like to support and specifying a license expression string format similar to SPDX 2.X.

**Comment by goneall** [comment]
From the SPDX tech call on 6 June 2023, three solution alternatives were very briefly discussed:

1. Make this purely a serialization issue – keep the model as is and create a serialization specification that uses license expression strings.
2. For every reference to `AnyLicenseInfo`, have 2 properties (e.g. `concludedLicense` and `concludedLicenseExpression`) and have rules about which takes precedence and which are required.
3. Create an optional `licenseExpressionString` on `AnyLicenseInfo` and have rules about precedence if the string is present

Since the call, I thought of a 4th possible solution:
4. Add a concrete subclass to `AnyLicenseInfo` `LicenseExpression` which would contain a single property `expression`.

**Comment by goneall** [comment]
Further elaboration on solution 4 above:
- This would avoid the conflict of having both the `Element` form of `AnyLicenseInfo` and the string.  You could only have one.
- As a subclass of `Element` it would have an `id` which solves the external reference problem for the expression string.
- It would be possible to have a license expression string as part of an `Element` based license expression - I think this is OK, but feels a bit odd

**Comment by goneall** [comment]
One issue with all of the solutions is how we represent `LicenseRef-` custom licenses in the expressions.  In SPDX 2.X, the interpretation of the custom licenses is very dependent on the SPDX document containing the reference.   We key off the specific string `LicenseRef-` to determine it is a custom license and know we can find the definition within the document itself.  If it is defined outside the document we use a namespace technique of `ExternalDocumentIdX:LicenseRef-xxx`.

Since the license expressions an be created without an enclosing document, we need a way of identifying the local licenses and finding the license definitions.  This could be done by requiring the fully expanded URI's - but that would make for some rather unwieldy expressions.

**Comment by zvr** [comment]
To give an example, we're talking about 
```json
"declaredLicense": "GPL-2.0-only OR BSD-3-Clause"
```
vs
```json
"declaredLicense": {
  "@id": "https://my.namespace/867acee9-57ec-487a-a093-314a50c87218",
  "@type": "http://spdx.org/rdf/v3/Licensing/ConjunctiveLicenseSet",
  "creationInfo": {
      "@id": "https://my.namespace/d0512e13-233f-4d75-a4c0-2e0fd585e418",
      "@type": "http://spdx.org/rdf/v3/Core/CreationInformation",
      "specVersion": "3.0.0",
      "created": "2023-06-06T00:00:00",
      "createdBy": [ "https://my.namespace/13766b41-1f22-45b4-a046-d5327f8bc51a" ],
      "profile": [ "core", "licensing" ],
      "dataLicense": "https://spdx.org/licenses/CC0-1.0"
  },
  "member": [
    "https://spdx.org/licenses/GPL-2.0-only",
    "https://spdx.org/licenses/BSD-3-Clause"
  ]
}
```

This is the simplest example, a single `OR` operator and two licenses from the License List. Anything more complicated will be... more of an eyesore.

**Comment by maxhbr** [comment]
@zvr : since we decided against nesting of elements, your second example needs to contain one more level of inderection and  would need to look like

```yaml
{
  # ...
  "declaredLicense": "https://my.namespace/867acee9-57ec-487a-a093-314a50c87218",
  # ...
},
# ...
}
  "@id": "https://my.namespace/867acee9-57ec-487a-a093-314a50c87218",
  "@type": "http://spdx.org/rdf/v3/Licensing/ConjunctiveLicenseSet",
  "creationInfo": {
      "@id": "https://my.namespace/d0512e13-233f-4d75-a4c0-2e0fd585e432",
      "@type": "http://spdx.org/rdf/v3/Core/CreationInformation",
      "specVersion": "3.0.0",
      "created": "2023-06-06T00:00:00",
      "createdBy": [ "https://my.namespace/13766b41-1f22-45b4-a046-d5327f8bc51a" ],
      "profile": [ "core", "licensing" ],
      "dataLicense": "https://spdx.org/licenses/CC0-1.0"
  },
  "member": [
    "https://spdx.org/licenses/GPL-2.0-only",
    "https://spdx.org/licenses/BSD-3-Clause"
  ]
}
```

**Comment by zvr** [comment]
OK, after thinking a lot about it, how about a more radical proposal?

While processing the data, we can all safely assume that at some point any SPDX License Expression (in a string) will get parsed and expanded into a tree.
Gary is confident that there is value in the definition (and transmission?) of the expanded tree, so we should still make it possible.
But maybe we want to put it somewhere separately?

I propose that:
The common, widely-used licensing profile should:
-	Specify the properties that artifacts should have (e.g. declaredLicense, concludedLicense), their descriptions, cardinalities, etc.
-	Also specify the values of the above, i.e., the correct syntax and interpretation of all License Expressions (as in the Annex in SPDXv2)
… and that’s it.

License-expression-tree-expansion stuff, specification of internal nodes like ConjuctiveSets etc. can all become part of something else: we can have a more specialized profile, or even (dare I say it?) an extension… It will be available for those who want it, but it won’t bother the majority of users (producers and consumers) who can live without it.


One not-ideal result is that some of us have already spent a considerable amount of time struggling with the Licensing profile as it currently is. I’m willing to write this off as “experience gained” if the SPDX project is not really helped by the presence of the expanded forms in a widely-used profile.

**Comment by maxhbr** [comment]
@zvr : In your example we at least need space for CustomLicenses (and maybe more) and the mapping between those and their references in the expressions. How would your radical proposal handle them?

**Comment by goneall** [comment]
On the more radical proposal, I'm trying to think through how this would work in practice.

I would like to be able to have any property that takes a license expression to be able to take the tree - somehow make them interchangeable.  I don't like the idea of the extension as you would have duplicated information.

I do like the idea of separating the complex license tree into a separate profile so we can keep the main case simple.

Perhaps we can combine one of the other proposals (e.g. subclassing AnyLicenseInfo) with the separate profile.  I need to think through this more, but the idea would be to have `AnyLicenseInfo`,  `LicenseExpression`, and the simpler licensing information be defined in the main licensing profile then create a `LicenseExpressionEvaluation` profile that defines the full tree expressions (e.g. `ConjunctiveLicenseSet`).  That would separate out the complexity yet still allow us to fully utilize a standardized model for the parsed expressions.

**Comment by goneall** [comment]
Decision from call on 9 June: Go with the option 6 - option 4 above with the a separate profile for the `LicenseExpressionEvaluation` as described above in [this comment](https://github.com/spdx/spdx-3-model/issues/372#issuecomment-1584752924) with the following change:
- The only subclass for `AnyLicenseInfo` is the `LicenseExpression`
- Change the name `LicenseExpressionEvalution` to `ExpandedLicense`

**Comment by goneall** [comment]
Follow-ups to our call on 9 June:
- @goneall will update PR #369 to be consistent with this decision
- created issue #380
- Others on the call to create any remaining issues with solution 6

**Comment by davaya** [comment]
Remark: [Scancode](https://scancode-licensedb.aboutcode.org/) is just a list of 2,000 (at the moment) license IDs.  So saying "developers only want scancode" is irrelevant to the SPDX model if lawyers and system evaluators say that license expressions are a requirement.

**Comment by goneall** [comment]
Decision from tech team call on 13 June 2003:
- Serialization team needs to resolve how to serialize the license expressions as a simple string without the level of indirection for at least 1 of the serialization formats (reference Package Manager persona).  This will be discussed on the serialization team on Thursday - see [here for coordinates](https://github.com/spdx/meetings#serialisation-focus-group-meetings)
- Agree with the proposal , will merge PR #380
