### ISSUE TITLE
does every Element need to implement the Payload interface, or would it be sufficient that just Collection does that?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#38]
I thought about moving the "implements" relation from `Element -> Payload` to `Collection -> Payload`. The result would look like:

![model-Core drawio](https://user-images.githubusercontent.com/1187050/198976994-ba00aff6-d0ae-48f2-81c4-87b931e42350.png)

**Comment by iamwillbar** [comment]
`Element` will have a default implementation of `Payload` that has a null/empty `imports` and `namespaces`. This was needed to meet the requirement of being able to transmit either a single element or a collection of elements.
