### ISSUE TITLE
 Serialization team needs to resolve how to serialize the license expressions as a simple string without the level of indirection for at least 1 of the serialization formats

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#386]
follow up from https://github.com/spdx/spdx-3-model/issues/372#issuecomment-1589741772: 

> - Serialization team needs to resolve how to serialize the license expressions as a simple string without the level of indirection for at least 1 of the serialization formats (reference Package Manager persona). This will be discussed on the serialization team on Thursday - see [here for coordinates](https://github.com/spdx/meetings#serialisation-focus-group-meetings)

**Comment by goneall** [comment]
Is https://github.com/spdx/spdx-3-model/issues/380 a duplicate of this issue?

In #380, I have a proposal which I believe is lossless - please review / comment in that issue.

**Comment by goneall** [comment]
I'm closing this issue - let's move any further discussion to #380 which has a proposal.
