### ISSUE TITLE
Why is there Collection and Bundle, if they just differ in an optional context?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#39]
Not sure why there is `Collection` and `Bundle`, looks like they can just be collapsed into one. Was there a discussion on that?

**Comment by iamwillbar** [comment]
There was a need to separate a grouping of elements that have a shared context (e.g. a bill of materials) versus an arbitrary set of elements (e.g. the result of a query). This was where we landed after almost 18 months of discussion on this topic.

**Comment by maxhbr** [comment]
The `Collection` is written in *italic* and thus can not be used. So one always needs to use Bundle, and since the context is optional there seems to be no issue.

**Comment by meretp** [comment]
For clarification as we are also disussing about this in #67: Should `Collection` be instantiable and therefore not be written in _italic_ -> no abstract class?
