### ISSUE TITLE
ExtendableLicense is defined twice

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#391]
... under both the Licensing profile and the ExpandedLicense profile.  Should names be unique across all profiles?

**Comment by zvr** [comment]
I don't see it in the Licensing profile: https://github.com/spdx/spdx-3-model/tree/main/model/Licensing/Classes

**Comment by davaya** [comment]
Maybe I'm confused, but https://github.com/spdx/spdx-3-model/blob/main/model/Licensing/Classes/LicenseExpression.md#metadata says:
```
## Metadata

- name: ExtendableLicense
- SubclassOf: AnyLicenseInfo
- Instantiability: Concrete
```
I would expect the name to be `LicenseExpression`.

**Comment by davaya** [comment]
https://github.com/spdx/spdx-3-model/blob/main/model/Licensing/Classes/LicenseExpression.md#metadata says:
```
## Metadata

- name: ExtendableLicense
- SubclassOf: AnyLicenseInfo
- Instantiability: Concrete
```
I would expect the name to be `LicenseExpression`.  My software is using the metadata, not the filename or the # H1 header, as the source for class names.

**Comment by goneall** [comment]
Agree this is an issue, the file name and name should match.  I probably made a copy/paste error when creating a pull request.  The name should be changed to `LicenseExpression`.  I'll create a PR to fix.
