### ISSUE TITLE
Confusion around `ExtendableLicense` and `ExpandedLicensing` profile

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#394]
I don't understand the inheritance structure in the current `Licensing`/`ExpandedLicense` profiles, especially the following part:
`Licensing:AnyLicenseInfo  -->  ExpandedLicense:ExtendableLicense  -->  Licensing:License`
If every License object (that includes `CustomLicense` and `ListedLicense`) is a subclass of `ExtendableLicense`, why are they not part of the `ExpandedLicense` profile? Same question goes for `OrLaterOperator`, which is also a subclass of `ExtendableLicense`.
Alternatively, `ExtendableLicense` might just be moved to the `Licensing` profile as it is abstract anyway and does not introduce any new properties as far as I can tell.

If the current state is indeed intended the way it is, I propose to write a bit more documentation on why we cycle through different profile for the inheritance chain above.

**Comment by armintaenzertng** [comment]
> or move the `OrLaterOperator` and `WithOperator` to the `ExpandedLicense` profile.

In that case, I think we should also move `License`, `CustomLicense` and `ListedLicense` to the `ExpandedLicense` profile, as they are all subclasses of `ExtendableLicense`.

**Comment by goneall** [comment]
> In that case, I think we should also move `License`, `CustomLicense` and `ListedLicense` to the `ExpandedLicense` profile, as they are all subclasses of `ExtendableLicense`.

In that case we should just move `ExtendableLicense` to the `Licensing` profile.  I think we would want the field definitions of the license to be in the `Licensing` profile.

@armintaenzertng - would that resolve this issue?

**Comment by armintaenzertng** [comment]
> would that resolve this issue?

On a technical level I would say yes.

But I'd be still confused why there is an extra profile that houses `ConjunctiveLicenseSet` and `DisjunctiveLicenseSet`, while `WithAdditionOperator` and `OrLaterOperator` are in a different profile. I mean, they are all made for the purpose of modeling some keyword from a license expression. Why are "AND" and "OR" in a different profile than "WITH" and "+"?

**Comment by goneall** [comment]
Let's discuss on today's tech call if we have time.

**Comment by goneall** [comment]
With PR #399 I believe this issue is resolved.

@armintaenzertng if you disagree, please open a new issue
