### ISSUE TITLE
Punch List: Annotation

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#4]
This is a punch list of open questions from the 2021-12-07 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Should annotation inherit profile from element? 
- [x] Have we articulated all the annotation types for 3.0?    Review & Other

**Comment by davaya** [comment]
Annotation should inherit profile from element.  There is no benefit to not doing so, and a large cost in complexity to try to selectively inhibit properties when Extending (inheriting from) a type.

The annotationType property should be removed.  Even if it were possible to describe a use case for annotating an Element that didn't involve looking at (reviewing) it, the nature of the purpose can be inferred from the statement. Even an "I looked at this Element and have nothing to say" could be captured by an Annotation Element with no annotationType or statement.

**Comment by iamwillbar** [comment]
* Stick with REVIEW and OTHER for now.
  * Gary had a scenario of capturing information for round-tripping/lossless data.

**Comment by jeff-schutt** [comment]
Gary's suggestion in the call is a specific use case that could be captured as it's own type: TRANSLATION
Suggest adding this as a 3rd type

**Comment by iamwillbar** [comment]
@jeff-schutt I was looking into this some more and the new "extension" property that allows arbitrary structured data to be attached to elements would be better for this. Annotations are intended for plain text content produced by humans (in SPDX 2.2 they were used as a fallback for capturing other structured information because we didn't have a better place to put it). @goneall do you think extensions will meet your needs here?

**Comment by goneall** [comment]
@iamwillbar @jeff-schutt I agree with William that extensions will meet the need for capturing the translation information.
