### ISSUE TITLE
Should SbomType be required?

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#408]
The serialization playground generates logical **types** directly from the model.  This is the logical type for
[Sbom](https://github.com/spdx/spdx-3-serialization-prototype-playground/blob/24ee04ba69b6bd808bc984fb1c310b73db6fc54e/model/generated_20230705T100948Z/Software/Sbom.md):

## [Sbom](https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/Sbom.md)
Model: [828388b](https://github.com/spdx/spdx-3-model/commit/828388b98c2374f1af6b760ab87fee0d4a11e3f4) 2023-07-05T10:09:48Z
```
class Sbom:
    sbomType: SbomType = None                          # optional Set[1..*]
    context: str = None                                # optional 
    element: SpdxId = None                             # * Set[1..*]
    rootElement: SpdxId = None                         # * Set[1..*]
    namespaces: NamespaceMap = None                    # optional Set[1..*]
    imports: ExternalMap = None                        # optional Set[1..*]
    spdxId: SpdxId = None                              # * 
    name: str = None                                   # optional 
    summary: str = None                                # optional 
    description: str = None                            # optional 
    comment: str = None                                # optional 
    creationInfo: CreationInfo = None                  # 
    verifiedUsing: IntegrityMethod = None              # optional Set[1..*]
    externalReference: ExternalReference = None        # optional Set[1..*]
    externalIdentifier: ExternalIdentifier = None      # optional Set[1..*]
    extension: Extension = None                        # optional Set[1..*]
```
Logical **values** (use case examples) are types with property values filled in, and serialized data will be converted to/from the use case's logical value.

It seems odd that sbomType should be optional, and even odder that it has maxCount: *, but that is what the model file says. [Relationship](https://github.com/spdx/spdx-3-serialization-prototype-playground/blob/b60b3de89af68ba94b53e49ed8f83baa67f1d8b6/model/generated_20230705T100948Z/Core/Relationship.md) also seems odd; is it even possible to have a relationship with no "to"?  We should take a closer look at all of the model files to determine if property multiplicity is what we expect.

Or perhaps I'm mistaken and there are use cases for an Sbom Element to have [0..*] types or a Relationship with a from and no to.

**Comment by goneall** [comment]
Kate and I discussed and we don't think this needs to be required.

@davaya please reopen if you feel strongly about this.

**Comment by davaya** [comment]
I don't object or feel strongly about it.  If it makes logical sense (i.e., there are use cases) for an Sbom to have no type or to have multiple types (`["build", "design", "source", "deployed"]`) then the model should reflect the use cases.
