### ISSUE TITLE
Properties with a range of a class with properties should not be "Data Types"

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#409]
Several properties with nature `DataProperty` have a range of a class which contains properties.

These properties should be object properties.

In RDF, a Data property can only have a range of a Datatype (at least in my Protege editor).

@zvr @armintaenzertng, @sbarnum if you agree, I can create a PR to fix.

**Comment by zvr** [comment]
I completely agree.

We have been using the maxim: "if the value is an object it's an ObjectProperty; if it's not (doesn't have an id) it's a DataProperty".

This is wrong.
It's a DataProperty only if the value is a (simple) literal.

**Comment by goneall** [comment]
For properties with an enumeration type (e.g. `relationshipType`), the class restriction is an `ObjectType`, so it looks like they also need to be changed to `objectProperties` to be consistent.
