### ISSUE TITLE
What is the difference between Actor and Identity?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#41]
Why is there `Actor`? Feels like something that could be satisfied by `Identity` or at least very closely matches that?

**Comment by iamwillbar** [comment]
Here is the meeting where this was discussed:
https://github.com/spdx/meetings/blob/29edd3ae5078c9603efca1bcdaf41ecd01616ba0/tech/2022-04-12.md

"Actor" is the technical entity that was observed taking an action, it could be nothing more than an identifier (e.g. a GitHub username).

"Identity" is a real-world entity such as a Person or Organization.

We may, or may not, know the relationship between an "Actor" and an "Identity". An "Actor" may be related to an "Identity" (e.g. William owns the GitHub username 'iamwillbar') and that relationship can change over time (e.g. a GitHub organization 'spdx' may change owners over time).

**Comment by maxhbr** [comment]
thanks
