### ISSUE TITLE
Define Dataset/PresenceType

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#416]
[Dataset/senasitivePersonalInformation](https://github.com/spdx/spdx-3-model/blob/main/model/Dataset/Properties/sensitivePersonalInformation.md) references Dataset/PresenceType which is not defined in [Vocabularies](https://github.com/spdx/spdx-3-model/tree/main/model/Dataset/Vocabularies)

**Comment by goneall** [comment]
@rgopikrishnan91 and @kestewart  - can you create a pull request for this?

**Comment by armintaenzertng** [comment]
This is actually defined in the AI profile. If both profiles want to use that vocabulary, we should probably move it to Core, right?

I'm still confused why we need an additional type for what is essentially an optional Boolean, though...

**Comment by goneall** [comment]
@kestewart Is `PresentType` something considered to be AI specific or is it something more general?  If the latter, we should move it to core.

In either case, we should update [Dataset/senasitivePersonalInformation](https://github.com/spdx/spdx-3-model/blob/main/model/Dataset/Properties/sensitivePersonalInformation.md) to point to the correct place.

**Comment by goneall** [comment]
I can create a pull request to fix.
