### ISSUE TITLE
How can we tell if a class is abstract from the OWL Ontology / SHACL file?

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#418]
I'm not sure if this is an issue for the model of the spec parser, but I'm having trouble determining if a particular class (e.g. `Element`) is abstract solely from the generated OWL/SHACL file.

**Comment by goneall** [comment]
@JPEWdev @zvr - any ideas?  Should we add this to the annotations SHACL file?  I need this information for generating Java code - right now it is hard-coded (rather inconvenient).

**Comment by zvr** [comment]
If someone can provide the correct SHACL to add, I can easily add it to the generated ontology.
@sbarnum , any ideas?

**Comment by goneall** [comment]
I looked through the [SHACL spec](https://www.w3.org/TR/shacl) and couldn't find anything obvious.  We could construct a (rather convoluted) SPARQL query, but since this is primarily for code generation that would probably be overkill.

One possibility would be to generate text in the description that it is abstract (e.g. "[Abstract] This class ...") or perhaps we could annotate it in another way.

@JPEWdev @sbarnum - any thoughts?

**Comment by zvr** [comment]
If we want to have it so that this is enforced on arbitrary SPDX data, we should construct some SHACL that says "select all objects of type X (and not of any type inherited from X) and ensure that the result is empty".

If we only want it for the code-generation (shacl 2 code), we could easily have our own `spdx:AbtractClass` (inheriting from `owl:Class`) and add it to the generated SHACL, so it can be recognized.

**Comment by goneall** [comment]
> If we want to have it so that this is enforced on arbitrary SPDX data, we should construct some SHACL that says "select all objects of type X (and not of any type inherited from X) and ensure that the result is empty".
> 
> If we only want it for the code-generation (shacl-to-code), we could easily have our own `spdx:AbtractClass` (inheriting from `owl:Class`) and add it to the generated SHACL, so it can be recognized.

How about both?

We could add the `spdx:AbstractClass` now then add the SHACL once we figure it out.  I make a brief attempt at coming up with the SHACL a couple days ago and found it a bit more of a challenge than I expected.

**Comment by bact** [comment]
Does https://github.com/spdx/spec-parser/pull/158 already solve this? @goneall

**Comment by goneall** [comment]
> * Does [use equivalentClass instead of AbstractClass spec-parser#158](https://github.com/spdx/spec-parser/pull/158) already solve this? @goneall

Yes - I'll go ahead and close as resolved
