### ISSUE TITLE
Update model-security-profile.png 

### ISSUE THREAD

**Issue by rnjudge** [spdx/spdx-3-model#419]
https://github.com/spdx/spdx-3-model/blob/main/model-security-profile.png is outdated due to several changes that have been made (i.e. https://github.com/spdx/spdx-3-model/pull/346 and https://github.com/spdx/spdx-3-model/pull/338). This diagram needs to be updated to reflect those changes.

This diagram also needs to be uploaded to the security meeting minutes so it is publicly available to edit in the future. @tsteenbe can you help here?

**Comment by rnjudge** [comment]
Looks like anyone can do this, just need to update https://github.com/spdx/spdx-3-model/blob/main/model-security-profile.drawio

**Comment by goneall** [comment]
@tsteenbe - can you take this on or get a volunteer from the security profile team?

**Comment by goneall** [comment]
It looks like this is part of PR #578 which needs one more review to merge.

@rnjudge - can you review to see if it includes the updates requested?

**Comment by goneall** [comment]
Closing this as PR #578 is merged

@tsteenbe if you think it needs a further update, please create a separate PR
