### ISSUE TITLE
Proposal: Change cardinality of specVersion to required

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#421]
Not having the `specVersion` in the creation info will make certain validation, conversion and parsing unreliable.

Note that this is already required in SPDX 2.3 and all previous versions.

**Comment by davaya** [comment]
Yes.

**Comment by armintaenzertng** [comment]
I absolutely agree, no version info will totally trip up tooling.

I opened #422 to fix this.

**Comment by armintaenzertng** [comment]
While we are at it, should `dataLicense` be mandatory, too? (If this requires more discussion, we can open a separate issue.)

**Comment by goneall** [comment]
> While we are at it, should `dataLicense` be mandatory, too? (If this requires more discussion, we can open a separate issue.)

There is a [change proposal](https://github.com/spdx/change-proposal/issues/8) to make the `dataLicense` optional - so we should wait until that is resolved before changing.
