### ISSUE TITLE
Include Profile in model markdown files?

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#429]
Looking at the Security team's real-world examples (including [Vulnerability](https://github.com/spdx/spdx-3-model/blob/main/model/Security/Classes/Vulnerability.md)) brings up the question of profile information contained in the model markdown files.  Like all other model files, there is no indication within the file of where the vulnerability class is defined.

This is what the playground model parser reads from the latest GitHub files:
```
"Vulnerability": {
  "Summary": {},
  "Description": {},
  "Metadata": {
    "name": "Vulnerability",
    "SubclassOf": "/Core/Element",
    "Instantiability": "Concrete",
    "_modelRef": "https://rdf.spdx.org/v3/Security/Vulnerability",
    "_profile": "Security",
    "_category": "Classes",
    "_file": "Vulnerability.md",
    "_html": "https://github.com/spdx/spdx-3-model/blob/main/model/Security/Classes/Vulnerability.md"
  },
  "Properties": {
    "publishedTime": {
      "type": "/Core/DateTime",
      "minCount": "0",
      "maxCount": "1"
    },
    "modifiedTime": {
      "type": "/Core/DateTime",
      "minCount": "0",
      "maxCount": "1"
    },
    "withdrawnTime": {
      "type": "/Core/DateTime",
      "minCount": "0",
      "maxCount": "1"
    }
  }
},
```

It extracts synthetic metadata from the GitHub filesystem, including the fact that file "Vulnerabilities.md" is in the "Security" directory of the file tree.  That means that if by mistake some files were moved to different folders, that would change the model that was parsed from them.  That seems a bit haphazard; it might be more reliable to include profile in the content of the file itself, which would allow a parser to detect if files have been misplaced.

There are three options:

1. change the metadata "name" field to indicate the profile, as is done with other fields:
```
    "name": "/Security/Vulnerability",
    "SubclassOf": "/Core/Element",
    "Instantiability": "Concrete",
```
2. add a "profile" metadata field:
```
    "name": "Vulnerability",
    "profile": "Security",
    "SubclassOf": "/Core/Element",
    "Instantiability": "Concrete"
```
3. status quo: leave the profile unspecified except through file location.

I suggest option 1 - update all the model files to include profile in the `name` metadata field, and update the spec-parser to check for discrepancies between name and location..

**Comment by jeff-schutt** [comment]
I agree that the markdown files should explicitly define in which profile a class has been defined. Option 2 would convey the profile while also helping to ensure that two classes in two different profiles aren't named the same.

**Comment by goneall** [comment]
Since this would be a significant amount of work and it only impacts the documentation, I'm going to move this to 3.1

**Comment by zvr** [comment]
@goneall I think this can be closed.

Each generated file has the information on which profile it belongs, and we are using the convention that everything non-local (in other profiles) is specified by `namespace/entity`.

**Comment by goneall** [comment]
Agree with @zvr  - closing
