### ISSUE TITLE
The examples in the diagram contain `"software"` profile elements but do not list it under profiles

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#43]
as mentioned in https://github.com/spdx/spdx-3-model/issues/42, the examples in the diagram contain `"software"` profile elements (e.g. `SBOM`) but do not list it under `profiles` in their creation info. This probably should be fixed.

Ping @iamwillbar

**Comment by kestewart** [comment]
@maxhbr - I believe this has been addressed now.   Closing this.   Please reopen if you disagree.
