### ISSUE TITLE
JSON Serialization Example Code

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#430]
@nishakm created example JSON data and Python code for a ["Simple Acme" app](https://github.com/spdx/spdx-3-serialization-prototype-playground/tree/main/implementations) for the serialization playground (implementations/1). 

@armintaenzertng has a PR comparing three JSON-LD compaction approaches, still in draft.

I created a copy of Nisha's JSON data and massaged it into v3 format (camelCase property names, PascalCase profiles, flat list of elements (there are 5), and added a type property to each element.  There is still work needed on the element content, but in its current form is sufficient for demonstrating payload compaction.  The `payload_simple_acme.json` file and `expand-payload.py` example code are in [implementations/2](https://github.com/spdx/spdx-3-serialization-prototype-playground/tree/main/implementations/2).

The code takes a compacted payload:
```
{
  "namespaceMap": {},
  "creationInfoMap": {},
  "element": [
    "element1",
    "element2",
    "..."
  ]
}
```
and converts it to a full (uncompacted) element list:
```
[
  "element1",
  "element2",
  "..."
]
```

It takes literally two lines of code to de-compact an element's creationInfo, and literally four lines to fill in namespace prefixes using namespaceMap (two of which check to see if the spdxId is already a full IRI).

The purpose of the playground is to experiment, and by experimenting with real data dispel unfounded assumptions regarding the difficulty of non-RDF JSON serialization.

**Comment by goneall** [comment]
We decided not to tackle anything other than JSON-LD for 3.0 - closing this for now
