### ISSUE TITLE
Missing Extension class

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#433]
The Element refers to an `extension` property of type `Extension`.  There is no class definition which is causing some RDF OWL validations to fail.

**Comment by sbarnum** [comment]
It used to exist in the model diagram on the right side with the other non-Element classes as a simple abstract (italic name) class without properties.
I agree that the model should include such an abstract class as a basis for defining extension subclasses.

**Comment by maxhbr** [comment]
@sbarnum : I think that you planned to write down the semantics and details, as it was unclear for and misunderstood by most other participants. Until that, at least I am not able to add it in and would prefer to drop it for now (as an incomplete and misunderstood feature, that can no longer be fixed, is worse than adding the feature later).

**Comment by maxhbr** [comment]
Wasn't there the tentative decision to move extensions to their own profile?

See also 
- the corresponding issue: https://github.com/spdx/spdx-3-model/issues/47#issuecomment-1533592094
- the action item from the meeting notes: https://github.com/spdx/meetings/blob/f1955693dd8a9c339813f9c3d1cbb37f434d8561/tech/2023-05-02.md?plain=1#L163

both waiting for input from @sbarnum

**Comment by goneall** [comment]
@sbarnum will take a look at this

**Comment by goneall** [comment]
Resolved with PR #503
