### ISSUE TITLE
Update model.png to indicate suppliedBy property is plural

### ISSUE THREAD

**Issue by rnjudge** [spdx/spdx-3-model#437]
The `suppliedBy` property [here](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/Artifact.md) indicates that there is no max count. However, the [model.png](https://github.com/spdx/spdx-3-model/blob/main/model.png) diagram indicates the max count is [0..1].

The diagram needs to be updated.

**Comment by goneall** [comment]
Reference the minutes from [Tech Call 21 Mar 2023](https://github.com/spdx/meetings/blob/main/tech/2023-03-21.md#supplier-property) - it looks like we decided on cardinality [0..1] - so the diagram is right, the property MD file needs to be updated.

**Comment by goneall** [comment]
@rnjudge - Can you change the title to "Update suppliedBy cardinality to [0..1]"?
