### ISSUE TITLE
Clarify validation of LicenseExpression

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#440]
Currently, the `LicenseExpression` has a validation of just `xsd:string` when in fact the real validation should involve fully parseable and checking on the validity of the ID's (e.g. listed license ID's).

**Comment by swinslow** [comment]
Thanks @goneall, +1 from me.

A `LicenseExpression` string should only be treated as valid if it correctly conforms to the [License Expression Syntax](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/). Arbitrary `xsd:string` values that are not valid expressions under the License Expression Syntax should not be valid `LicenseExpression` objects.

For ListedLicenses, agreed that this involves confirming that each such ID is validly on the [License List](https://spdx.org/licenses). New license IDs may be added over time, but to my knowledge the Legal Team has committed that existing IDs will _not_ be removed after a release has been published. (License IDs that are deprecated remain valid and remain on the License List.)

For CustomLicenses, this would involve confirming that the ID has the `LicenseRef-` prefix and a valid set of characters following it. Note also the permitted use of `DocumentRef-abc:` prior to the LicenseRef- prefix in the syntax.

Similar concepts would apply to ListedLicenseExceptions and CustomLicenseAdditions.
