### ISSUE TITLE
Document License Expressions

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#445]
In 2.3, license expressions are documented in their own Annex.

We do not have a place to document the full expression - yet.

Note that we need to update the expressions to handle custom license additions as discussed in issue #208

**Comment by jlovejoy** [comment]
this is also true/an issue for the matching guidelines, license list, use of SPDX ids - all appendices in the current spec. Maybe we should discuss these together, as whatever is decided for one might be good for all?

as to the license list itself, I'm in favor of simply removing that :)

**Comment by zvr** [comment]
But please remember that this repo is for the **model** not the spec. The spec will be generated and produced in another place (our good ol' spdx-spec or another repo).

**Comment by swinslow** [comment]
@zvr One question about this:

Although [`licenseExpression`](https://github.com/spdx/spdx-3-model/blob/main/model/SimpleLicensing/Properties/licenseExpression.md) is an `xsd:string`, as described in #440 only valid license expressions under the License Expression Syntax should be treated as valid.

Does that mean that the license expression syntax should be documented in this repo (perhaps in https://github.com/spdx/spdx-3-model/blob/main/model/SimpleLicensing/Properties/licenseExpression.md)? If so, I can prepare a revised copy from the relevant parts of the Annex in SPDX 2.3, and also add in Custom License Additions.

**Comment by zvr** [comment]
No need, @swinslow .  The spec (v3) already has an annex to describe license expressions: https://spdx.github.io/spdx-spec/v3.0/annexes/SPDX-license-expressions/ -- and it's been updated to include custom additions, for example.

**Comment by swinslow** [comment]
Got it, thank you @zvr! 

Given that, does anything need to be changed in [`licenseExpression`](https://github.com/spdx/spdx-3-model/blob/main/model/SimpleLicensing/Properties/licenseExpression.md) to make it explicit that the `xsd:string`'s value needs to conform to the License Expression Syntax, in order for the `licenseExpression` to be valid?
