### ISSUE TITLE
Consider using sh:in instead of owl:oneOf to model enumerations with SHACL

### ISSUE THREAD

**Issue by aamedina** [spdx/spdx-3-model#460]
I am working through learning the SPDX 3 model and noticed that some classes use owl:oneOf to denote enumerated individuals (like AnnotationType, RelationshipType instances etc.). 

I have been noticing that since SHACL shapes are used throughout the vocabulary the OWL terms seem redundant since there is no particular leverage from OWL that is being used in the current model. It seems to me more like a marker that "this an enumerated value" derived from a class. I think to express that semantic (correct me if I'm wrong) it is more appropriate to use sh:in. 

Would it be helpful to separate the model into a base RDF(S) model with no OWL or SHACL and then add two additional models respectively adding named individuals and owl:oneOf to the "OWL" model and the various sh:NodeShape constraints in a "shapes" model.

This way consumers could choose the appropriate model for their graph.

**Comment by aamedina** [comment]
Thoughts: It may not even be necessary for SPDX to have anything beyond owl:NamedIndividual and owl:Ontology for the namespace metadata wrt OWL

**Comment by zvr** [comment]
Implemented via https://github.com/spdx/spec-parser/pull/113
