### ISSUE TITLE
ML-Schema 

### ISSUE THREAD

**Issue by aamedina** [spdx/spdx-3-model#461]
seeAlso: https://ml-schema.github.io/documentation/ML%20Schema.html

There is (or was?) a working group to define a RDF ML model, here is the GitHub: https://github.com/ML-Schema/core

Just adding a note here in case anyone wants to look at it for inspiration for the SPDX AI Profile.

**Comment by aamedina** [comment]
seeAlso: https://bioportal.bioontology.org/ontologies/AIO

**Comment by goneall** [comment]
@aamedina - We just release the RC2 version of the spec and we're going to setup a separate thread and/or meeting to go through this and all the other RDF/SHACL/OWL labelled SPDX issues.  I just sent out an email on the SPDX tech email list: https://lists.spdx.org/g/Spdx-tech/message/5538 

My current thinking is we have separate SPDX tech call just to focus on the RDF related issues and work through them.  Please reply to the email thread if you're available to participate.

**Comment by goneall** [comment]
cc @bennetkl @kestewart @bact @rgopikrishnan91 - I wanted to make sure the AI team was aware of the parallel work mentioned above.

I'm going to close the issue as part of the 3.0 release clean-up

**Comment by bennetkl** [comment]
Thanks @goneall  ,  We will watch for further discussions.
