### ISSUE TITLE
How should the external properties restriction of SPDX Lite (Profile) .md be listed?

### ISSUE THREAD

**Issue by yoshi-i** [spdx/spdx-3-model#462]
To refrecting the discussions  in the July 24 Tech team call, Kobota-san, Ninjoji-san, me and collegues reviewed SPDX Lite (Profile) to make new PR.

We are not sure how to describe the following three points, so we'd like to ask SPDX community.
1. Which class and element should be used to represent a license with or without an SPDX short ID?  
   It seems to reconfigure Licensing classes in [issue#399](https://github.com/spdx/spdx-3-model/pull/399).
2. How do we list the elements that need to be listed if they are present in the deliverable but not if they are not?  
   For example, if there is a CustomLicense, it should be listed but not if there is none.
3. When we receive an archived file of an OSS package, how should the file name be represented?  
   For example, if we receive nginx v1.25.1 in the file nginx-1.25.1.tar.gz, Package/name == nginx and Package/packageVersion === 1.25.1. So what classes and elements should be used in the file names passed in and how should they be associated with the package information?

**Comment by goneall** [comment]
Propose that we use the following format:

In the profile's markdown file (e.g. `model/Lite/SPDX-Lite.md`) in addition to the `Summary`, `Description` and `MetaData` sections, add a section `External Property Restrictions`.

The `Restrictions` section would have the same format as the `External Property Restrictions` in the class definitions except the highest level bullet would be the fully qualified class name.

For example, to create a restriction that every package has a copyright text property:

## External properties restrictions
- /Software/Package
  - /Software/CopyrightText
    - minCount: 1

For required relationships, a new section `External relationship restrictions` would be added with the type, from range, to range, and cardinality specified.

For example, to create a restriction that every package must have one and only one concluded license relationship:

## External relationship restrictions
- relationshipType: concludedLicense
- fromRange: /Software/Package
- toRange: /SimpleLicensing/AnyLicenseInfo
- minCount: 1
- maxCount: 1

@zvr - Let me know if this is OK / implementable in the spec-parser.

**Comment by jeff-schutt** [comment]
In the security profile we chose to implement `External property restrictions` in a similar manner, in order to ensure at least 1 `to` relationship restriction existed (changed from min count 0 to min count 1). See https://github.com/spdx/spdx-3-model/blob/main/model/Security/Classes/VulnAssessmentRelationship.md#external-properties-restrictions

It's unclear if we need two different types of restrictions (property & relationship) or if simply using `External property restrictions` is enough.

**Comment by davaya** [comment]
There are two situations:
1) A profile team adds a restriction and defines a new class
2) A profile team adds a restriction and does not define a new class

For situation 1, /Software/Package adds a minCount: 1 restriction to Core/Element/name, or Jeff's example of security relationships.

For situation 2, it is definitely easier to use external properties restrictions.  But for situation 1, using external properties restrictions is unnecessary.

Question: When a profile team does create a new class, is it allowed to add restrictions to existing properties/relationships without using "External Restrictions"?

**Comment by goneall** [comment]
> Question: When a profile team does create a new class, is it allowed to add restrictions to existing properties/relationships without using "External Restrictions"? I'd like an explicit statement that this is possible and supported.

If you are defining a new class which is a subclass of an existing class, you can add a restriction in that class definition using the External property restrictions section on the class file - see the [File for an example](https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/File.md#external-properties-restrictions).

In the case of adding a restriction to an existing property or class which is not a superclass, you would add that restrictions to the profile markdown file per the above proposal.

**Comment by goneall** [comment]
@sbarnum provided the SHACL that will enforce the relationship constraints.

I made a few modification to match the current model.

There are two attached files:
- [lic-restriction-shape.ttl.txt](https://github.com/spdx/spdx-3-model/files/12716317/lic-restriction-shape.ttl.txt) - the shape we should generate for the above concluded license relationship restriction
- [model.ttl.txt](https://github.com/spdx/spdx-3-model/files/12716332/model.ttl.txt) - The complete model.ttl generated from the current model + the relationship restriction shape added to the end of the file

Note that the current restriction only looks for existence of the relationship - it does not strictly validate the min and max cardinalities.  I don't think it is checking the type of the "to" element either.

**Comment by goneall** [comment]
Based on the SHACL restrictions and review by @sbarnum , I updated the syntax for defining the External Relationship Restrictions to remove the cardinality and "to" type restrictions.  The semantics of this external relationship restriction is that it will require 1 or more relationships.

The reason for removing the specific cardinality is that, as separate Elements, relationships can be added at any time.

The reason for removing the "to" type restriction is that it is typically an aspect of the relationship type, not the additional restriction. Note: we could add "to" restrictions based on type in a separate format proposal.

**Comment by goneall** [comment]
@yoshi-i - Just noting the change in format noted above for use in the SPDX-Lite profile.

**Comment by goneall** [comment]
@zvr - Can we proceed with the recommended syntax above?

The alternative would be to duplicate all classes to add the restrictions as done here: https://github.com/spdx/spdx-3-model/pull/521

**Comment by yoshi-i** [comment]
The issues raised in this issue list have been resolved. Discussions regarding the specifics of individual definitions will be conducted through Pull Requests.
