### ISSUE TITLE
Issue with Property rdfs:domain 

### ISSUE THREAD

**Issue by aamedina** [spdx/spdx-3-model#465]
I have found that the model being generated RDF property definitions like the following:

```turtle
spdx-core:verifiedUsing a owl:ObjectProperty ;
  rdfs:comment "VerifiedUsing provides an IntegrityMethod with which the integrity of an Element can be asserted." ;
  rdfs:range spdx-core:IntegrityMethod ;
  sh:or ( [
    rdfs:domain spdx-core:Element ;
    rdfs:domain spdx-core:ExternalMap ;
  ] ) ;
  vs:term_status "Stable" .
```
In OWL you would write something like:

```turtle
spdx-core:verifiedUsing a owl:ObjectProperty ;
  rdfs:comment "VerifiedUsing provides an IntegrityMethod with which the integrity of an Element can be asserted." ;
  rdfs:domain [ owl:unionOf ( spdx-core:Element spdx-core:ExternalMap ) ] ;
  rdfs:range spdx-core:IntegrityMethod ;
  vs:term_status "Stable" .
```
If the intention is to use SHACL to express the same constraint you would need to add a sh:PropertyShape, am I wrong in assuming that? I think the syntax is different:

```turtle
ex:VerifiedUsingShape a sh:PropertyShape ;
  sh:path spdx-core:verifiedUsing ;
  sh:or (
    [ sh:class spdx-core:Element ]
    [ sh:class spdx-core:ExternalMap ]
  ) ;
  sh:class spdx-core:IntegrityMethod .
```
Either way I do not believe any RDF tools will be able to infer the domain as you want. Maybe the owl:unionOf is simpler in this case. Alternatively, consider [`schema:domainIncludes`](https://schema.org/domainIncludes).

**Comment by maxhbr** [comment]
Interesting point. I think this would need to be fixed in https://github.com/spdx/spec-parser.

(CC @zvr )

**Comment by goneall** [comment]
@zvr - is this issue resolved with the latest spec parser?

**Comment by goneall** [comment]
Or should we move this to 3.1 as @aamedina sugests?

**Comment by zvr** [comment]
We do not include `rdfs:domain` in our current generated ontology.
