### ISSUE TITLE
Reinserting deleted text for concludedLicense and declaredLicense

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#466]
In #448 it looks like a lot of context details for [concludedLicense](https://github.com/spdx/spdx-3-model/blob/8dff2a3243c9e00e1eb170fac749450a845ccdd6/model/Software/Properties/concludedLicense.md) and [declaredLicense](https://github.com/spdx/spdx-3-model/blob/8dff2a3243c9e00e1eb170fac749450a845ccdd6/model/Software/Properties/declaredLicense.md) were deleted as part of moving them from properties to relationships.

The content in the "Description" parts of those files is key to the meanings of concludedLicense and declaredLicense, and was part of addressing some specific complaints from 2.x.

I'm happy to submit a PR to reinsert it, but not sure where it should be placed for relationships. Just want to make sure it doesn't get dropped. Thanks!

**Comment by goneall** [comment]
@swinslow Agree - as the one who dropped it ;)  Currently, there is only a short summary for each relationship in the relationship types.

One idea is to add the full context in the profile's markdown file and create a reference to that markdown file in the summary descriptions.

Now, the question is, which profile do we add this to?

There is a related issue in that we are not capturing the additional restrictions in either profile markdown.

I'm thinking we create yet one more licensing related profile Licensing which contains nothing but documentation and restrictions.  We would use SimpleLicensing and ExpandedLicensing for only namespace purposes.

If this make sense, I can create a proposal.

Note - this is related to issue #463

**Comment by jlovejoy** [comment]
I think #456 adds the missing text?

**Comment by goneall** [comment]
> I think https://github.com/spdx/spdx-3-model/pull/456 adds the missing text?

It does - I'll delete my comment above.  I guess I already added it to the previous PR.

Thanks for catching this @jlovejoy

**Comment by goneall** [comment]
This is fixed with #456 - closing the issue
