### ISSUE TITLE
Design/Model/Serialization Frenzy

### ISSUE THREAD

**Issue by karsten-klein** [spdx/spdx-3-model#471]
In todays SPDX-Defects meeting I was tasked to write up my observations/concerns/ideas in an issue. I try my best to put this in brief sentences.

Today and also the recent weeks I witnessed a high level of frustration and impatience. Of course this is natural as we a heading towards an RC2 of SPDX 3.0. However, it appears to me that understanding the root causes for these discussions we are having is key to make 3.0 a success.

I guess we all share the objectives:
* we want to make 3.0 happening
* we would like to maximize adoption
* we would like to be early adopters
* we would like to see SPDX being a practical, efficient and highly effective way to describe software, its characteristics and the assertions the creators would like to express.

Having followed the discussions in various groups I currently conclude:
* the current SPDX model is not easy to understand
* its even more problematic when trying to convey a specific use case or scenario in the model
* we have certain design-smells going along with the model which are triggers for unprecedented discussions (property vs relationships, relationship overuse, extensive properties on relationships, lack of a domain-specific language or even a lack of words to express the use cases)
* we try to resolve issues within the model during serialization (and the other way around)
* we are unable to express ourselves in the model (and fail explaining it to others)

For me a potential way out could be:

We realize - as a group - that we currently have a design / abstraction issue.

We understand the need to differentiate different model / abstraction layers. At least: 
1) The serialization level model.
2) The SPDX model giving us certain core concepts, relationships and modular profiles.
3) An abstraction level to express / model the use case and to create sound examples; this level enables us to speak in natural language "about the model" and create harmonized graphical illustrations / diagrams.

To the latter I would refer to as "logical model" and "instances of the logical model". The SPDX model is a "generic technical model", while the serialization model is a helper abstraction to isolate specifics of the formats that we want to support (also a technical model, but a task-specific technical model).

The current problem arises from the fact that we need (at least) these three abstractions, but we always keep stumbling and swinging between the models and argue on the specifics that currently suit us best. In my eyes we need to halt, breathe and observe: every model has its arguments and we must not mix but honor them. Trying to omit one of models causes issues. 

So I challenge all to think along these lines and to collect ideas on how this could be achieved/implemented. 

In the end of course, we need to map back and forth between these abstraction layers. But when we discuss "the model", we always stay within its boundaries, respectively.

We may observe that the current SPDX model is not too far away from what is required. However, I anticipate we can optimize the current model to gain further options and flexibility (without sacrificing attributes of the others).

I hope I could convey my thoughts...
Regards,
Karsten

**Comment by davaya** [comment]
This will require the tech team to decide if the are really going to separate serialization from the logical model, or just give it lip service and then have to deal with the resulting frenzy of confusion.

> every model has its arguments and we must not mix but honor them.

**This**, x100.

The logical model is defined using RDF, that's universally agreed.  The serialization model must be separate from the logical model, but it too could be defined using RDF, if only there were agreement to use RDF to define datatypes (like CreationInfo, PositiveIntegerRange and Payload).  Only by understanding that these are datatypes, not graph nodes, will it be possible to define an RDF serialization model.  In the absence of that agreement, the serialization model will need to be defined directly using either serialization-specific concrete schemas for each format, or a single serialization-agnostic information model (abstract schema) for all formats.  RDF already defers to XSD to defining the Lexical-to-Value (L2V) mapping of simple datatypes for XML serialization.

**Comment by kestewart** [comment]
I think this is now OBE (overtaken by events), and am closing since the discussion is stale, and we have released rc2 and we now have a JSON schema.    If there are elements that we should tackle,  please open an issue against 3.1.
