### ISSUE TITLE
Question: How would "infered" or "implicit" creationInfo in a serialization work?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#48]
(I know that this is a serialization question. But we are right now acting under the assumption that serialization can answer this question so I think it is fair to ask it already)

Hey, I came up with the following example:

lets say you have a SPDXDocument called `SPDXDocument` containing a SBOM called `SBOM` containing a Package called `Package`. 

This can be encoded either completely inlined or the `Package` can be pulled one level up and just be referenced in the `SBOM` element. And both are parsed to the same internal representation.

So, in some kind of pseudo code it could look like:
```
SPDXDocument {
  SBOM {
    Package
  }
}
```
or
```
SPDXDocument {
  SBOM {
    PackageRef
  },
  Package
}
```

Now, my question is the following:
* Under the assumption, that `SPDXDocument` and `SBOM` would have different creationInfos, which of these would be inferred to `Package`?

And as a potential follow up / equivalent question:
* If a package or reference of a package appears in multiple collections, which one should be infered?

**Comment by maxhbr** [comment]
Or in the case
```
SPDXDocument {
  SBOM1 {
    Package
  },
  SBOM2 {
    Package
  },
  Package
}
```
where SBOM1 and SBOM2 have different creationInfos, one has the same issue.

**Comment by maxhbr** [comment]
a discussion in the last tech meeting sounded like, that only the one creationInfo from the top level element should be inferred to elements without their own. Instead of every element gives the creationInfo to its children.

**Comment by davaya** [comment]
The data for element should be independent, with all elements inheriting from Payload and no element inheriting from another:

Payload [
  SPDXDocument
  SBOM1
  SBOM2
  Package
]

The data for Package occurs only once, not copied 3 times, while SBOM1 and SBOM2 contain the SPDXID of Package.  SPDXDocument contains no data from other elements, just the four SPDXIDs of the elements in the Payload.  Every element can be serialized as a single element without having any dependency on any other element.
