### ISSUE TITLE
What is the intent for namespaceMap in the model?

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#485]
In recent discussions, multiple benefits of, features of and reasons for namespaceMap in the model were named. I would like to identify the actual ones and would be interested to identify the coresponding stakeholders. 

# Potential Reasons for namespaceMap:

#### It helps reduce the size of serialized blobs
Isn't that solved by gzip and transport compression in protocols like HTTP?
#### They help human readability as the IDs are shortened and the repeated part is dropped

# Some thoughts on the entries above:
#### _R1_ It helps consistency and my minted aliases get reused

example is msft for https://www.microsoft.com

- This only brings benefit if one expects the documents to be read by humans?
- Wouldn't it be better to introduce a public list of recommended aliases and to use that in the provided tools/libraries?

#### _R2_ It was part of SPDX 2.X

- In SPDX2 the serialization was not sufficiently decoupled from the model and it had to be part of the model.
- in SPDX2 tag value there was just a [single value `documentNamespace`](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/examples/SPDXTagExample-v2.3.spdx#L3C20-L3C94), to construct a namespaceMap entry out of that, one would need to create a new key. This is also only encoded in some properties and [the rdf file does not express the namespace](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/examples/SPDXRdfExample-v2.3.spdx.rdf.xml)

#### _R3_ Having it in the model directly allows to communicate them to the serializing tool, like an API

- The namespaceMap are just hints and the serialization can choose to do other things
- as discussed in https://github.com/spdx/spdx-3-model/issues/482 it has advantages to give the serialization the choice of mapppings

**Comment by goneall** [comment]
From the [SPDX Tech Call on 2023-08-08](https://github.com/spdx/meetings/blob/main/tech/SPDX%20Tech%20Team%20Meeting%202023-08-08.md): "Agree we need to preserve roundtripping and conversion between formats, as well as linkage between elements located in different collections." as it relates to namespaces.

**Comment by maxhbr** [comment]
> ... linkage between elements located in different collections.

isn't the linkage via IDs which are not shortened? The namespaceMap should not play any role here?

> Agree we need to preserve roundtripping and conversion between formats ...

That would be R1

**Comment by goneall** [comment]
> > Agree we need to preserve roundtripping and conversion between formats ...
> 
> That would be R1

I interpreted R1 to be much broader than just round tripping - the example given would apply even outside SPDX.  Personally, my focus is just the round tripping which can be solved by either approach - in the model or in the serialization spec.

**Comment by goneall** [comment]
@maxhbr - can this be closed?

**Comment by goneall** [comment]
@maxhbr I'm going to close this - if you feel it needs to be addressed, please open a new issue or PR with specific suggestion
