### ISSUE TITLE
Alternative proposal for namespaceMaps

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#489]
add a new Element to the Model, that describes a serialized artifact.

# Data it contains

- It encodes the `NamespaceMap`
- It points to the elements which are serialized in the element (like a collection)
- It might also contain
  - name of the file
  - hash of the file

# semantics
- when deserializing, this element is minted on the fly
  - the NamespaceMap is filled from the actually used namespaces
- when serializing, one can optionally provide this as a description what and how it should be serialized, but it is not written itself to the generated output

**Comment by goneall** [comment]
Since we made a decision on the namespaceMaps, I'm closing this issue to avoid confusion.
