### ISSUE TITLE
Missing DataType DictionaryEntry

### ISSUE THREAD

**Issue by nishakm** [spdx/spdx-3-model#494]
The build profile uses `DictionaryEntry` in a couple of places, but there is no definition for `DictionaryEntry`. Should we add it?

**Comment by zvr** [comment]
It is defined in https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/DictionaryEntry.md

**Comment by nishakm** [comment]
My bad. I thought it was a DataType. I'll close this issue
