### ISSUE TITLE
documentDescribes relationship overlaps with rootElement

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#495]
Also in the diagram, it states it is from a "bundle" to an Artifact which is inconsistent with the description.

The description of documentDescribes:

`Every to Element is described by the from Element. This can be used to denote the root(s) of a tree of elements contained in an SBOM.`

The description of rootElement:

`A rootElement of a collection is the top level Element from which all other Elements are reached via relationships.`

**Comment by maxhbr** [comment]
I think we should specify, that `rootElement` is a purely technical property that is used for finding all nodes on the graph by highlighting the elements from which one should start traversing relationships and other edges.

And the `documentDescribes` is the intent of the document, which might or might not overlap with the roots.

**Comment by goneall** [comment]
On the tech call 3 October, 2023 we tentatively agreed that we would have only one property to describe the root elements and intent of the serialized document.  We will finalize the decision on our 7 Oct. call.
