### ISSUE TITLE
Serialization: NamespaceMap, Solutions A and B, and Playground use cases

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#499]
It's a bit confusing to understand a PR against a PR, but since #491 has been merged into #490 and closed, this issue keeps a pointer to #491 alive to preserve the discussion.

**Comment by goneall** [comment]
I added a link the PR itself: https://github.com/spdx/spdx-3-model/pull/490#issuecomment-1792864548

I think we can close this issue since they are linked.
