### ISSUE TITLE
Serialization Flow Diagrams

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#518]
Thanks to @sbarnum for recognizing that the serialization team members still have different understandings of various proposals despite intense focus on the logical model, that flow diagrams could bring additional clarity and speed agreement, and for producing the first such diagram.

This is the "proposal 5" physical-centric flow.  It treats logical elements as content to be serialized into physical `payloads` in accordance with a serialization specification/binding for each data format, independently of any logical `serializable collections` that may be defined as additional content.  It clarifies PR #431 with respect to physical document without imposing any constraints on logical document / X-Collection.

A `payload` is a byte sequence containing header (non-element) properties and element content as defined by the [Payload](https://github.com/spdx/spdx-3-model/pull/500/files?short_path=d341b0a#diff-d341b0aa4eedac78681f49bf7f00dc773d9d84c80f834ae1c6e06da8250ed205) type proposed in PR #500.  Using the Build team [example](https://github.com/spdx/spdx-3-serialization-prototype-playground/blob/main/implementations/4/example.png), OpenSSL is the innermost contained package, the OpenSSL `Producer` would perform steps 1 and 2 (serialize the payload) and be done.  Any consumer of the OpenSSL SBOM would perform step 3 (parse the payload) and be done, unless they went on to produce other payloads that reference elements from an OpenSSL payload as shown in steps 4-6.

Any Producer (such as Alpine) that includes copies of all referenced elements from multiple sources within a single payload is done after steps 1 and 2.  The remaining steps are performed only if some referenced elements are external to the payload.

Logical document / serializable collection elements shown after step 6 may be created by the original producer or by a third party but do not affect the serialization/parsing process.

![SPDX-PhysicalDocument](https://github.com/spdx/spdx-3-model/assets/19152940/84919ae0-f1c0-4a4d-a1c1-d20671b50163)

**Comment by nishakm** [comment]
In Step1, what does "Document Header" mean?

**Comment by nishakm** [comment]
Here's a somewhat equivalent Sean diagram: https://drive.google.com/file/d/1gAT-N0NJuqVuQTxa1MfcPa1Ck5rIogdQ/view?usp=sharing

**Comment by davaya** [comment]
> In Step1, what does "Document Header" mean?

The serialized XML or JSON data contains per-document content properties (like NamespaceMap, rootElement and possibly dataLicense) and elements.  The document has "header properties" and a "body" that is the element values.  See Payload.md in PR #500.

**Comment by davaya** [comment]
This is exactly Nisha's diagram mapped to the corresponding steps in David's diagram.  The producer starts with information to be serialized in Step 1, serializes it into multiple data formats in Step 2, and parses it back to the identical information in Step 3, equivalent to Nisha's Step 7.

The SerializedElements processing and creation of relationships between SerializedElements and Artifacts is Nisha's Step 4 and David's Step 4, but by then the parsing is already finished.

https://app.diagrams.net/#G1D2su7AZAyYvZngzeGQ1C0gxubLlXSdZD

![SPDX-flow-nisha-david-Sean drawio](https://github.com/spdx/spdx-3-model/assets/19152940/f3e932df-e98c-4ce2-aac5-62ee06f7ef2d)

**Comment by goneall** [comment]
There's some really good documentation in this issue.  I'm going to mark this as a documentation issue to note that we should document this in the serialization repo somewhere to represent the current decision / solution.

Targeting for 3.0 after RC2.

**Comment by JPEWdev** [comment]
I think extra diagrams for serialization are probably not necessary in this form. There are I think 3 "levels" of users who will be attempting to serialize SPDX. The first level are users who have no experience at all and "just want to write a document". For these users, these diagrams are not helpful. Instead, a more long form guide to introduce the concepts of SPDX serialization in a concrete form (e.g. https://github.com/spdx/spdx-3-serialization-prototype-playground/blob/main/jsonld/GETTING_STARTED.md) is likely going to be the most useful.

The next is users who understand the basic concepts of SPDX, and want to write documents with more complexity and features than the guides above can cover. For these users, inline examples of the various classes, properties in the documentation itself are _extremely_ helpful as these users know where to look, but not exactly what the need to do to encode documents.

Finally the users that are very familiar with the SPDX spec and how it is serialized can usually read about a given class/property/vocab and be able to translate it in their head to a serialized form. For these users, the existing SPDX documentation is mostly sufficient.

**Comment by goneall** [comment]
Agree with @JPEWdev - if no one disagrees after the next serialization meeting, I'll close

**Comment by kestewart** [comment]
Discussed on tech call, with Joshua & Nisha,  and agree it can be closed.
