### ISSUE TITLE
Add "disk-image" and "filesystem" to SoftwarePurpose

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#525]
In the embedded world, it is common to produce complete disk images (e.g. root filesystem, Linux kernel, bootloaders, etc.) that can be flashed to e.g. internal flash or an SD card to boot a device. This use case doesn't seem to be quite captured by the current SoftwarePurpose; the closest is probably `firmware`, but this is specific to low level hardware firmware, so not quite appropriate for something that also contains userspace.

Similarly, a filesystem image is also often produced where it contains the userspace (and possibly also the bootloader and/or kernel) that can be written to a partition.

**Comment by goneall** [comment]
@JPEWdev - OK to have this as a 3.1 milestone or should we add this to the RC3 milestone list?

**Comment by bact** [comment]
Both of them are already in [SoftwarePurpose entries](https://github.com/spdx/spdx-3-model/blob/main/model/Software/Vocabularies/SoftwarePurpose.md), from PR #554 and released with 3.0-rc2 

- `diskImage`: the Element refers to a disk image that can be written to a disk, booted in a VM, etc. A disk image typically contains most or all of the components necessary to boot, such as bootloaders, kernels, firmware, userspace, etc.

- `filesystemImage`: the Element is a file system image that can be written to a disk (or virtual) partition

**Comment by JPEWdev** [comment]
Closed by #554
