### ISSUE TITLE
Allow ElementCollection to contain 0 elements

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#526]
Currently, the minimum count for the `element` field of `ElementCollection` is 1. This means that any time a producer want to return no elements to a consumer, it must do so using and out-of-band mechanism, which is annoying for implementation.

For example, imagine a server that implements a query API and returns the elements that match the query in an `ElementCollection`. Currently, if you provided a query that doesn't match any elements, the server cannot return an empty `ElementCollection` to indicate this and instead must implement some other out-of-band mechanism to tell the clients that no elements match the query, even though this is likely not really an error.

**Comment by goneall** [comment]
+1 on changing the cardinality - the logic presented makes sense to me.

**Comment by maxhbr** [comment]
how does that interact with `rootElement`? Will we specify that at least `rootElement` is mandatory as soon as the collection contains an element?

**Comment by goneall** [comment]
In the serialization team, we discussed having serializations that are not wrapped in an `ElementCollection`.  In that case, all elements would be considered root elements.

We could take the same approach with the `rootElement` property.  Change the cardinality to `0..1` and add text that if there is no root element specified, then all elements in the collection are considered root.

**Comment by JPEWdev** [comment]
I think it would need to be `0..*` as multiple root elements are currently allowed (and I think makes sense per our discussion on Tuesday), but otherwise I think that makes sense
