### ISSUE TITLE
Document that minimum of 0 in `Relationship.to` is on purpose

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#527]
The `to` field of the `Relationship` class has a minimum of 0, which is to allow producers to indicate that there are no known relationships of the given type. This makes sense, but should be documented as it is not clear why you would have a relationship that doesn't go anywhere.

**Comment by kestewart** [comment]
In https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/Relationship.md it is explicit that minCount: 0. 
to
type: Element
minCount: 0

was already there. 

Went in and added: https://github.com/spdx/spdx-3-model/pull/623 today, which should wrap it up.

**Comment by kestewart** [comment]
Closing this as resolved in earlier PRs.
