### ISSUE TITLE
ExpandedLicensing `License` Class has weird property name

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#530]
The `License` class in ExpandedLicensing has a field named `/SimpleLicensing/licenseText`. This means that in the actual JSON encoding, it looks like:

```json
{
  "type": "License",
  "/SimpleLicensing/licenseText": "The text"
}
```

Which seems like it is unintentional

**Comment by zvr** [comment]
It's intentional, this is the case of a class in a namespace using properties from another namespace.

I'm not sure about your point on the JSON encoding. Are you saying that the currently generated JSON-LD schema does not provide a "shorthand" for the property?
