### ISSUE TITLE
All relationshipType descriptions should explicitly state `from` and `to`, or clearly indicate they are directionless

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#533]
It should be unambiguous when reading the description of a relationshipType what the direction is. Some of the descriptions do a good job of this, but some do not. All of the descriptions should explicitly state the direction using the terms `from` and `to`, or explicitly state they are directionless.

As an example, this description is clear and unambiguous about the direction:

* contains: Every `to` Element is contained by the `from` Element

Whereas this one is ambiguous:

* descendant: This relationship may be used to describe child builds of a Build instance.

And yes I realize the irony that I helped write the latter :)

**Comment by zvr** [comment]
I am strongly in favor of this!

I would also go further: mention what classes are valid for `from` and `to`, if there are restrictions that can be expressed easily.
