### ISSUE TITLE
json-ld context seems to currently be invalid (reported by rdflib)

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#539]
The context currently found in [gh-pages branch](https://github.com/spdx/spdx-3-model/blob/ed5754252580c8cf29c0042018caf7bec2e402e0/context.json) is reported by the [rdflib](https://rdflib.readthedocs.io/en/stable/) of python to be an invalid context. A test to validate that is proposed to be added via #538 

This needs to be fixed in the spec-parser, which generates this file.

ping @zvr

**Comment by zvr** [comment]
ok, closing this to leave #531
