### ISSUE TITLE
The JSON-LD Example contain a link to the context which does not match its actual location

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#540]
The JSON-LD examples contain the following context reference: 

https://github.com/spdx/spdx-3-model/blob/6b45815e2fe1d49b5242038b4c4667ede6baf5f6/serialization/json_ld/examples/agent1.json#L1-L2

but it is actually located at https://spdx.github.io/spdx-3-model/context.json. Which one should be its actual location?

**Comment by goneall** [comment]
I think we should change it to the current location https://spdx.github.io/spdx-3-model/context.json

Once we release the 3.0 spec, the location will likely change again - but for now, let's use the current generated context in the examples.
