### ISSUE TITLE
Add hasInputs relationship

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#544]
The current `inputOf` relationship has a high fan out from the artifact to the Build, allowing one artifact to be the input to multiple builds (although, this might be ambiguous, see #534). However, when constructing Build its also very likely easier to indicate that a given build has multiple inputs instead. As such, add a new `hasInputs` relationship that indicates that a `from` Build has artifacts `to` as it's inputs.

**Comment by kestewart** [comment]
This relationship is in https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/RelationshipType.md
from earlier PRs from Joshua.   
hasInputs: The from Build has each to Elements as an input during a LifecycleScopeType period.

Marking this closed.
