### ISSUE TITLE
Serialization: lists of constants

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#56]
The element "profile" property is a list of profile names, e.g., "core", "software", etc.

The conventional way of serializing a list of string values is as a list:
```
  "profile": ["core", "software"]
```
It has been suggested to instead require all list items to be serialized as objects with repeated constant property names:
```
  "profile": [
    {
      "name": "core"
    },
    {
      "name": "software"
    }
  ]
```
**Proposal:** Serialize lists with their actual values (e.g., IRIs, enumerations such as profile name, SoftwarePurpose, etc. rather than injecting an artificial object wrapper around those values.

Rationale: an object wrapper makes serialized data both more verbose and more difficult to read.  But more importantly, the extra data provides no information - the receiver knows nothing more after seeing it than it does without seeing it.  Proof: a receiver, after receiving the native list, has everything it needs to locally transform it into the list of objects if that format is needed for some reason.

**Decision:** ?

**Comment by maxhbr** [comment]
Although I would prefer the "conventional way", profiles are expected to get versioned, which is possible with objects without a breaking change:
```
  "profile": [
    {
      "name": "core",
      "version": "3.0.1"
    }
  ]
```

**Comment by davaya** [comment]
Every Element has its own specVersion; I'm not sure what applications would be expected to do with specVersion 3.2.0, profile core 3.1.2, software 3.0.5.

Of course lists are a general case, not just versioning.  But if there were a use case for separately-versioned profiles they could be  serialized as:
```json
  "profile": {
    "core": "3.1.2",
    "software:": "3.0.5"
  }
```

The general case is described in #55 - do you serialize email headers with lists of repeated [ {name: x1, value: y1}, {name: x2, value: y2}, {...} ] pairs or with normal object properties {x1: y1, x2: y2, ...}?

**Comment by maxhbr** [comment]
> Of course lists are a general case, not just versioning. But if there were a use case for separately-versioned profiles they could be serialized as:

yes, that would be possible. But that would still be a breaking change to your initial proposal. So, this does not help to avoid the breaking change in the "there might or might not be a future with individual versions"-Problem.

**Comment by maxhbr** [comment]
> Every Element has its own specVersion; I'm not sure what applications would be expected to do with specVersion 3.2.0, profile core 3.1.2, software 3.0.5.

+1 from me, I also think that this is not a future to hope for. Maybe we can decide that it will not come. This would solve this thread.

**Comment by davaya** [comment]
Enumerated values are not properties.  The SPDX model would need a breaking change to accommodate versioned profiles.

**Comment by maxhbr** [comment]
Profile identifiers are structs with just a name at the moment, not enums:
![2023-01-30_15-33-10](https://user-images.githubusercontent.com/1187050/215505814-a321aa85-e95f-482f-9063-5bc1a48e5379.png)

**Comment by davaya** [comment]
I'm not sure how to interpret that model notation - ProfileIdentifier is clearly not enumerated (my mistake), but it cannot be simultaneously a string and an object.

**Comment by maxhbr** [comment]
Just found https://github.com/spdx/meetings/blob/f9e1bbe608d5f2b9b6f8bd9be26f9520339c22c5/tech/2022-10-04.md?plain=1#L55-L56:

> * Proposal 2 - Remove the version from profiles, profiles will always be released in lock step with the SPDX spec.  Implication, changing this would be a breaking change - so we are essentially deciding that profiles and specs will be release together until at least 4.0 (which allows breaking changes)
> * Decision: Proposal 2 - remove version from profiles

the versions of profiles will not come back before 4.0. So my assumption in that case was wrong and I would obviously also choose the simple serialization.

**Comment by kestewart** [comment]
Have submitted https://github.com/spdx/spdx-3-model/pull/249 this will be a bit more "automation friendly" than an arbitrary string, which is what it was set to, and should address @davaya comments about not having any value "Food", etc. 
Will close this, but feel free to reopen if you disagree.
