### ISSUE TITLE
Should cardinality of Core/Annotation/contentType be 0..* as in current spec or 0..1 as in previous model diagram?

### ISSUE THREAD

**Issue by sbarnum** [spdx/spdx-3-model#565]
This question was raised in the Dec 5th, 2023 Tech call and there was not universal consensus on the answer.

**Comment by goneall** [comment]
Decision on 2 Jan tech call:
- Keep at `0..1` as is currently documented

Reason: if we want to change to `0..*` it would be backwards compatible.  If we went with `0..*` and decided later it should be `0..1`, it would be a breaking change.

Also, `File` has a a `MediaType` field with a cardinality of `0..1`.

Statement also has a `0..1`.
