### ISSUE TITLE
The "begin" and "end" properties on PositiveIntegerRange are far to generically named and will almost certainly cause semantic collision. They need renamed something more specific.

### ISSUE THREAD

**Issue by sbarnum** [spdx/spdx-3-model#567]
The PositiveIntegerRange class currently defines an integer range using a "begin" and an "end" property both of datatype positiveInteger.
These names are far to generic for use within the model.
The concept of 'begin' and 'end' could be desired/needed to characterize time windows, substrings, memory regions, etc.
Any other use would conflict with the current properties given their specific typing.
To avoid such semantic collisions these two properties should simply be renamed "beginIntegerRange" and "EndIntegerRange".

**Comment by goneall** [comment]
Agree - @sbarnum - could you create a PR?
