### ISSUE TITLE
The "issuingAuthority" property on the ExternalIdentifier class should be of type String rather than anyURI.

### ISSUE THREAD

**Issue by sbarnum** [spdx/spdx-3-model#568]
The "issuingAuthority" property on the ExternalIdentifier class is currently typed as anyURI.
However many if not most issuing authorities for concept identifiers are likely to be general strings such as organization names (IETF, NIST, etc.) rather than URIs.
Changing the type of "issuingAuthority" to String would solve for the general case and also support specifiying URIs as strings.
This type should be changed to String in the spec.

**Comment by goneall** [comment]
Agree

**Comment by goneall** [comment]
Additional context - here's the meeting minutes where this was added: https://github.com/spdx/meetings/blob/main/tech/2023-04-25.md

I didn't see any references to why we choose IRI.

**Comment by bact** [comment]
It is from point 3 in the meeting minutes, at the very end:

```
DECISION: ok to add to /Core/ExternalIentifier two properties: identifierLocator: IRI[0..*] issuingAuthority: IRI[0..1]
```
