### ISSUE TITLE
Defined string constraint for MediaType simple data type should reference RFC2046 rather than RFC6838.

### ISSUE THREAD

**Issue by sbarnum** [spdx/spdx-3-model#569]
The string constraint for the MediaType simple data type was originally specified as conformance to RFC2046 (the IETF standard for Media Types).
At some point it was changed to be conformance to RFC6838 (the IETF standard for Media Type Specifications and Registration Procedures).
RFC6838 is a procedural standard rather than a structural or representation standard like RFC2046 is.
RFC6838 is NOT intended to cover the same ground as RFC2046 or replace it in any way.
RFC6838 is a relatively new standard (published Jan 2023). It does describe how to specify new media types to support intended registration. However, the format constraints of RFC6838 are narrower than RFC2046 meaning that defining the MediaType simple data type in SPDX 3.0 as conformance to RFC6838 would invalidate many existing media types that are conformant to RFC2046 but not to RFC6838.

RFC2046 is the appropriate standard to conform to for the intended purpose of the MediaType simple data type in SPDX.

**Comment by goneall** [comment]
Good catch - agree we should keep this compatible.
