### ISSUE TITLE
Should cardinality of Core/ExternalRef/locator property be 0..* as defined in the current spec or 1 as contained in the previous version of the model diagrams?

### ISSUE THREAD

**Issue by sbarnum** [spdx/spdx-3-model#570]
This question was raised in the Dec 5th, 2023 Tech call and there was not universal consensus on the answer.

**Comment by sbarnum** [comment]
I would vote for 0..*

I think this is more realistic and practical.

**Comment by goneall** [comment]
Discussed on SPDX Tech call 30 Jan 2024.  Agreed to keep it optional.  External Identifiers have a required identifier which satisfies the vulnerability correlation use case.  In the future, we can subclass ExternalRef and create additional restrictions on the locator if we want/need.
