### ISSUE TITLE
There is still lack of consensus on the appropriate location, cardinality and type of the dataLicense property in Core

### ISSUE THREAD

**Issue by sbarnum** [spdx/spdx-3-model#572]
Previous discussion and consensus led to a decision to place the "dataLicense" property on the SpdxDocument class however it still also exists on the CreationInfo class.
This issue was discussed very briefly on the Dec 5th, 2023 Tech call and rough consensus seemed to be that it should stay on SpdxDocument and be removed from CreationInfo but the decision whether or not to remove it from CreationInfo needs formal approval.

We currently lack formal consensus on the appropriate cardinality for the dataLicense property (on SpdxDocument and potentially on CreationInfo). The current spec defines the cardinality as 0..* but the previous model diagram defined it as 1. Which is correct?

The current spec defines the dataLicense property on SpdxDocument as of type AnyLicenseInfo whereas it defines the dataLicense property on CreationInfo as of type String.
This issue was discussed very briefly on the Dec 5th, 2023 Tech call and rough consensus was that the String form was a historic artifact and that it should be AnyLicenseInfo but there was not universal consensus and it was decided to discuss it on an Issue here.

**Comment by goneall** [comment]
This is dependent on resolution of https://github.com/spdx/change-proposal/issues/8

**Comment by goneall** [comment]
For RC2, I suggest we go with the the updates in PR #586 which uses a `dataLicense` on `SpdxDocument` with a cardinality of `0..1` and a type `AnyLicenseInfo`.

We can revisit before 3.0 release.

Moving to the 3.0 milestone.

cc: @swinslow @jlovejoy

**Comment by goneall** [comment]
Reviewed on tech call on 5 March 2024, no objections to the current state - closing
