### ISSUE TITLE
ExpandedLicensing profile/namespace specifies two individuals (NoAssertionLicense and NoneLIcense) as of type AnyLicenseInfo which is invalid since AnyLIcenseInfo is abstract

### ISSUE THREAD

**Issue by sbarnum** [spdx/spdx-3-model#574]
The two individuals (NoAssertionLicense and NoneLIcense) need to be redefined as instances of a concrete subclassof AnyLicenseInfo.

**Comment by goneall** [comment]
@sbarnum good catch.  Do you have a suggested solution?  Should we create one concrete class for the individuals?  What should we name this class?

**Comment by swinslow** [comment]
I'm good with the approach @goneall proposed in #588, with just a couple of questions I noted in that PR thread.

**Comment by zvr** [comment]
Just to note that "abstract/concrete" was something we added to the model for our own convenience.

There are no such things as "abstract" classes in RDF or OWL.

Since this is the only case, for the handling of two unique "individuals" (instances) of None and NoAssertion, my proposal would be to simply let it be. We can have the individuals and they can be AnyLicenseInfo.

**Comment by goneall** [comment]
> Just to note that "abstract/concrete" was something we added to the model files for our own convenience.
> 
> There are no such things as "abstract" classes in RDF or OWL.
> 
> Since this is the only case, for the handling of two unique "individuals" (instances) of None and NoAssertion, my proposal would be to simply let it be. We can have the individuals and they can be AnyLicenseInfo.

Good point - I'm OK leaving it as is.

@sbarnum - are you OK with the current state?

**Comment by sbarnum** [comment]
While @zvr is correct that the concept of "abstract/concrete" classes do not formally exist in RDF or OWL, we have been using this concept in our model/spec to convey which classes should be instantiated and which should not.
Simply leaving things as they are with Individuals formally defined as instances of classes we have marked as abstract would likely confuse things especially around how to then interpret Artifact and ElementCollection which are also specified as Abstract.

I think there is a very simple solution to this issue which I have outlined in a comment on #588
