### ISSUE TITLE
Resolve IRI base used for RDF

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#601]
SPDX 2.3 IRI's for the RDF vocabulary is `http://spdx.org/rdf/terms`.

The files in the SPDX 3.0 model consistently use `https://rdf.spdx.org/v3` as the base.

There is no current subdomain or redirect in the spdx.org domain to allow us to provide documentation for the IRI base.

Although there is no requirement that the base point to online documentation (it only has to be unique) having such documentation is extremely convenient.

We should either work with LF IT to give us a way of adding documentation to `https://rdf.spdx.org/v3` or change the base IRI to something we have current access to (e.g. `https://spdx.org/rdf/terms/v3`).

**Comment by JPEWdev** [comment]
While nice to have, I don't think this is a blocker for 3.0

**Comment by goneall** [comment]
Since changing the IRI would be a breaking change, we should make sure we have a supportable IRI in before the 3.0 release.  Fixing up the website itself can be done later.

**Comment by goneall** [comment]
Decision on 2 April 2024 tech call:
- Prefix: https://spdx.org/rdf/3.0.0/terms/[profile namespace]/[class or property name]
