### ISSUE TITLE
Fix generation of RDF/SHACL and JSON-LD context

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#608]
The current changes to spec-parser caused us to drop generation of all outputs. This means that we no longer have an up-to-date context. Without a matching context file, there is currently no feasible way to serialize a valid json-ld file for the latest state of the model. 

This is also important for using https://github.com/JPEWdev/shacl2code/tree/main.

As we have a stale and outdated context in https://github.com/spdx/spdx-3-model/blob/gh-pages/context.json, it would be good to identify the commit in the model to which it is consistent so that we can point implementers to a consistent state.

**Comment by goneall** [comment]
I believe this is now fixed with merging of https://github.com/spdx/spdx-spec/pull/893

@maxhbr - if you disagree, please open or reopen a PR
