### ISSUE TITLE
How to add profile data to an existing SBOM or Element

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#61]
This scenario came up in the Asia SPDX tech call on Jan 9, 2023.

An entity which is in the middle of a software supply chain receives an SPDX document and wishes to add profile information (e.g. the Build profile) before passing the information on to downstream consumers.

In SPDX 2.X, you would produce an SPDX Document which has an `AMENDS` relationship to the supplied SPDX document.

Since each element has creator information and can be independent of the Document, I would like to document the best practice for this scenario.

A proposal would be that each Element (be it a Package, SBOM, File, etc.) would be updated in the new document with the Profile information.  The Profile would also be added to the Creator information for the element.  An `AMENDS` relationship would be added from the new Element to the previous Element using the ExternalMap to reference the previous Element.

There are a couple of downsides to the above proposal:
- It is difficult to tell exactly what has changed, you would essentially need to "diff" the Elements
- You end up copying all the information from one element to another

I'm open to any other proposals or variations on a theme.

Below is an example:

Original Supplier element:
```
{
  ...
  "elements": [
    "@type": "Package",
    "@id": "urn:originalsupplier.org:packagea#elementid",
    "creationInfo": { ... "profile": ["core", "software"] ...
    "name": "myPackage"
    ...
    ],
   ...
}
```

Intermediate supplier element
```
{
  ...
  "externalMap": [{"elementId": "urn:originalsupplier.org:packagea#elementid"}],
  "elements": [
    "@type": "Package",
    "@id": "urn:intermediateSupplier.org:packagea#uniqueid2",
    "creationInfo": { ... "profile": ["core", "software", "build"] ...
    "name": "myPackage",
    "buildDate": "2022-12-13T18:36:37.793Z",
    ...
    ],
   ...
}
```

**Comment by davaya** [comment]
This solution assumes that multiple inheritance is allowed: Package is defined in the Software profile but the Build profile can add properties to it.

An alternate solution would allow only single inheritance: the Build profile defines a BuildPackage type that contains just properties relevant to Build, including a required "sourcePackage" property that points to the original supplier package.  That eliminates 1) multiple inheritance, 2) an extra AMENDS relationship element, and 3) duplicate properties in both original and build elements.

**Comment by kestewart** [comment]
https://github.com/spdx/spdx-3-model/pull/249 resolves this.   Closing.   Please open a new issue if you spot additional concerns.
