### ISSUE TITLE
Type mismatch in ExpandedLicensing

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-3-model#612]
I've added new tests in spec-parser to check that the type of properties appearing in classes matches the range in the property itself.

One error was raised:

> ERROR: In class /ExpandedLicensing/WithAdditionOperator, property subjectLicense has type ExtendableLicense but the range of /ExpandedLicensing/subjectLicense is License

**Comment by goneall** [comment]
Thanks @zvr for catching this.

I created PR #613 to fix.
