### ISSUE TITLE
Resolve how IDs are handled for individuals

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#624]
In the discussion for PR #588 there were 2 approaches proposed for creating and managing the IDs for RDF Individuals:

- Generate in a similar fashion to the classes and property IDs
- Explicitly state as a field in the markdown file - Note: this would require changes to the spec-parser to validate

**Comment by zvr** [comment]
Both are being handled:
- an automatic IRI is generated always, and,
- a specific IRI may also be specified.

If there is a specific one, the RDF also contains a `owl:sameAs` between the two.

**Comment by goneall** [comment]
Thanks @zvr 

This looks to be resolved - I'll go ahead and close it.
