### ISSUE TITLE
Add in type of "support level" 

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-3-model#627]
One of the gaps that has been highlighted, is not say the state of what is "ValidUntil" for an artifact.
There was an implicit semantic of end of life/end of support,   but from consulting the guidance from
the FDA, it's more appropriate to make this a bit more nuanced. 

In discussions with the AI & Dataset profile working groups, this concept makes sense to carry forward
into those profiles as optional property,  so it is appropriate to move into core.    
From the discussion on the call, we landed on: 

Field Name: "SupportLevel"

Enumerated SupportTypes: 
  * Development
  * Support
  * LimitedSupport
  * EndOfSupport (aka End of Life)
  * NoSupport (Use as Is)
  * NoAssertion **default of nothing specified**
  
Recommendation is to describe any relevant support details in package comments, beyond the enumeration.

**Comment by goneall** [comment]
Fixed with #628
