### ISSUE TITLE
missing Instantiability

### ISSUE THREAD

**Issue by NorioKobota** [spdx/spdx-3-model#641]
missing Instantiability in some classes.
https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/Hash.md
https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/PackageVerificationCode.md
https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/File.md
https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/Package.md
https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/Sbom.md
https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/Snippet.md
It doesn't appear in Ontospy, but is this a necessary parameter?

**Comment by zvr** [comment]
No need to have the `Instantiability` metadata in every file, the default is `Concrete` and gets added when the spec is generated.

**Comment by goneall** [comment]
@zvr Since this has been answered, should we close this issue or should we create a PR to update the documentation?

**Comment by zvr** [comment]
I'm closing this.

"Documentation" on the input format is sorely missing; something I'm planning to work on now that both the format and the processing tool are mostly stable.
