### ISSUE TITLE
Update PackageVerificationCode to have algorithm explicit

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-3-model#646]
In https://github.com/spdx/spdx-3-model/pull/643 the PackageVerificationCode model had the algorithm, but the text for the class had it hardcoded as SHA1.   The model was updated to match, but the algorithm should be put back into the diagram & the description of packageVerificationCode rewritten to include use of algorithms other than SHA1.

**Comment by kestewart** [comment]
Need PVR to be added to HashAlgorithm (in model and diagram).

**Comment by kestewart** [comment]
<img width="623" alt="Screenshot 2024-03-28 at 11 04 03 AM" src="https://github.com/spdx/spdx-3-model/assets/13152682/888e6ed0-a775-4ff5-827b-f5c60b950587">

Need to get example to see how this is able to express with different HASH algorithms - @sbarnum can you help here

**Comment by kestewart** [comment]
DIscussion from the call,  preference is to replicate algoirthm in PackageVerificaitonCode.

PR will be submitted.

**Comment by goneall** [comment]
Resolved with PR #699
