### ISSUE TITLE
Make LifecycleScopedRelationship & LifecycleScopeType neutral to what they are a lifecycle of

### ISSUE THREAD

**Issue by bobmartin3000** [spdx/spdx-3-model#664]
The Core capabilities should be made neutral with respect to software, hardware, or other kinds of lifecycle so those capabilities can be used by all profiles.
Propose that in LifecycleScopeType: 
- Summary - change "software lifecycle" to "lifecycle"
- Description - change "runtime dependency" to "operational dependency"

and In LifecycleScopeRelationship:
- Summary - change "software lifecycle" to "lifecycle"
- Description - change "software lifecycle" to "lifecycle"

**Comment by goneall** [comment]
Fixed with #665
