### ISSUE TITLE
What is the difference between rootElement and element?

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-3-model#67]
..and how do I determine them correctly? So for example a `SPDXDocument` is a Subclass of `Bundle` which is Subclass of `SpdxCollection`. A `SpdxCollection` has at least one `element` and at least one `rootElement`. If I now try to migrate a `document` from spdx 2.3 into a `SpdxDocument` in spdx 3.0, I would assume that `Packages, Files, Snippets, Relationships` and `Annotations` would be collected in the List of `element` but what is the `rootElement` in that case?

**Comment by seabass-labrax** [comment]
I believe `rootElement` is a left-over from a previous SPDX Tech Team discussion about nested collections of Elements, so I wouldn't lose any sleep about that :smiley:

For 'upgrading' a 2.3 Document into SPDX 3.0, I would suggest creating an `Collection` Element pointing to all of the `Package`, `File`, `Snippet`, `Relationship` and `Annotation` Elements. That `Collection` and the Elements that it points to need not necessarily be serialised in the same file of SPDX data; one of the key aspects of SPDX 3.0 is that all Elements can be independently communicated. The `SPDXDocument` Element, however, is a special kind of Collection which describes a specific, serialised set of Elements.

Another way of describing the difference would be that `Collection` associates Elements by something they have in common (for example, that they are all related to a Linux distribution ISO), whereas `SPDXDocument` associates Elements by how they were serialised together. Hope this helps :smiley:

**Comment by meretp** [comment]
Thanks, that at least helps to understand that I don't need to pay any further attention to `rootElement`. :smile: I would leave this issue open for the time being until the documentation has been adapted.

But one more question about the "upgrade" 2.3 -> 3.0 as I am a bit confused right now. 
Consider the following: I have a serialised SPDX Document 2.3 (let it be a .json file) and want to "upgrade" this to a serialised SPDX Document 3 (also a .json file, assuming there is a definition how to do that). In this case I would use `SPDXDocument`, wouldn't I? 
But if I don't need to serialise the data into one file, I would use a `Collection` not a `Bundle`? Eventhough this is defined as an abstract class which I thought meant it wasn't instantiated directly. Or am I misunderstanding "abstract class" here?

**Comment by iamwillbar** [comment]
> I believe `rootElement` is a left-over from a previous SPDX Tech Team discussion about nested collections of Elements, so I wouldn't lose any sleep about that 😃

This isn't quite correct, let's say I have a document containing the SBOM for "Office", it would have the following elements:
* SBOM
* Package: Office
* Package: Word
* Package: Excel
* Package: Outlook
* ...

On SBOM, the `element` property would list all the `Package` elements that make up that collection (this is true whether there's nesting or not), however, the `rootElement` property would just point to the `Package: Office` property, telling you where to start traversing the relationship hierarchy. This is a generalized version of the `describes package` property on `spdx document` in 2.x: https://spdx.org/rdf/ontology/spdx-2-3/#d4e210.

**Comment by meretp** [comment]
Thanks @iamwillbar for clarification and I see the use case you described. But I have one more question: the field `describes package` isn't required in the rdf ontology, neither in the json ontology nor in the html spec. So I would assume that not every SBOM has a dedicated "entry point" as in your example. The current png and the markdown files for SPDX 3.0 say that a `Collection` should have at least one `rootElement`, this could be a source of error when translating SPDX 2.x documents to SPDX 3.0. Is a `rootElement` really required in SPDX3.0?

**Comment by kestewart** [comment]
@iamwillbar - thoughts?

**Comment by armintaenzertng** [comment]
@iamwillbar: This issue already came up twice in the last week; @meretp`s last comment still stands in my opinion.

I would be happy to mark `rootElement` as optional.
Our current workaround is to put the SpdxId of the Collection itself in there.

**Comment by armintaenzertng** [comment]
Thanks Gary, that makes this part clear!

I have a follow-up question for a general SPDX3 use-case (not for conversion from SPDX2):
* Does this mean that all Elements that are connected to the `SpdxDocument` via a `DESCRIBES` relationship should be included in `rootElement`?
* Does every Element in `rootElement` need to be related via a `DESCRIBES` relationship to the `SpdxDocument`?

If yes to the above, we would have duplicated information which are highly probable to diverge.
If no, what is the difference between `rootElement` and the list of all Elements that are related to the `SpdxDocument` via a `DESCRIBES` relationship?

**Comment by goneall** [comment]
> Does this mean that all Elements that are connected to the `SpdxDocument` via a `DESCRIBES` relationship should be included in `rootElement`?

I would say - yes - specifically "should" not "must"

> Does every Element in rootElement need to be related via a DESCRIBES relationship to the SpdxDocument?

This one isn't a clear to me, but I'm thinking no.  In fact, I wonder if we should deprecate the `DESCRIBES` relationship in favor of using the `rootElement`.

**Comment by goneall** [comment]
Kate's working through the relationships for 3.0 - we'll add this to the list.

**Comment by goneall** [comment]
@kestewart - can we close this issue?

**Comment by kestewart** [comment]
We'll need to have DESCRIBES for use cases, other than those with a "root element", so keeping both makes sense.

**Comment by goneall** [comment]
`rootElement` is now optional - we'll go ahead with the above optional mapping of `DESCRIBES` relationships in SPDX 2.3 to the rootElements and reccomended.
