### ISSUE TITLE
[3.1] AI: Add inferenceEnergyConsumption and totalEnergyConsumption

### ISSUE THREAD

**Issue by bact** [spdx/spdx-3-model#676]
Per discussion in https://github.com/spdx/spdx-3-model/pull/671#discussion_r1534622099 with @bennetkl, also related to #677 and #682, the next version of `energyConsumption` may also include the energy consumption at the inference time.

It is also possible to include the estimation of the energy consumption for the entire life cycle of an AI system.

This issue will be use to collect
- Definitions
- Estimation methods
- Links to relevant technical/legal requirements or documents

## Proposed properties and descriptions

A free-form text that captures the amount of energy needed to train and operate the AI model.

- `trainingEnergyConsumption` for energy consumption during the training of an AI model
  - Training energy consumption is the amount of energy consumed during the training phase of an AI model. This includes the energy used to power the hardware and software systems used for training, such as GPUs, CPUs, and data centers.
  - Renamed from `energyConsumption` #677
  - [EU AI Act](https://www.europarl.europa.eu/meetdocs/2014_2019/plmrep/COMMITTEES/CJ40/AG/2024/02-13/1296003EN.pdf) refs: see Points (2)(d) and (2)(e) in Annex IXa Section 1 and Point (c) in Annex IXc

- `inferenceEnergyConsumption` for energy consumption per one inference
  - Inference energy consumption is the amount of energy consumed per one inference of an AI model. This includes the energy used to power the hardware and software systems used for making predictions or decisions based on the model, such as edge devices, servers, or cloud services.

- `totalEnergyConsumption` for energy consumption during the entire life cycle of the system
  - Total energy consumption is the total amount of energy consumed by an AI model over its entire lifecycle, including training, inference, and any other related activities.

**Comment by bact** [comment]
Another way to record the energy consumption is to record the compute (FLOPs and FLOPs per second)
https://epochai.org/blog/estimating-training-compute 
https://blog.montrealanalytics.com/predicting-and-reducing-energy-consumption-of-machine-learning-models-7dc44e197225

**Comment by bact** [comment]
AI team meeting 2024-04-03 agrees to change `energyConsumption` property range from `xsd:string` to a `EnergyConsumption` class. 

The `EnergyConsumption` class will have these properties: `trainingEnergyConsumption`, `finetuningEnergyConsumption`, `inferenceEnergyConsumption` - all with `EnergyConsumptionDescription` type.

`EnergyConsumptionDescription` will contains a unit information. The unit will have a type of`EnergyConsumptionDescriptionUnitType`.

See:
- #694
- #695
- #696
- #697

**Comment by bact** [comment]
Update: will be in 3.0

See these PRs:
- #694
- #695
- #696
- #697

**Comment by kestewart** [comment]
Was included in https://github.com/spdx/spdx-3-model/pull/648 to avoid breaking change in future.

**Comment by bact** [comment]
From 2024-04-10 meeting:

Hugging Face model card has a carbon footprint information:
- https://huggingface.co/docs/hub/model-cards-co2

This could compliment the energy consumption. For 3.1?
