### ISSUE TITLE
[3.0] AI: Rename: energyConsumption to trainingEnergyConsumption

### ISSUE THREAD

**Issue by bact** [spdx/spdx-3-model#677]
From its description, the `energyConsumption` is intended for being a training energy consumption.

This is confirmed by a conversation here https://github.com/spdx/spdx-3-model/pull/671#discussion_r1535291356

The proposal is to rename `energyConsumption` to `trainingEnergyConsumption` to make it more explicit.

This is also to avoid conflict and make rooms for possible future properties like `inferenceEnergyConsumption` and `totalEnergyConsumption` (see #676).

**Comment by bact** [comment]
Do we need a suggested unit here?

**Comment by kestewart** [comment]
Changes merged as #682
