### ISSUE TITLE
Decide URLs for JSON-LD context, schema, and model

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#679]
Prior to the 3.0 release, we need to decide the final URLs for the JSON-LD context file, schema, and RDF model. Currently, these are:

* https://spdx.github.io/spdx-spec/v3.0/model/context.jsonld
* https://spdx.github.io/spdx-spec/v3.0/model/ontology.rdf.ttl
* https://spdx.github.io/spdx-spec/v3.0/model/schema.json

Changing these URLs will be difficult once users are actively creating SPDX documents, so these URLs need to be finalized before announcing that users should consume them

**Comment by bact** [comment]
Do we like to use spdx.dev domain name or do we like to use one of those persistent URL services (purl.org, w3id.org)?

**Comment by goneall** [comment]
My preference is for spdx.dev.  I would assume we can create a redirect in WordPress to point to the github.io pages if it is helpful.

**Comment by goneall** [comment]
Decided on tech call 2 April 2024 - 

- https://spdx.org/schema/3.0.0/spdx-json-schema.json
- https://spdx.org/rdf/3.0.0/spdx-model.ttl
- https://spdx.org/rdf/3.0.0/spdx-context.jsonld
- https://spdx.org/rdf/3.0.0/spdx-json-serailize-annotations.ttl

**Comment by bact** [comment]
> - https://spdx.org/rdf/3.0.0/spdx-json-serailize-annotations.ttl


Must be **"serialize"** (instead of "serailize", `i` before `a`)

**Comment by goneall** [comment]
> > * https://spdx.org/rdf/3.0.0/spdx-json-serailize-annotations.ttl
> 
> Must be **"serialize"** (instead of "serailize", `i` before `a`)
> 
> @goneall

Good catch @bact - I also updated the minutes with the correct spelling

**Comment by JPEWdev** [comment]
Yes, thanks for catching that
