### ISSUE TITLE
Security Examples need to be updated

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-3-model#689]
Security examples need to be reviewed, and make sure that they are are in sync with the latest version of SPDX.

**Comment by goneall** [comment]
@jeff-schutt - Can you help coordinate a review with the next week?
@JPEWdev - I don't know if you've had a chance look at the embedded examples in the markdown files

**Comment by rnjudge** [comment]
Planning to review all the security examples in the call this Wednesday. Will open a PR with any changes then.

**Comment by rnjudge** [comment]
Closing this issue - we reviewed and fixed a few small misprints at the last call (via https://github.com/spdx/spdx-3-model/pull/709)
