### ISSUE TITLE
`hasDataFile` would benefit from a better description

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#690]
The following line does not help to understand what it means and how it should be used. It is missing context and data file is a very generic term.

https://github.com/spdx/spdx-3-model/blob/eb10c88123ee3e401c375fbb3d52722b134bdb1e/model/Core/Vocabularies/RelationshipType.md?plain=1#L50

**Comment by goneall** [comment]
Looks like it was just copied from the SPDX 2.X definitions.

@maxhbr If you want to create a PR, we can get this into 3.0, otherwise I'll target it for 3.1

**Comment by goneall** [comment]
It has been a very long time since this was discussed.

I'll move it to 3.1 unless someone wants to volunteer to write a PR.

**Comment by kestewart** [comment]
@rgopikrishnan91 - do you want to take a pass at this description?

**Comment by bact** [comment]
In this [example SBOM](https://github.com/bact/sentimentdemo/blob/2dd889cac0f231fc19ce39542c7c4d16697f1560/bom.spdx3.json#L555-L565), I use it to documented that a classifier script has a classifier model (data file).

`[ predict.py ]` `--hasDataFile-->` `[ model.bin ]`

```json
{
    "type": "Relationship"
    "relationshipType": "hasDataFile",
    "from": "https://spdx.org/spdxdocs/File11",
    "to": [
        "https://spdx.org/spdxdocs/File10"
    ],
}
```

**Comment by bact** [comment]
Open PR #815 to get more suggestions

**Comment by rgopikrishnan91** [comment]
I left a review on the PR, but here are my thoughts 

Generic database fie --> File
I am unsure if saying hasDataFile is the right name? Should it hasAsset? because hasDataFile for a model executable and log file seems odd and non-intitutive.
Also, I am unsure and maybe we should clarify how its different from dependsOn relationship?

@bact @kestewart

**Comment by goneall** [comment]
> Should it hasAsset?

In other parts of the SPDX spec, we've used the term `Artifact` to mean something more general than a file.

**Comment by bact** [comment]
I agree with @rgopikrishnan91 that we should clarify how `hasDataFile` is different from `dependsOn`.

I can see that `hasDataFile` doesn't imply dependency, while `dependsOn` explicitly does.

`hasDataFile` also suggests that the `to` Element should be a `File` (although I don't think it is enforced by the model), while the `to` of `dependsOn` can be anything.

What I wonder is, from my example above, if we already have:

`[ predict.py ]` `--hasDataFile-->` `[ model.bin ]`

in the same SBOM, should we also have this?:

`[ predict.py ]` `--dependsOn-->` `[ model.bin ]`

**Comment by bact** [comment]
Found relevant information here, in the 2.3-3.0 difference table:
https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/diffs-from-previous-editions/#relationship

`dependsOn` has LifecycleScopeType as "test", as was named "TEST_DEPENDENCY_OF" in 2.3.

I'm not sure if `dependsOn` is now already generic and can be use in any lifecycle scope, or it still limited to the test.

**Comment by bact** [comment]
Yesterday AI team meeting (2024-07-31), we settled with this:

> - hasDataFile: The `from` Element treats each `to` Element as a data file. A data file is an artifact that stores data required or optional for the `from` Element's functionality. A data file can be a database file, an index file, a log file, an AI model file, a calibration data file, a temporary file, a backup file, and more. For AI training dataset, test dataset, test artifact, configuration data, build input data, and build output data, please consider using the more specific relationship types: `trainedOn`, `testedOn`, `hasTest`, `configures`, `hasInputs`, and `hasOutputs`, respectively. This relationship does not imply dependency.

(see #815) @maxhbr do you think this is sufficient? thank you
