### ISSUE TITLE
Punch List: IntegrityMethod

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#7]
This is a punch list of open questions from the 2021-12-07 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [ ] Do we want to have signatures as integrity methods?
- [ ] How are signatures going to be used (for example, element vs artifact)?  
- [ ] How can this model fit in with best practices on signing and verification practices?
- [ ] What is list of minimum capabilities so can include?
- [ ] How does integrity apply to element vs. collections vs. documents?
- [ ] Can integrity be applied to anything other than sequence of bytes? 
- [ ] How can we be sure that references to other SPDX documents can keep integrity intact?

**Comment by davaya** [comment]
Hashes and signatures can be computed only over artifacts - serialization means putting information into a specific sequence of bytes.  A single Element can be serialized into a file and a signature or hash computed over the bytes of that file.  This is true even if that Element is first serialized into a file containing many Elements - the multi-Element file will have one signature that validates all of the Elements within it.  A different multi-Element file will have a different signature. But when a single Element is extracted from both files its value, and thus its single-Element file signature, must be identical.

**Comment by iamwillbar** [comment]
Subgroup will look at verification of elements themselves, independent of 3.x timeline. `verifiedUsing` will continue to be verification of what the element references (e.g. an artifact).

**Comment by kestewart** [comment]
@iamwillbar - I believe we've covered all the issues in the punchlist now.   If you disagree, please reopen.
