### ISSUE TITLE
Cardinality constraints on external properties of AIPackage and DatasetPackage should be used consistently

### ISSUE THREAD

**Issue by sbarnum** [spdx/spdx-3-model#702]
The markdown file for AIPackage defines the following property constraints:

- /Core/Artifact/suppliedBy
   - minCount: 1
- /Software/Package/downloadLocation
   - minCount: 1

These are both narrowing restrictions on the externally defined properties that by default have cardinality of maxCount=1.
To be consistent with other such narrowing constraints (e.g., /Software/Package/packageVersion & /Software/SoftwareArtifact/primaryPurpose on AIPackage) these two property constraints should also explicitly assert maxCount=1.

The markdown file for DatasetPackage defines the following property constraints:

- /Core/Artifact/originatedBy
   - minCount: 1
- /Software/Package/downloadLocation
   - minCount: 1

These are both narrowing restrictions on the externally defined properties that by default have cardinality of maxCount=1.
To be consistent with other such narrowing constraints (e.g., /Software/SoftwareArtifact/primaryPurpose on DatasetPackage) these two property constraints should also explicitly assert maxCount=1.

**Comment by zvr** [comment]
I don't think this is needed.

The externally defined properties already have cardinality 0..1 (`minCount = 0` and `maxCount = 1`).

When changing `minCount` to 1, this changes the cardinality to 1..1 -- it does not change it to 1..*.

To put it differently, `minCount` and `maxCount` are handled independently. Changing one does not affect the other.

**Comment by zvr** [comment]
Closed via #704
