### ISSUE TITLE
Doc: Possible outdated references to gh-pages and auto-generated in README.md

### ISSUE THREAD

**Issue by bact** [spdx/spdx-3-model#726]
The README mentioned generated files available in `gh-pages` which is no longer updated (updated 3 months ago).

It also mentioned about HTML files generated by Ontospy, which is  generated the last time on 13 Jan 2024.

Should we update those site/branch. Or should we remove the references to them?

```markdown
These files are automatically processed into the following formats available at https://spdx.github.io/spdx-3-model/:

- HTML files generated by [Ontospy](http://lambdamusic.github.io/Ontospy/): https://spdx.github.io/spdx-3-model/auto-generated/
- [JSON-LD context](http://niem.github.io/json/reference/json-ld/context/) file: [context.json](https://spdx.github.io/spdx-3-model/context.json)
- Model [SHACL](https://en.wikipedia.org/wiki/SHACL) and [OWL](https://www.w3.org/OWL/) files:
  - [Turtle format](https://en.wikipedia.org/wiki/Turtle_(syntax)): [model.ttl](https://spdx.github.io/spdx-3-model/model.ttl)
  - [JSON-LD format](https://json-ld.org/): [model.jsonld](https://spdx.github.io/spdx-3-model/model.jsonld)

Note that these files are also available in the `gh-pages` branch.
```

**Comment by goneall** [comment]
Based on the discussion on the 23 April 2024 tech call, the consensus was to move to the SPDX spec repo for the generated documentation and delete the gh-pages branches.

**Comment by bact** [comment]
Conclusion for `gh-pages`: Delete it - see #727

- This also mean the sentence "Note that these files are also available in the `gh-pages` branch." will be removed from the README

No conclusion yet for the https://spdx.github.io/spdx-3-model/auto-generated/ from Ontospy,
