### ISSUE TITLE
Delete gh-pages for the spdx-3-model

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#727]
Since we are now generating the spec in the spdx-spec repo, this is no longer needed and indeed may cause some confusion.

Discussed on the SPDX tech call on 23 April 2024

**Comment by zvr** [comment]
Just deleted the branch.

**Comment by p-linnane** [comment]
Hi @zvr. We were leveraging this downstream for Homebrew to validate SBOM's.
```
  ==> Fetching SBOM schema
  ==> Downloading https://spdx.github.io/spdx-3-model/model.jsonld
  curl: (22) The requested URL returned error: 404
  Warning: Failed to fetch SBOM schema, cannot perform SBOM validation!
  Warning: Failed to fetch SBOM schema, cannot perform SBOM validation!
```
Is there another location this will be served from? Or do we need to vendor it ourselves?

**Comment by zvr** [comment]
@p-linnane that branch had not been updated for months!

We publish these in the https://github.com/spdx/spdx-spec repo (and of course it will be served in http://spdx.org/rdf, once released)

**Comment by p-linnane** [comment]
Thanks for the confirmation.
