### ISSUE TITLE
License list version is still not SemVer

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#730]
The License List version is still not SemVer compatible (e.g. 3.23, not 3.23.0)

Since this wasn't fixed before the 3.0 release, I suggest relaxing the requirement that it be a SemVer in `licenseListVersion` for 3.0.1

**Comment by swinslow** [comment]
With [the v3.24.0 release of the License List](https://lists.spdx.org/g/Spdx-legal/message/3558), we've now switched to SemVer.

**Comment by swinslow** [comment]
@JPEWdev @zvr Any further changes needed here from your perspective? 

Based on https://github.com/spdx/spdx-3-model/blob/main/model/SimpleLicensing/Properties/licenseListVersion.md and https://github.com/spdx/spdx-3-model/blob/main/model/SimpleLicensing/Classes/LicenseExpression.md I think the spec documents the License List version as SemVer. So together with the v3.24.0 release from May, are we good to close this?

**Comment by goneall** [comment]
I think we're good to close this issue IMO - there is a [related issue in the license list publisher](https://github.com/spdx/LicenseListPublisher/issues/181) to solve a compatibility issue created by our changes here.

@swinslow  - before our next release of the license list, I should fix this in the license list publisher and update the CI for the license list XML repo.

**Comment by goneall** [comment]
Closing this issue as completed
