### ISSUE TITLE
Document PATCH for specVersion

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-3-model#733]
In specVersion, it is written:

The specVersion provides a reference number that can be used to understand how to parse and interpret an Element.
It will enable both future changes to the specification and to support backward compatibility.
The **major version number** shall be incremented when incompatible changes between versions are made
(one or more sections are created, modified or deleted).
The **minor version number** shall be incremented when backwards compatible changes are made.

I understand that for the spec versioning we are using SemVer, so with a PATCH version.

This should be documented.

**Comment by kestewart** [comment]
https://spdx.github.io/spdx-spec/v3.0.1-draft/model/Core/Properties/specVersion/ to be updated with the details on patch.
