### ISSUE TITLE
ProfileIdentifierType list

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-3-model#735]
ProfileIdentifierType lists the following profiles:
* ai: the element follows the AI profile specification
* build: the element follows the Build profile specification
* core: the element follows the Core profile specification
* dataset: the element follows the Dataset profile specification
* expandedLicensing: the element follows the expanded Licensing profile specification
* extension: the element follows the Extension profile specification
* security: the element follows the Security profile specification
* simpleLicensing: the element follows the simple Licensing profile specification
* software: the element follows the Software profile specification
* usage: the element follows the Usage profile specification

Questions:
* where is the Usage profile described?
* the Lite profile is missing

**Comment by bact** [comment]
FYI, the Usage profile got pushed to 3.1 instead.

See: https://github.com/spdx/spdx-3-model/pull/191
