### ISSUE TITLE
What does "IRI ``" mean?

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-3-model#736]
In NoAssertionElement (and several others) you have:

```
IRI ``
```

What does that mean?

**Comment by zvr** [comment]
Thanks for reporting this, @vargenau .

In _this_ repo, there is no such information; as you can see in https://github.com/spdx/spdx-3-model/blob/main/model/Core/Individuals/NoAssertionElement.md there is no IRI.

I think you are reporting that the empty IRI appears in the generated specification.

This seems to be an issue with the generator; I'll fix it shortly.

When you say "(and several others)" do you mean more than the one you listed and `NoneElement`?

**Comment by vargenau** [comment]
Hi @zvr 

I see it here:
* https://spdx.github.io/spdx-spec/v3.0/model/Core/Individuals/NoAssertionElement/

And also:
* https://spdx.github.io/spdx-spec/v3.0/model/Core/Individuals/NoneElement/

It is present with a value in:
* https://spdx.github.io/spdx-spec/v3.0/model/ExpandedLicensing/Individuals/NoAssertionLicense/
* https://spdx.github.io/spdx-spec/v3.0/model/ExpandedLicensing/Individuals/NoneLicense/

**Comment by zvr** [comment]
Thanks, @vargenau .

I knew of the two instances -- I was intrigued by your "and several others". 

Fixed in spec-parser.

**Comment by vargenau** [comment]
Yes, there were only two. Sorry for the confusion.

**Comment by zvr** [comment]
No problem. Shall we close this issue?

**Comment by vargenau** [comment]
Yes, if it is fixed in the parser, you can close the issue.
