### ISSUE TITLE
rootElement: SBOM or BOM?

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-3-model#745]
In `rootElement`it is written:

This property is used to denote the root Element(s) of a tree of elements contained in an SBOM.

Is it really SBOM, or can it be a BOM?

BOM is defined in Core, SBOM is defined in Software only.

**Comment by goneall** [comment]
Agree - this should be on BOM.  Fortunately, `rootElement` is in the core profile, so we only need to update the description and/or summary.
