### ISSUE TITLE
Where is the "Legacy Text Template format section"?

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-3-model#747]
In standardLicenseTemplate, it says:

A standardLicenseTemplate contains a license template which describes sections of the License text which can be varied. See the Legacy Text Template format section of the SPDX specification for format information.

Where is the "Legacy Text Template format section"?

**Comment by bact** [comment]
They are available in v2.3 but I cannot find it in v3.0 as well.

https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b153-legacy-text-template-format

**Comment by bact** [comment]
Will be fixed by https://github.com/spdx/spdx-spec/pull/968

**Comment by bact** [comment]
Note that the new Licensing Matching Guidelines in 3.0.1, added by #968 (merged), does not has a "Legacy Text Template format" subsection in the "SPDX License list" section.

**Comment by swinslow** [comment]
Thanks @vargenau for noting this.

I would be inclined to delete the following sentence from https://github.com/spdx/spdx-3-model/blob/main/model/ExpandedLicensing/Properties/standardLicenseTemplate.md:

> See the Legacy Text Template format section of the SPDX specification for format information.

As well as, from the Summary part of that same file:

> , in SPDX templating format

@goneall @zvr Let me know if you feel differently. If this should stay, then I assume we would need to re-insert the legacy text template formatting section into the spec and/or model. I don't have a preference either way, but agree that this should be consistent.

**Comment by bact** [comment]
@swinslow https://github.com/spdx/spdx-3-model/blob/main/model/ExpandedLicensing/Properties/standardAdditionTemplate.md also made a reference to the Legacy Text Template. Do you feel to delete that reference as well?

**Comment by bact** [comment]
Note that this is related to the release of 3.0.1 model, as it may introduce changes to these properties:

- [standardLicenseTemplate](https://github.com/spdx/spdx-3-model/blob/main/model/ExpandedLicensing/Properties/standardLicenseTemplate.md)
- [standardAdditionTemplate](https://github.com/spdx/spdx-3-model/blob/main/model/ExpandedLicensing/Properties/standardAdditionTemplate.md)

**Comment by goneall** [comment]
> Since we are moving towards using the `licenseXml` to describe the variable text, I am in favor of removing the references. In looking at the description for the [licenseXml description](https://spdx.github.io/spdx-spec/v3.0.1-draft/model/ExpandedLicensing/Properties/licenseXml/), I did notice one problem - we reference the Github URL for the field definitions. @zvr - will this be a problem for ISO? I haven't checked to see if this is covered by another issue or pull request.

After reviewing the PR, I changed my mind.  I think we need to include the format description even though we are encouraging the XML format.  Perhaps in the field we should mention that the `licenseXml` contains the same replacement information and should be used.

**Comment by bact** [comment]
> In looking at the description for the [licenseXml description](https://spdx.github.io/spdx-spec/v3.0.1-draft/model/ExpandedLicensing/Properties/licenseXml/), I did notice one problem - we reference the Github URL for the field definitions. @zvr - will this be a problem for ISO? I haven't checked to see if this is covered by another issue or pull request.

Not yet. It still points to GitHub repo: https://github.com/spdx/spdx-3-model/blob/main/model/ExpandedLicensing/Properties/licenseXml.md?plain=1 (btw, updates in spdx-3-model will not automatically show in the https://spdx.github.io/spdx-spec/v3.0.1-draft/, as the build workflow will only get triggered by a PR from within spdx-spec)

I can update the links to these:
- https://github.com/spdx/license-list-XML/blob/5f885e8264dc701c1d7b764539691e3cc5a49fb2/DOCS/xml-fields.md
- https://github.com/spdx/license-list-XML/blob/5f885e8264dc701c1d7b764539691e3cc5a49fb2/schema/ListedLicense.xsd

**Comment by bact** [comment]
> After reviewing the PR, I changed my mind. I think we need to include the format description even though we are encouraging the XML format. Perhaps in the field we should mention that the `licenseXml` contains the same replacement information and should be used.

I address this with PR #820

**Comment by bact** [comment]
Two options

1) Remove Legacy Text Template, apply this PR
    1. https://github.com/spdx/spdx-3-model/pull/818

2) Keep Legacy Text Template, apply this PR
    1. https://github.com/spdx/spdx-spec/pull/1026
    2. https://github.com/spdx/spdx-3-model/pull/820

Option 1 is less likely, as it will make a string in standardLicenseTemplate and standardAdditionTemplate a free-form text.

**Comment by kestewart** [comment]
Based on discussion in call,  we're going forward with "Keep Legacy Text Template", and apply the two PRs.   Art will close #818

**Comment by bact** [comment]
#1026 still needs to be applied
