### ISSUE TITLE
Handling NONE and NOASSERTION values in a consistent manner

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#76]
In the SPDX 2.X spec, there are several fields which accept a value of `NONE` and `NOASSERTION` which have specific semantic meaning along with either a text or a class. 

This is defined in RDF as a superclass restriction - you can find an example for [SPDX Item](https://spdx.org/rdf/terms/#d4e3785) in the `License Concluded` property.  This may not be the cleanest approach since we're mixing individual values with other types (e.g. `xsd:string`) and the reasoning is rather clunky IMHO.

@swinslow is proposing having an abstract class for each of the properties where the values can include the `NONE` and `NOASSERTION` values which may yield a slightly different RDF model.

There may also be other alternatives.

Whichever approach we take, we should probably be consistent.

Related to issue #71 

@sbarnum @davaya @zvr - Interested in any thoughts you have on this issue.

**Comment by swinslow** [comment]
Thanks @goneall! I'm closing #65 in favor of #77 so that the initial Licensing profile draft can be merged into a separate branch -- just flagging that here so that it doesn't get lost  :)

I don't have a strong preference either way on the manner in which NONE / NOASSERTION is handled. I had structured it as shown in #65 / #77 mostly out of trying to move away from assuming string values for Licensing fields as you noted, but happy to adjust as appropriate.

**Comment by maxhbr** [comment]
this is a duplicate of https://github.com/spdx/spdx-3-model/issues/71?

**Comment by goneall** [comment]
Discussed on the SPDX Tech call on 18 April 2023:
- For properties with an enumeration, we can just have a value NONE and NOASSERTION be one of the enumeration values
- For RDF properties with a typed value, having a concrete individual representing the NONE and NOASSERTION is the preferred approach.  If we were to take this route, we would need to extend the markdown file format to be able to express individual values in the range for a property.  Perhaps having a Union of a type and an individual value?
- An alternative solution is to "wrap" the typed value with another class that offers the typed value, NONE and NOASSERTION as 3 different possible results (similar to Java's Optional class).  This was considered more complex for the RDF Ontology.

**Comment by goneall** [comment]
@zvr - Any thought on how we can express an Individual value for the range of a property?

**Comment by goneall** [comment]
If we use an Individual approach as suggested on the tech call, should we create separate individuals for each class/type (e.g. NoAssertionLicense) or just use a single individual for all uses (e.g. NoAsserttion).  In SPDX 2.X, we use just the single individual in all cases.

Another question is for text fields.  For the text fields, can we have an Individual with a range `xsd:string`?

**Comment by goneall** [comment]
In SPDX 2.X we have `none` and `noassertion` individuals which are included in the domain of values for any Object property which can have a NONE or NOASSERTION in the spec.  For example, `licenseConcluded`.  This isn't done for data properties.

Do we want to do the same thing in SPDX 3 or do we want to have different individual values for every type (e.g. NoneLicesne, NoneCopyrightText, None...)?

**Comment by kestewart** [comment]
Handled in https://github.com/spdx/spdx-3-model/pull/300.   Closing now.   Please reopen if I've misinterpretted.

**Comment by goneall** [comment]
@kestewart #300 takes care of half of this issue, we still need to resolve how we handle non-string properties - reopening.

**Comment by goneall** [comment]
This will be resolved with PR #456

**Comment by goneall** [comment]
This was resolved with PR #456
