### ISSUE TITLE
AI: Not clear what 'energyQuantity' means

### ISSUE THREAD

**Issue by VenkatTechnologist** [spdx/spdx-3-model#767]
The property energyQuantity's name or its description does not provide enough information to understand what the property stands for.

**Comment by bact** [comment]
Thanks @VenkatTechnologist, will this be something sufficient ?

```json
{
    "energyConsumption": {
        "trainingEnergyConsumption": {
            "energyQuantity": 345,
            "energyUnit": "kilowattHour"
        },
        "finetuningEnergyConsumption": {
            "energyQuantity": 42,
            "energyUnit": "kilowattHour"
        }
    }
}
```

We are now working on examples. If you find there's anything need more explanation, feel free to shout out. Thank you.

**Comment by VenkatTechnologist** [comment]
In addition to the examples, it would be good
to provide explanation of what energyQuantity
is, and how it fits in the scheme of EnergyConsumption(s).

The reason for the confusion is because we
have two similar sounding objects EnergyConsumption
and energyQuantity without the details of how they
are placed. Thanks.

**Comment by bact** [comment]
Thanks. Will this read better?

"Represents the energy quantity.

The quantity is the amount or numerical value of the energy we are trying to represent.
The unit of measure is how we express the measurement of the quantity.

For example, 42 kilowatt-hour of energy will have the property `energyQuantity` as `42` and the property `energyUnit` as `kilowattHour`."

The 2nd and 3rd paragraphs will also be added to `energyUnit` description.

**Comment by bact** [comment]
Code snippet and narrated example are add to EnergyConsumption and EnergyConsumptionDescription, in PR #780
