### ISSUE TITLE
AI: 'modelExplainability' summary and description should be modified

### ISSUE THREAD

**Issue by VenkatTechnologist** [spdx/spdx-3-model#770]
The summary and description of modelExplainability property states:

**Summary
Describes methods that can be used to explain the model.

Description
A free-form text that lists the different explainability mechanisms (such as SHAP, or other model specific explainability mechanisms) that can be used to explain the model.**

This should be modified to:

**Summary
Describes methods that can be used to explain the predictions of the model.

Description
A free-form text that lists the different explainability mechanisms (such as SHAP, or other model specific explainability mechanisms) that can be used to explain the predictions of the model.**

**Comment by bact** [comment]
I think the idea here is to make it more generic as the model can be non-predictive as well (for example, generative model).

**Comment by VenkatTechnologist** [comment]
Then let us make it

"Describes methods that can be used to explain the results from the model."

**Comment by bact** [comment]
Put on SPDX AI Team Meeting 2024-07-03 agenda.

**Comment by bact** [comment]
SPDX AI Team Meeting 2024-07-24 - No objection.

Will open a PR
