### ISSUE TITLE
AI: 'trainingEnergyConsumption' is duplicate of 'energyConsumption'

### ISSUE THREAD

**Issue by VenkatTechnologist** [spdx/spdx-3-model#771]
It looks like 'trainingEnergyConsumption' and 'energyConsumption' properties are meant for the same purpose.
Either one of them can be removed. 

Also, see #768 .

**Comment by bact** [comment]
`energyConsumption` will contain `EnergyConsumption` object, which in turn contains energy consumption for different stages.

A description and example is updated in PR #780 to make it clearer.
