### ISSUE TITLE
publishedTime redefined in EpssVulnAssessmentRelationship

### ISSUE THREAD

**Issue by mugicha101** [spdx/spdx-3-model#783]
Within the Security profile, both [EpssVulnAssessmentRelationship](https://github.com/spdx/spdx-3-model/blob/e542684fc292183227bd03c87e068a8a52578f19/model/Security/Classes/EpssVulnAssessmentRelationship.md?plain=1#L55) and its parent class [VulnAssessmentRelationship](https://github.com/spdx/spdx-3-model/blob/e542684fc292183227bd03c87e068a8a52578f19/model/Security/Classes/VulnAssessmentRelationship.md?plain=1#L26) define publishedTime.

Looks like publishedTime within EpssVulnAssessmentRelationship should be an external property restriction instead as the only difference is minCount: 1.

**Comment by bact** [comment]
Should we also remove 

```markdown
- /Core/Relationship/to
  - minCount: 1
```

from `VulnAssessmentRelationship` as well?

As `/Core/Relationship` already has `minCount: 1` for `to`.

**Comment by goneall** [comment]
Agree we should fix both issues  (`/Core/Relationship/to` and moving `publishedTime` to external property restrictions).
