### ISSUE TITLE
location for SPDX 3 Operations Profile proposal

### ISSUE THREAD

**Issue by umm0** [spdx/spdx-3-model#785]
Hi,

Kate asked us a while back to put the proposal for an SPDX Operations profile into a pull request. Mostly to have it available for a discussion with the tech team on June 18th.

I haven't got any information, to where is should put this pull request. Can someone point this out?

The data does not yet adhere to any SPDX 3 structure definitions. It is a simple JSON file plus a markdown description generated from the JSON.

Best regards,
Ummo

**Comment by goneall** [comment]
Hi Ummo,

 

For discussion purposes, if it is somewhat of an example format you can put the pull request into https://github.com/spdx/spdx-3-serialization-prototype-playground.

 

We will need to put the operations profile into the SPDX-3-Model structure at some point.  Once that is ready, please add a pull request to the spdx-3-model repo.


Thanks,

Gary

 

From: umm0 ***@***.***> 
Sent: Friday, June 14, 2024 5:22 AM
To: spdx/spdx-3-model ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spdx/spdx-3-model] location for SPDX 3 Operations Profile proposal (Issue #785)

 

Hi,

Kate asked us a while back to put the proposal for an SPDX Operations profile into a pull request. Mostly to have it available for a discussion with the tech team on June 18th.

I haven't got any information, to where is should put this pull request. Can someone point this out?

The data does not yet adhere to any SPDX 3 structure definitions. It is a simple JSON file plus a markdown description generated from the JSON.

Best regards,
Ummo

**Comment by umm0** [comment]
Added pull request https://github.com/spdx/spdx-3-serialization-prototype-playground/pull/37 to  https://github.com/spdx/spdx-3-serialization-prototype-playground
