### ISSUE TITLE
Should we use `@type` / `@id` or `spdxId` / `type` in example snippets?

### ISSUE THREAD

**Issue by bact** [spdx/spdx-3-model#799]
- Security Profile classes like [CvssV2VulnAssessmentRelationship](https://spdx.github.io/spdx-spec/v3.0/model/Security/Classes/CvssV2VulnAssessmentRelationship/) and [EpssVulnAssessmentRelationship](https://spdx.github.io/spdx-spec/v3.0/model/Security/Classes/EpssVulnAssessmentRelationship/) use `@type` and `@id` in their "Syntax" example snippets.
  - The snippets look like JSON but do not follow JSON-LD serialization schema that use `type` and `spdxId` as keys.
    - But this may be valid because of the context?
  - Non-Core Profile names also do not prefixed by namespaces. For example, `score` instead of `security_score`.
- [Vulnerability](https://spdx.github.io/spdx-spec/v3.0/model/Security/Classes/Vulnerability/) uses both `@type` and `type` in a same snippet

**Comment by bact** [comment]
#794 (merged) changed @type -> type, and @id -> spdxId in Security Profile

**Comment by kestewart** [comment]
Closing as merged.
