### ISSUE TITLE
SPDX 2->3 conversion of ExternalPackageReferences

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#81]
This is part of #74:

Edit: updated after I understood that ExternalPackageReference will be split into two new properties. Some references will convert to ExternalIdentifier, others to ExternalReference. See the [migration documentation](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#) for a conversion guideline.

There remain two problems when the `category` is `OTHER`:
- In this case, `type` can be String-valued. Should this then be converted to SPDX3 `ExternalIdentifierType.other` or `ExternalReferenceType.other`?
- Also in this case, `locator` can be an arbitrary String (without spaces) in SPDX2, but the SPDX3 `ExternalReference.locator` must be a URI. `ExternalIdentifier.identifier` would be a String, but can we be sure that the SPDX2 reference of category `OTHER` is actually an identifier?

**Comment by armintaenzertng** [comment]
The following SPDX 2 external package ref types don't seem to have an SPDX 3 counterpart:
- url
- maven-central
- npm
- nuget
- bower
How would they be sorted into identifier vs reference?

**Comment by goneall** [comment]
I would suggest - reference.

**Comment by kestewart** [comment]
This needs to be handled, but not considered a blocker for 3.0-rc

**Comment by goneall** [comment]
Kate and I discussed this.  We probably should handle these in RC2 since it will impact the vocabulary.

**Comment by goneall** [comment]
@maxhbr - with @armintaenzertng being out, would you mind adding a pull request to add the missing external reference types?

**Comment by armintaenzertng** [comment]
I opened #484 to address the issue of missing ExternalRefTypes.

However, the initial question of this issue still stands, namely what to do with [the `OTHER` category](https://spdx.github.io/spdx-spec/v2.3/external-repository-identifiers/#f5-other) of SPDX2.
I'd think it would probably be safer to convert these to references instead of identifiers, but as pointed out above, SPDX3 identifiers expect a URI while the `OTHER` locator is an arbitrary string.

**Comment by goneall** [comment]
> However, the initial question of this issue still stands, namely what to do with [the OTHER category](https://spdx.github.io/spdx-spec/v2.3/external-repository-identifiers/#f5-other) of SPDX2.
I'd think it would probably be safer to convert these to references instead of identifiers, but as pointed out above, SPDX3 identifiers expect a URI while the OTHER locator is an arbitrary string.

I'm thinking we should change the type of ExternalRefTypes to be `xsd:string`.  I'm not sure why we restricted it to a URI if it is a reference.
