### ISSUE TITLE
Add ISO number for SWHID

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-3-model#816]
in Vocabulary / ExternalIdentifierType

**Comment by bact** [comment]
> ISO/IEC DIS 18670 Information technology — SoftWare Hash IDentifier (SWHID) Specification V1.2
[Under development](https://www.iso.org/standard/89985.html#lifecycle)
This Draft International Standard is in the enquiry phase with ISO members.

https://www.iso.org/standard/89985.html

**Comment by kestewart** [comment]
Closing this to track it now under PR.

**Comment by kestewart** [comment]
I'm fine with DIS, however in a couple of months, DIS will be removed, so I expect that when ISO is reviewing it, they'll ask us to change it.   But DIS for now is accurate, so no objection.
