### ISSUE TITLE
SPDX 2->3 conversion of FileTypes

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#82]
Part of #74:

SPDX 2 `fileType` will be converted to `contentType`. But contrary to `contentType`, `fileType` is not restricted to a single value, thus different `fileType`s might call for different `contentType`s, which would be problematic.

This topic has been discussed in the tech team call on 2023-02-21.

An example document "from the wild" with multiple file types per file [can be found here](https://github.com/chainguard-dev/bom-shelter/blob/cfa2d04268d5c28c601e5386ee723d38914c37dd/in-the-wild/spdx/source-controller_0.21.2_sbom.spdx.json#L7695-L7698).

**Comment by zvr** [comment]
The example includes the lines:
```
   "fileName": "internal/helm/testdata/charts/helmchart-0.1.0.tgz",
   "fileTypes": [
    "APPLICATION",
    "ARCHIVE"
   ]
```

In _this_ case, the correct `fileType` for the file is `application/vnd.cncf.helm.chart.content.v1.tar+gzip `.

Both `application` and `archive` are valid `filePurpose` values and can both be present.

**Comment by armintaenzertng** [comment]
So you are saying that the contentType has to be determined from the filename alone (the provided SPDX2 fileTypes `APPLICATION` and `ARCHIVE` are no help in this whatsoever).

But for an automated conversion approach, extracting the contentType from the filename is not feasible/maintainable. The [list of possible MIME types](https://www.iana.org/assignments/media-types/media-types.xhtml) is huge and dynamic, and the helmchart example above makes use not only of the file extension but also of (from an algorithm's perspective) seemingly random other parts of the filename.

Furthermore, I found [this warning](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types), indicating that the file extension might not necessarily be the source of truth for the contentType:
> Browsers use the MIME type, not the file extension, to determine how to process a URL, so it's important that web servers send the correct MIME type in the response's Content-Type header.

In light of this, I don't think an automated conversion can do much more than a basic conversion from the fileType Enum to some very generic MIME types. Two of these generic types are `text/plain` and `application/octet-stream`. For audio/image/video I have yet to find such a generic analogue.

I will prepare a conversion table for this to help the disussion.

**Comment by armintaenzertng** [comment]
Here is a conversion table from `fileType` to `contentType`. I would consider this issue closed as soon as this table is complete.

| SPDX2 File Type | MIME Content Type        |
|-----------------|--------------------------|
| SOURCE          |  text/plain                        |
| BINARY          |  application/octet-stream                        |
| ARCHIVE         |  application/octet-stream                        |
| APPLICATION     | application/octet-stream |
| AUDIO           |  audio/???                        |
| IMAGE           |  image/???                        |
| TEXT            | text/plain               |
| VIDEO           |   video/???                       |
| DOCUMENTATION   |  text/plain                        |
| SPDX            |   spdx type in MIME?                       |
| OTHER           |  ???                        |

**Comment by goneall** [comment]
SPDX - for tag/value, the media type is [text/spdx](https://www.iana.org/assignments/media-types/text/spdx), for JSON the media type is [application/spdx+json](https://www.iana.org/assignments/media-types/application/spdx+json).

**Comment by iamwillbar** [comment]
One of the things that we identified is that FileType was being used for two things:
1. Describing the purpose of the file.
2. Describing the type of content in the file.

For SPDX 3.0 we split this into two properties:
* `SoftwarePurpose` to capture the purpose (which is of type `SoftwarePurpose`).
* `ContentType` to capture the type of content (which is of type `MediaType`).

The name `ContentType` was chosen to mirror the Content-Type header in HTTP (which is also of type MediaType) and to express that this is describing the type of content (as opposed to metadata, headers, or something else). For example, if (and not saying we would) we extended `File` in the future to be able to capture the type of executable header a file has (e.g. ELF), that could also be of type `MediaType` but the property name might be `ExecutableHeaderType`.

**Comment by goneall** [comment]
FYI - I updated the [SPDX 3 Migration Analysis](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.rdk9o9wzr24c) with @iamwillbar description above.

**Comment by armintaenzertng** [comment]
Thanks to @iamwillbar, I've updated [the conversion table](https://github.com/spdx/spdx-3-model/issues/82#issuecomment-1441476885) to include `SoftwarePurpose` as an alternative property to convert to.

This mainly leaves the problem of AUDIO, VIDEO and IMAGE as well as SPDX in the formats rdf-xml, xml and yaml.

**Comment by goneall** [comment]
Since we can't determine the exact format for Audio, Video or Image, I suggest we use the default application/octet-stream:

| SPDX2 File Type | MIME Content Type        | SoftwarePurpose |
|-----------------|--------------------------|---------|
| SOURCE          |                         | source |
| BINARY          |  application/octet-stream    | 
| ARCHIVE         |    | archive |
| APPLICATION  | | application |
| AUDIO           |  application/octet-stream                  |
| IMAGE           |  application/octet-stream                       |
| TEXT            | text/plain               |
| VIDEO           |   application/octet-stream                      |
| DOCUMENTATION   |                          |  documentation |
| SPDX            |   text/spdx for tag-value, application/spdx+json for json; what about the other formats? |
| OTHER           |                          | other |

**Comment by goneall** [comment]
@kestewart @armintaenzertng @zvr - Any objections?

**Comment by zvr** [comment]
Why lose the information of types?
I mean, even if you don't want to look at filenames for a hint (and decide it's an `image/gif`), you can always use a wildcard subtype `image/*` for what has previously been tagged as `IMAGE` before.

And a more general question: are the issues discussed here _recommendations_ on how to do a conversion from SPDXv2 data or _must-do-it-this-way_ ?

**Comment by goneall** [comment]
> Why lose the information of types? I mean, even if you don't want to look at filenames for a hint (and decide it's an `image/gif`), you can always use a wildcard subtype `image/*` for what has previously been tagged as `IMAGE` before.
> 

if wildcards are valid, then let's go with that.  I've updated the [migration guide section](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.ci8ghfkbglr8).

> And a more general question: are the issues discussed here _recommendations_ on how to do a conversion from SPDXv2 data or _must-do-it-this-way_ ?

I would suggest these are all recommendations - I'll be adding an Annex to the spec repo based on the migration guide for review in the next couple of days.

**Comment by goneall** [comment]
No objections to the wild card over - the migration guide has been updated.  Closing this issue as resolved.
