### ISSUE TITLE
No file contributor property in the SPDX 3 model

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#827]
SPDX 2.3 has a [fileContributor](https://spdx.github.io/spdx-spec/v2.3/file-information/#814-file-contributor-field) property which does not exist in the SPDX 3.0 model.

This is not documented in the [diffs-from-previous-editions](https://spdx.github.io/spdx-spec/v3.0.1-draft/annexes/diffs-from-previous-editions/) Annex.

If this was intentional, it should be documented.  Otherwise, we should add back this property for compatibility.

**Comment by goneall** [comment]
ping @kestewart

**Comment by kestewart** [comment]
We'll document this as deleted in favor of "originator" (which is a property in Artifact).

**Comment by goneall** [comment]
Added https://github.com/spdx/spdx-spec/pull/1038 to fix in the spec-repo

**Comment by goneall** [comment]
Fixed with https://github.com/spdx/spdx-spec/pull/1038
