### ISSUE TITLE
SPDX 2->3 conversion of PackageFileName

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#83]
Part of #74:

- Will this be a `Relationship` to a file? `packageFileName` may also point to a folder, though.
- If a future integrity profile requires a checksum, it may not be possible to translate to a file relationship since the checksum is optional in SPDX2.

Gary's comment from #74:
 > We were thinking of using a relationship. If it is a folder, then we would probably create a separate "package" definition to represent the folder? The folder scenario is one I have not thought through and probably deserves more discussion.

This has been discussed in the tech team call on 2023-02-21.

This has been discussed in the tech team call on 2023-03-07:
Gary's migration document describes the conversion process.
Open issue is still the case that `packageFileName` may also point to a folder.

**Comment by goneall** [comment]
Kate and I discussed this and thought it should be resolved in RC2 in case there is a change to the model.

**Comment by armintaenzertng** [comment]
As long as we agree on that a `File` ("any object that stores content on a computer" according to its description) can also be a directory, this should work out fine.

If not, then the current solution of having a relationship pointing at a file will not work for the case of the SPDX2 `PackageFileName` being a directory.

**Comment by goneall** [comment]
@goneall to create pull request for File and update the migration document for this issue - we will allow for File to be a directory.
