### ISSUE TITLE
Add conformance for Lite profile

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-3-model#833]
Not everything mentioned in the Lite profile Annex of the spec is included in the actual definition.

The mandatory parts have to be mentioned in the profile definition.

**Comment by NorioKobota** [comment]
duplicated?
https://github.com/spdx/spdx-3-model/pull/843

**Comment by zvr** [comment]
@NorioKobota   This here is the issue to solve; #843 is the PR solving it.

**Comment by NorioKobota** [comment]
Ah sorry, issue and PR.. I saw it wrong.

**Comment by zvr** [comment]
Done via #843
