### ISSUE TITLE
Change cardinality for element in SpdxDocument and Bom classes

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#841]
From the SPDX tech call 30 July 2024, we reached consensus that the SpdxDocument and Bom classees should have a minimum of 1 element.

We should update the model to reflect this decision.

**Comment by goneall** [comment]
@zvr - How do we override the superclass restrictions to change the cardinality in the markdown files?

**Comment by goneall** [comment]
@zvr if it's easy, could you create the PR for the cardinality changes?  Otherwise, I can do it early Monday - hoping to get this in before the OMG deadline.

**Comment by zvr** [comment]
Just to verify:

- can be empty:
  - /Core/ElementCollection
  - /Core/Bundle
- must have at least one element
  - /Core/SpdxDocument
  - /Core/Bom
  - /Software/Sbom

Must these also have at least one rootElement ?

**Comment by zvr** [comment]
OK, to save us time, I created **two** PRs, depending on what we need to be non-empty:

- update only `element`: #844 
- update both `element` and `rootElement`: #845 

We should merge only **one** of these.
