### ISSUE TITLE
delete serialization/lite.md

### ISSUE THREAD

**Issue by NorioKobota** [spdx/spdx-3-model#846]
I think SPDX Lite is well explained in [model](https://github.com/spdx/spdx-3-model/pull/843) and [annex](https://github.com/spdx/spdx-spec/pull/1061), so [serialization/lite.md](https://github.com/spdx/spdx-3-model/blob/main/serialization/lite.md) should be deleted.

**Comment by kestewart** [comment]
This isn't a blocker for release, we'll deal with after the .pdf is generated.

**Comment by NorioKobota** [comment]
Thanks, @kestewart.
I think it's a good idea to describe ```Format```, but I don't think it should be described in ```serialization``` part. Anyway, let us discuss after the release of the pdf.
