### ISSUE TITLE
SPDX 2->3 conversion of DocumentNamespace

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#87]
Part of #74:

Gary's comment in #74:
> I recall a discussion where we could represent a "default namespace" that would be used. That being said, I don't see a way to represent the default namespace using the namespace map. Perhaps others on the call recall how this is done.

This has been discussed in the tech team call on 2023-02-21:
 * Main discussion Gary was referring to was around using JSON LD which supports default namespace
 * Applies to all serializations, including RDF, JSON, JSON LD, ...
 * Need to look at adding field to SPDX 3? Depends on serialization formation, where it might need to be. Recommend expanding IRI out into full and including verbatim.

**Comment by goneall** [comment]
Since we removed namespace map from the model, this no longer applies.

@armintaenzertng If you still see an issue, please open a new issue.
