### ISSUE TITLE
Potential issues in the JSON context file

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#870]
I ran into 2 potential issues in the JSON-LD context file generated by the spec-parser which are currently being tracked against the spec-parser which generates the context file:

- https://github.com/spdx/spec-parser/issues/145
- https://github.com/spdx/spec-parser/issues/144

**Comment by JPEWdev** [comment]
These both should be resolved

**Comment by goneall** [comment]
> These both should be resolved

Agree - closing
