### ISSUE TITLE
What is "Document" in ExternalMap context?

### ISSUE THREAD

**Issue by bact** [spdx/spdx-3-model#871]
"Document", with uppercase "D", is used in ExternalMap and externalSpdxId:

- https://spdx.github.io/spdx-spec/v3.0.1-draft/model/Core/Classes/ExternalMap/
- https://spdx.github.io/spdx-spec/v3.0.1-draft/model/Core/Properties/externalSpdxId/

I guess they are meant to be `SpdxDocument`.

Should we replace "Document" with "SpdxDocument" in their summaries and descriptions?

**Comment by goneall** [comment]
Agree with replacing "Document" with "SpdxDocument" - I believe that is the intent of the descriptions since Document has an uppercase "D".  An alternative would be to refer to a serialization of data, but I think the latter alternative would be more confusing since we have "SpdxDocument" defined.

**Comment by bact** [comment]
thx. I've created PR #872 for this
