### ISSUE TITLE
FuSa references for SPDX 3.0

### ISSUE THREAD

**Issue by nicpappler** [spdx/spdx-3-model#88]
To use the SPDX references for Functional Safety (FuSa), the reference EVIDENCE needs to be added. With the description: To be used when SPDXRef-A is an evidence for the adherence to what is defined in SPDXRef-B.

Also keeping the references REQUIREMENT and SPECIFICATION like they are currently defined is needed for FuSa.

More information what all this FuSa stuff is needed for has been discussed at Fosdem in the SBOM devroom (https://fosdem.org/2023/schedule/event/sbom_fusa/)

@kestewart - can you please comment? Did I forget something?

**Comment by kestewart** [comment]
Extending set of relationships types to include this concept.

**Comment by kestewart** [comment]
SpecificationFor and RequirementFor have been included in the https://github.com/spdx/spdx-3-model/blob/main/model/Core/Vocabularies/RelationshipType.md
