### ISSUE TITLE
Add SpdxOrganization to Core Profile diagram

### ISSUE THREAD

**Issue by bact** [spdx/spdx-3-model#882]
New individual [SpdxOrganization](https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Individuals/SpdxOrganization/)

**Comment by goneall** [comment]
@zvr @ramartin - do we need this for the OMG / ISO spec version?

**Comment by zvr** [comment]
No, we said we will not show _any_ Individuals in the model diagram.

I think I remember a PR removing the None/NoAssertion elements and licenses.
