### ISSUE TITLE
packageVerificationCodeExcludedFile filename prefix

### ISSUE THREAD

**Issue by ilans** [spdx/spdx-3-model#910]
From /Core/packageVerificationCodeExcludedFile:
"**In general**, every filename is preceded with a ./, see [RFC 3986](https://datatracker.ietf.org/doc/rfc3986/) ..."

Why use "**In general**" if the summary clearly states that this is "The **relative** file name...".
Shouldn't it always preceded with `./`?

If that's correct, I'll include a SHACL rule.

**Comment by bact** [comment]
Because RFC 3986 also has another kind of relative reference that begins with `//`.

> A relative reference that begins with two slash characters is termed a network-path reference; such references are rarely used.

See "4.2.  Relative Reference" in https://datatracker.ietf.org/doc/rfc3986/

**Comment by zvr** [comment]
We're talking about filenames, not URIs. So, there should only be "relative-path" references (to follow the nomenclature of RFC3986).

I don't even understand why there is a reference to this RFC. I'd rewrite the whole sentence as simply:

> Every filename starts with `./`.

**Comment by bact** [comment]
Will "absolute-path" with a single slash (`/`) prefix (also from 4.2.  Relative Reference) possible in this context?

**Comment by zvr** [comment]
I don't think so, since we're talking about which files _inside a package_ should be excluded when computing the verification hash.  It makes no sense to use absolute paths for these .

But probably @goneall should be the one to decide, since he's more proficient in this SPDXv2 verification stuff.

**Comment by bact** [comment]
Thanks. Would be great if it can be simplified.

For reference, the RFC reference is from https://spdx.github.io/spdx-spec/v2.3/package-information/#742-intent and also the description there does not have "in general".

**Comment by ilans** [comment]
Created a PR: https://github.com/spdx/spdx-3-model/pull/913
