### ISSUE TITLE
Indentation of bullets in Licensing profile is off

### ISSUE THREAD

**Issue by ilans** [spdx/spdx-3-model#916]
I checked on both Chrome and Safari and the bullet points are aligned to left:
> <img width="712" alt="image" src="https://github.com/user-attachments/assets/9b5ddbbc-73af-49fb-b9d6-3272cfd71847">

We use 2 spaces for indentation:
> <img width="362" alt="image" src="https://github.com/user-attachments/assets/2135239e-a348-41c0-968f-8cf0f2f7f944">
Which should be fine. But some markdown formatters require 4 spaces.

I don't know if 4 spaces will solve it, but it's worth a try...

**Comment by bact** [comment]
We have two options here:

1) Use 4-space indent. To make goes well with Python-Markdown that MkDocs use.
2) Avoid nested unordered list (as we have it before).

I'm not sure which one is better for PDF generation (considering #834), so maybe better let @zvr decide on this.

----

### Option 1: 4-space

![](https://github.com/user-attachments/assets/0a1a66d9-daeb-4cb9-bd69-26a654f63f2a)

Code for option 1:

```markdown
- for Packages:
    - would include ...
    - would not include ...
- for Files:
    - would include ...
    - would not include ...
- for Snippets:
    - would include ...
    - would not include ...
```

### Option 2: One-level unordered list

![](https://github.com/user-attachments/assets/5d010c67-2255-49e5-ae34-a1cfdea7ec3b)

Code for option 2:

```markdown
for Packages:

- would include ...
- would not include ...

for Files:

- would include ...
- would not include ...

for Snippets:

- would include ...
- would not include ...
```

**Comment by bact** [comment]
btw, @ilans if you want to try around the Markdown and see how it would look like after MkDocs process it into HTML, the MkDocs build instruction is here:
https://github.com/spdx/spdx-spec/blob/development/v3.0.1/build.md

To avoid issue when copying dirs, in the step 3.2, use instead the updated commands in https://github.com/spdx/spdx-spec/pull/1148

**Comment by ilans** [comment]
We could collapse it, but it's definitely not as readable as with a tree. The 4 spaces should work fine for all formatters and would produce the original intended (and indented 😅) result. But collapsing is fine.

**Comment by bact** [comment]
If the 4-space indent doesn't make an issue with PDF generation, I also support that.
