### ISSUE TITLE
Summary vs Intent in the markdown files

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#92]
The SPDX2 specification uses the two headings "Description" and "Intent" for describing the various fields of the model. This makes it obvious to me that "Description" provides general information about what the field is while "Intent" specifies why this field is there and how it should be used.

On the other hand, the SPDX3 markdown files use "Summary" and "Description", which I'm having a hard time distinguishing. Is "Summary" just a short form of "Description"? There are instances where they are essentially the same, e.g. for [Annotation](https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/Annotation.md).

@zvr, @goneall, could you provide me with some insight into what the difference between "Summary" and "Description" is and why we changed "Intent" to "Summary"?

**Comment by goneall** [comment]
@zvr correct me if I'm wrong, but I believe the summary will be put in the schema documentation whereas the longer description will be in the documentation targeted for humans (e.g. markdown, website).  I think it would be fine if the summary and description are the same for short/simple fields.  You can always add "intent" in the longer description - e.g. - "The intent of ..."

**Comment by armintaenzertng** [comment]
Ah, thanks Gary, that is very good to know! :)
