### ISSUE TITLE
Relationship 'NONE' and 'NOASSERTION' individuals

### ISSUE THREAD

**Issue by ilans** [spdx/spdx-3-model#927]
From [Relationship](https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Classes/Relationship/):

1. > To explicitly assert that no such relationships exist, the to property should contain the 'NONE' individual and no other elements.
A relationship that contains 'NONE' and additional elements in the to property is not valid.

2. > To explicitly assert that no assertions are being made regarding the existence of such relationships, the to property should contain the 'NOASSERTION' individual.

Questions:

- Why use 'NONE' and 'NOASSERTION' instead of the actual IDs of those individuals.
  - 'NONE' should be `NoneElement`
  - 'NOASSERTION' should be `NoAssertionElement`
- While constraint 1 requires 'NONE' to be the only `to` property, constraint 2 doesn't require it for 'NOASSERTION'. Was this intentional? Is it ok to have multiple `to` properties when using `NoAssertionElement` (in the same Relationship)?

**Comment by goneall** [comment]
> Why use 'NONE' and 'NOASSERTION' instead of the actual IDs of those individuals.
'NONE' should be NoneElement
'NOASSERTION' should be NoAssertionElement

@ilans - you're correct - we should fix the documentation to refer to `NoneElement` and `NoAssertionElement`

> While constraint 1 requires 'NONE' to be the only to property, constraint 2 doesn't require it for 'NOASSERTION'. Was this intentional? Is it ok to have multiple to properties when using NoAssertionElement (in the same Relationship)?

Yes - I do recall the discussion, but I don't recall exactly the reasoning.  There is one similar use case in licensing where I may want to express "This package has a concluded license of [some license] AND I know that I don't know if there are other licenses that apply.  For this use case, however, I would expect a license expression of "[some license] AND NOASSERTION" or a `ConjunctiveLicenseSet` with members [some license] and `NoAssertionLicense`.  I suppose we could have multiple To's to express the same thing?

**Comment by bact** [comment]
My reading:

A contains [ B, C, NOASSERTION ]

means it is asserted that A contains B and C, at the same time does not claim that A only contains B and C. There can be something more or there can be nothing more.

So it should be possible to write:

something contains [ ..., NOASSERTION],

but it should not be possible to write:

something contains [ ..., NONE ].
