### ISSUE TITLE
Change contentType to mediaType

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/spdx-3-model#93]
The file property `contentType` will give information about what is officially called the file's "media type".
I therefore propose to change the name of `contentType` to `mediaType` to make this more readily apparent.

**Comment by prabhavsingh** [comment]
I want work on this issue. Can you please assign it to me Or should I start working and create a pr without it begin assigned to me.

**Comment by armintaenzertng** [comment]
Sorry I didn't update this. @iamwillbar has given a rationale why we will keep the name contentType [here](https://github.com/spdx/spdx-3-model/issues/82#issuecomment-1462544306).
This issue is therefore closed.
