### ISSUE TITLE
Agent or Identity

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#94]
The newly-simplified creation portion of the model reflects tech team consensus on the following features:

* The single createdBy top-level class is an Element, not a string.
* The top-level class has three sub-classes: Person, Organization, SoftwareAgent.
* Tool is a separate Element type, not under the top-level class, used in the new optional createdUsing property

If software can create on its own and has an individual instance identifier, it is a SoftwareAgent.  If it cannot act on its own then it is a Tool.

![spdx-id1](https://user-images.githubusercontent.com/19152940/222727722-ffa685b8-a1ff-4bd0-9430-6b419150a744.jpg)

The only open issue is what name should be given to the top-level Element.  In defining the SPDX v3 model, naming is less important than functionality, but naming does matter for external communication.  Sean and David have expressed conflicting views on which name, "Agent" or "Identity", best promotes understanding the SPDX model by the wider cybersecurity community.

**David:**
* The grayed-out "Identity" class, representing future work, is incorrect.  The community understands Identity to include SoftwareAgent:
    * [The law](https://www.law.cornell.edu/wex/legal_person) uses "Legal Person" as the parent of Person and Organization -- "an individual, company, or other entity which has legal rights and is subject to obligations."  Its subclasses are "Natural Person" for human entities and "[Juridical Person](https://en.wikipedia.org/wiki/Legal_person)" for non-human entities.
    * The law does not use Identity to mean Legal Person, it has only other meanings ("detection, prevention, and mitigation of [identity theft](https://www.law.cornell.edu/cfr/text/17/162.30)", "[chemical identity](https://www.law.cornell.edu/cfr/text/40/350.5) of an extremely hazardous substance", etc.)
* The software community includes SoftwareAgent Identities:
    * Azure Active Directory [device identity](https://learn.microsoft.com/en-us/azure/active-directory/devices/overview)
    * [Decentralized Identifiers](https://www.w3.org/TR/did-core/#dfn-decentralized-identifiers): "Anything can be the subject of a DID: person, group, organization, thing, or concept"
    * The software [Actor Model](https://en.wikipedia.org/wiki/Actor_model) adopts the philosophy that everything is an actor whose identity is a "mailbox". In an actor model ([Clojure](https://clojure.org/about/state#actors)), state is encapsulated in an actor (identity) and can only be affected/seen via the passing of messages (values).
    * [DoD](https://public.cyber.mil/pki-pke/about/#dod-pki) identities include non-person entities (e.g., web servers, network devices, routers, applications)
* For future work, Identity, not Agent, needs to be the superclass, because a Person or other entity is identical whether the entity is acting as an Agent or merely being referred to, as on a list.
    * If future work were to define Identity, it would have to include Person, Organization and SoftwareAgent, and it would have to apply to both the act of creating and the fact of being referenced.
    * Calling the top-level class "Agent" is not incorrect for SBOM creators, but calling it Agent now precludes calling it Identity in the future. Including both in the model would require defining a semantic distinction between them as well as the relationship of the Person (Org / SW-Agent) class to each of them.

**Comment by sbarnum** [comment]
I would agree with the first three bullets at the top of this issue

> The newly-simplified creation portion of the model reflects tech team consensus on the following features:
> 
> - The single createdBy top-level class is an Element, not a string.
> - The top-level class has three sub-classes: Person, Organization, SoftwareAgent.
> - Tool is a separate Element type, not under the top-level class, used in the new optional createdUsing property

I would slightly disagree on the specific characterization of the next line.

> If software can create on its own and has an individual instance identifier, it is a SoftwareAgent. If it cannot act on its own then it is a Tool.

I do not believe that the fact a SoftwareAgent can act on its own is what _causes_ a distinction between it and a Tool. Rather, I would propose that the two represent different positions along an abstraction continuum for tools where a class of tool could be something like "tax preparation software", a Tool could be something like "TurboTax Premium 2022" and a SoftwareAgent could be a running instance of TurboTax Premium 2022 on a computer. They are what they are in relation to each other and the ability a SoftwareAgent has to "act" is simply a characteristic it has that a Tool does not.

I agree with the model snippet above as representing our minimal consensus compromise for SPDX 3.0, though I would strongly argue for removing the grayed-out "Identity" class and its arrows as I do not believe it is part of our current compromise consensus and I would agree with David that it very likely does not represent how the concept of Identity will be modeled _when_ we decide to pursue it in post-3.0 evolution.
The Agent class with the three sub-classes Person, Organization and SoftwareAgent along with the separate Tool class give us the minimum we need for 3.0 without muddying the water or locking us into unsettled structure or semantics that will likely cause significant breaking change in the future.

In response to David's rationale bullets:

- I would agree that the grayed-out Identity class in the model snippet "representing future work" is very likely incorrect and I would assert that it should be removed
- For the remaining bullets, I believe we are still talking about different concepts and conflating them together.
   - The concept of Identity within an Identity Management scope of context as represented by the Azure Active Directory and the DoD identities bullets above is a relevant concept within the cyber domain and is likely eventually relevant for SPDX but I would propose it is not what we are targeting with our minimal consensus compromise for SPDX 3.0. There is MUCH more to this concept than we currently require for 3.0 or have barely begun to discuss and model. In the interests of immediate progress on 3.0 I would propose we explicitly table that effort for post-3.0.
   - I would assert that the concept and matter of identifiers (whether decentralized or not) is equally relevant to both the concept of Agents and to the concept of Identity within Identity Management and should not be considered as distinguishing driver between the two.
   - I would strongly assert that Agent and not Identity is the correct term for the top-level class in the minimal consensus compromise. 
      - We have barely begun to discuss the concept of Identity that David is describing here (though it certainly warrants future discussion) and as such we do not have confidence that the current minimal consensus compromise structure correctly represents even the simplest beginning of that concept. This is further complicated by the reality that anyone reading the term Identity and interpreting it in the context that David appears to be interpreting it is likely going to expect far more structure and semantics to support it than we are attempting for 3.0.
      - What we have agreed to target with our minimal consensus compromise structure is 
         - The ability to ability to express minimal details (such as name and possible identifiers) of a Person, Organization, or SoftwareAgent that created or originated an Element.
         - The ability to express minimal details (such as name and possible identifiers) of some entity that created or originated an Element where it may be unclear if that entity is a Person, Organization or a SoftwareAgent.
      - For minimal capability and to maintain flexibility for future evolution and for integration with the broader domain of use what we are looking to model is the concept of some _entity that has the capacity to act_ (at a minimum act=creation or act=origination) without ANY further unnecessary limitation or specialization of the concept.
         - This concept is not new and exists throughout a range of relevant existing ontologies as Agent
            - The Friend-Of-A-Friend ontology (one of the most commonly used basic ontologies) defines a [foaf:Agent](http://xmlns.com/foaf/0.1/#term_Agent) class with the following characterizations:
               -  `The [foaf:Agent](http://xmlns.com/foaf/0.1/#term_Agent) class is the class of agents; things that do stuff. A well known sub-class is [foaf:Person](http://xmlns.com/foaf/0.1/#term_Person), representing people. Other kinds of agents include [foaf:Organization](http://xmlns.com/foaf/0.1/#term_Organization) and [foaf:Group](http://xmlns.com/foaf/0.1/#term_Group).
               - `The [foaf:Agent](http://xmlns.com/foaf/0.1/#term_Agent) class is useful in a few places in FOAF where [foaf:Person](http://xmlns.com/foaf/0.1/#term_Person) would have been overly specific. For example, the IM chat ID properties such as jabberID are typically associated with people, but sometimes belong to software bots.`
               - Does that sound familiar? It is very similar to what we are attempting to cover with our minimal consensus compromise.
            - The dbpedia ontology defines an [Agent](https://dbpedia.org/ontology/Agent) class as 
               - > Analogous to a foaf:Agent, an agent is an entity that acts.
            - The Financial Industry Business Ontology (one of the most comprehensive formal ontologies leveraged with the financial sector and other commercial domains) defines an [Agents Ontology](https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/Agents/) with the following abstract:
               - > This ontology defines the concept of autonomous agent for use in other FIBO ontology elements. As defined here, autonomous agent corresponds to what is often referred to as "agent" in software and other systems. It is defined as any entity which is able to act on its own part, and embraces all such things, including people, animals, software agents organizations and all forms of legal persons, although not all of these concepts are elaborated in FIBO as not all are relevant to financial services.
               - Again, doesn't this sound familiar to what we are attempting to cover.
            - The W3C Provenance Ontology (PROV-O) defines a [prov:Agent](https://www.w3.org/TR/prov-o/#Agent) class as
               - > An agent is something that bears some form of responsibility for an activity taking place, for the existence of an entity, or for another agent's activity.
- I would propose that the term we use for our class should be Agent defined as an entity with the capacity to act.

**Comment by davaya** [comment]
Close: decided to use Agent at the 3/7 tech team meeting.

**Comment by davaya** [comment]
Close: consensus is to use Agent at the 3/7 tech team meeting.

**Comment by maxhbr** [comment]
The markdown files (especially in 3.0-rc1) currently do not have an Actor, but instead use [Entity](https://github.com/spdx/spdx-3-model/blob/3.0-rc1/model/Core/Classes/Entity.md) and [Identity](https://github.com/spdx/spdx-3-model/blob/3.0-rc1/model/Core/Classes/Identity.md). This does not match the consensus referenced here.

**Comment by davaya** [comment]
See #202, which has not yet been merged.  It should address this issue as well.

**Comment by goneall** [comment]
Reference decision on https://github.com/spdx/meetings/blob/main/tech/2023-02-07.md

**Comment by goneall** [comment]
@nishakm will create a PR with these changes.

Markdown files will be updated to match the model picture above without the greyed out Identity classes.

@maxhbr @sbarnum will review.
